### ISSUE TITLE
No network connection when on mobile broadband

### ISSUE THREAD

**Issue by andreas-h** [k9mail/k-9#1010]
When I'm on WiFi, everything works fine.

When not on WiFi but on mobile broadband, K-9 cannot connect to IMAP nor to SMTP servers. However there is no general problem with internet connectivity as e.g. Firefox works normal.

I'm using the most recent K-9 that's on F-Droid, and I'm running CM13.

**Comment by lbdroid** [comment]
Probably not a k9mail issue. This is VERY likely a problem with your service provider. It is extremely common to block port 25. IMAP is also possible, but less common.

Are you using cleartext on either? Cleartext IMAP is port 143, cleartext SMTP is *usually* 25, but can also be 587. SSL IMAP is port 993, SSL SMTP is port 465.

First thing to do is try the SSL ports. If that works, then you're good to go. If not, then you may have to implement some networking voodoo. If you have a land based home network, then you should be able to set up a relay using a different port that isn't blocked by your mobile service provider. Most routers do NOT ship in a manner that can do this, but if your router is supported by OpenWRT (or if you replace it with a router that is supported by OpenWRT), then it becomes a pretty easy task. You could assign, say port 80 (HTTP) to IMAP, and 443 (HTTPS) to SMTP. Mobile service provider *can't* block those two ports since doing so would completely cripple the network for even the least sophisticated customers.

**Comment by andreas-h** [comment]
Yes, sorry for the noise.  Turned out my provider had configured a wrong APN on my phone. With the correct APN, it works.
