### ISSUE TITLE
Archive multiple selected emails in Unified Inbox

### ISSUE THREAD

**Issue by spollard** [k9mail/k-9#1041]
### Expected behaviour

An 'archive selected' button would appear after selecting multiple emails in the Unified Inbox. I noticed that this button is displayed when you select multiple emails in a specific account's inbox. 
### Actual behaviour

There is no button to do this yet. 
### Steps to reproduce
1. Select multiple emails in the Unified Inbox
2. See that there is no 'archive selected' button
### Environment

K-9 Mail version: v5.007

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment]
That's because some account types don't support the Archive functionality. Our current solution for that is not showing the Archive action in the Unified Inbox.

In the future we could archive messages that can be archived and leave the ones that can't be archived selected (and maybe display a message to the user stating why that is).

**Comment by spollard** [comment]
That makes sense. Thanks for letting me know. 

One could detect if all the user's accounts support archiving and therefore all messages can be archived. This is my case.

**Comment by boconnell** [comment]
Interested in taking this on. Is https://github.com/k9mail/k-9/issues/1041#issuecomment-181021602 still the desired functionality? Any desired copy for the message to the user displaying why the app did not archive some messages?

**Comment by philipwhiuk** [comment]
"Some messages couldn't be archived as their account doesn't support this feature" would be a decent line IMO.

I think a Toast is probably fine for this.
