### ISSUE TITLE
High battery consumption (request: disable sync on low radio signal?)

### ISSUE THREAD

**Issue by Utini2000** [k9mail/k-9#1086]
Hey there,

I am a long time K9 user which is using K9 for almost 5 years now. Everything is working perfectly except one thing: Battery consumption is way too high when K9 is just running in the backround.

I am running 2x gmail push accounts + 2x own-mail-server imap accounts on a Nexus 6 (previously Nexus 4 and HTC Desire HD).

On my large Nexus 6 screen 2hours of "screen on time" is consuming as much or sometimes less battery than K9 which would run in the backround. 
On my Nexus4, K9 would sometimes completely drain the battery within 1 hour.

My guess is that K9 is using so much battery because of low radio signals or being not connected to HSDPA?

I tried creating a tasker script which would disable android auto-sync (which also stops auto-sync + push in K9) when the radio signal is low for a certain amount of time and only reactivate it when the signal is good again for a certain amount of time.

Battery consumption is still high but better than before so I am wondering if K9 could get this feature out-of-the-box?

I don't know what other ways are possible to minify battery consumption but K9 is, just right now as I am writing here, still using 1% more battery than my screen would use in those 30-40mins of writing (I am connected to WiFi at home or have full HSDPA+ signal while driving in thr car).

For troubleshooting:
I re-installed K9 several times (also on several devices). 

Sizes of e-mail accounts (if relevant):
Gmail push #1: 114MB
Gmail push #2: 6MB
Own mail server imap #1: 331kb (syncs every 10 mins)
Own mail server imap #2: 3MB (syncs every 10 mins)

Thanks in advance !

**Comment by locutis-of-borg-1999** [comment]
I have the same issue.  It is VERY high drain, and I ONLY use push; NO POLLING!

'Droid reported tha75% of the battery use went to K-9!!!!!!!!!!

**Comment by doodhout** [comment]
Doesn't removing K9Mail from the 'open app switcher' take care of that already? I find that I get indeed higher battery drain when I forget to remove it from the list of open apps, thus keeping it opened. But if I don't forget and do remove it, it generally doesn't happen.

**Comment by philipwhiuk** [comment]
I'd definitely like to see a package of improvements whereby the phone is allowed to sync more often when on WiFi and less often when mobile data only / when reception is poor.

**Comment by RojoDiablo** [comment]
Similar to locutus-of-borg's experience, I dropped polling to 2 hours after having consumption issues and now android reports K-9 is keeping the radio active for the entire time between polls, not just polls themselves.  Keep-awake time is normal, such as 1 minute, but radio time reports hours.

This is only an issue when my phone (LG G4) is *not* on an LTE or wifi data connection, which is always at work due to building interference.

With no phone usage otherwise, K-9 will use nearly 30% of my battery within 2 hours.  If I force-stop the app, battery usage goes flat.

**Comment by crazy-max** [comment]
Hi, not sure if i have to create another issue but K9 drains a lot of battery.
I would say since 5.008.

![screenshot_2016-05-09-17-52-42](https://cloud.githubusercontent.com/assets/1951866/15119428/301e1d9e-1611-11e6-8a46-562352228f3c.png)

* Nexus 5
* CyanogenMod 11 (Android 4.4.4)
* K-9 Mail 5.010

**Comment by locutis-of-borg-1999** [comment]
I rolled back as far as seemed feasible, per the changelog, BEYOND 5.008...  I had to do a reboot to notice any appreciable current draw savings.  HOWEVER, K9 STILL is 40% to 75% of the current drain, on the average, in PUSH only mode, NO polling.

And doodhout , that doesn't seem logical, as killing/stopping an app' still leaves it in that list.  However, I tried anyway, before reverting.  It did NOT help.  

Let us not forget that the dev' relies heavily upon Google, or IS Google.

**Comment by Rocco83** [comment]
What about a custom trigger to stop any sync if battery goes below a certain level?

**Comment by Utini2000** [comment]
@Rocco83 I am currently usinger Tasker to disable Sync when NOT on 4G/3G and also when the battery is below 20%.

Not the most elegant solution but can't wait for k9 to ever implement it :/

**Comment by cketti** [comment]
Newer Android versions already have a battery saver mode that kicks in when battery is low. I believe it disables background operations. That's not really functionality I think we should replicate in K-9 Mail.

We definitely want to improve the power efficiency of K-9 Mail. But I don't think this issue is helpful.
