### ISSUE TITLE
Certificates still broken

### ISSUE THREAD

**Issue by mateli** [k9mail/k-9#1111]
Full discussion with patch. This only recently became an issue for me, I guess Dreamhost changed something. Possibly this was fixed but became unfixed. 

https://code.google.com/archive/p/k9mail/issues/3976

**Comment by philipwhiuk** [comment]
Either it's a bug in BouncyCastle (unlikely) or it's a bug in Dreamhost's certificate deployment (plausible).

Have you tried contacting Dreamhost. What's the behaviour on other platforms?

**Comment by cketti** [comment]
The linked issue is outdated. If you want to report a new bug please fill out the issue template and include enough information to reproduce the issue, at the minimum the server settings.

**Comment by mateli** [comment]
The linked issue isn't outdated and clearly shows what's wrong, including a patch. Has that patch been merged into K9?

As the linked issue clearly shows there are nothing wrong with android or dreamhost.

The behavior on other platforms (thunderbird evolution etc).

**Comment by mateli** [comment]
The linked issue isn't outdated and clearly shows what's wrong, including a patch. Has that patch been merged into K9?

As the linked issue clearly shows there are nothing wrong with android or dreamhost.

The behavior on other platforms (thunderbird evolution etc) is that those asks me if I want to accept the self-signed certificate. As they should. And then when I have answered yes it works.

**Comment by philipwhiuk** [comment]
The patched code (#136) relies on tests that will presumably fail in the future when the correctly created base-64 encoded plain-text certification in the test expires. That's not particularly useful from a testing perspective.

It's not been merged because it needs re-assessing following more recent changes.

From S/O:

> The discussion seems to imply that the error is caused by certificate chains that have a self-signed cert in the middle of the chain, and OpenSSL is more tolerant of this than Android's SSL implementation (which might be why Thunderbird works).

I'm not entirely sure what S/O mean by this. Either it's a valid certificate chain or it's not. A self-signed certificate can be fine only if it's the root cert. You can't pretend you're signed by a parent cert when you're not. That would be fraud.

Specifically, I worry that we might be falling into viewing the chain as a simple tree: https://www.blackhat.com/presentations/bh-usa-09/MARLINSPIKE/BHUSA09-Marlinspike-DefeatSSL-SLIDES.pdf

At minimum it would need to be re-based on-top of the "recent changes to certificate validation"

I might get time to look at it. But I still don't like the impossible to maintain unit test - there'd be no way to fix the test when it breaks - you'd have to start from scratch. It might be possible to mock the response and test it that way, rather than relying on actual certs.

I have an HTC M7. I don't know if this device can reproduce the issue or not?

**Comment by mateli** [comment]
I doubt that the fraud argument could be reasonable with dreamhost. Neglect possibly but that's different.

Other mail applications like thunderbird and evince warns about the problems and asks the user if they accept the certificate. Not very user friendly but it works.
