### ISSUE TITLE
How to delete suggested addresses when composing new email

### ISSUE THREAD

**Issue by k5fni** [k9mail/k-9#1118]
### Expected behaviour
Tell us what should happen
When K-9 makes suggestions for email addresses during typing in addressees, old ones should time out or user should be able to delete the ones that show up.
### Actual behaviour
Tell us what happens instead
Out-of-date addresses (even from folks dead several years) show up every time I begin to enter similarly spelled addressees' names
### Steps to reproduce
1.Begin to create a fresh email
2.Type in an address
3.

### Environment
K-9 Mail version:
5.000
Android version:
Kindle Fire HD 8.5.1
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment]
Email addresses are auto-completed from the system's contact database. You have to remove the associated contacts to get rid of suggestions for auto-completion.

**Comment by k5fni** [comment]
You might think so. But, friends/relatives dead and long gone from the system contact database STILL appear as suggestions. That was my reason to take the effort to ask how to get rid of addresses I did not want suggested. You did not help me with your answer. 

--
Rick Herndon K5FNI

**Comment by cketti** [comment]
K-9 Mail doesn't make up contacts or holds on to them. So those contacts are definitely in the system database. Whether you can actually see them in your Contacts app is another matter. You could ask for help on the [K-9 Mail mailing list](http://groups.google.com/group/k-9-mail). But since this is not a K-9 Mail issue, you might be better off asking the creator of your Contacts app for help.
