### ISSUE TITLE
Serbian language not available

### ISSUE THREAD

**Issue by pejakm** [k9mail/k-9#1136]
Hi.

Serbian language is only available in [K-9 Mail v5.104 (alpha)](https://github.com/k9mail/k-9/releases/tag/5.104) release. No other consecutive alpha or stable releases have support for Serbian (it's not even on the drop-down list of languages in Global options->Display).

**Comment by cketti** [comment]
The changelog for v5.105 states that all changes in v5.104 have been reverted except for certain fixes.
That's because the v5.104 line was not stable enough for even an alpha release. Consequent alpha releases were made from the v5.105 line. However, development continued in the v5.104 line. The current master contains the Serbian translation and so a new alpha version built from it will also contain the Serbian translation.

**Comment by pejakm** [comment]
> The changelog for v5.105 states that all changes in v5.104 have been reverted except for certain fixes.

Sorry, I missed that somehow.

> The current master contains the Serbian translation and so a new alpha version built from it will also contain the Serbian translation.

Yes, I was about to close this issue, because I've successfully built the latest master few minutes ago and realized the Serbian translation is in. :)
