### ISSUE TITLE
read emails are disappearing

### ISSUE THREAD

**Issue by norbusan** [k9mail/k-9#1180]
Dear all

I have some recurring hiccups that, after reading an email and returning to the inbox, the email disappears.

I need to leave the inbox, maybe refresh, to bring the hidden emails back.

I have root access and can provide further information if over tells me what is needed.

Device: Nexus 6p
Android: 6.0.1

Thanks

**Comment by cketti** [comment]
Make sure you don't tap the unread count in the account list screen or folder list screen. Because that will filter the list to show only unread messages. Opening a message marks it as read and hence removes it from the list of unread messages.

In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

**Comment by norbusan** [comment]
Sorry for the noise. Thanks for the explanation - I didn't know that this is a separate button.

I will use the mailing list in the future.

Thanks
