### ISSUE TITLE
TODO: Test new UI elements on API 15 devices

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#1288]
Make sure all the recent UI changes work well on devices with our current minSdkVersion 14.
Test both light and dark theme.

**Comment by Valodim** [comment]
Done. I tested:

* without crypto provider
- compose screen
- view regular mail
- view encrypted mail

* with crypto provider
- compose screen
- crypto selector
- alternate recipient selector
- pgp/inline info dialog
- actually send mail
- reply to, and actually send
- warning if no signing key selected
- view regular mail
- view encrypted mail

findings:
- NPE because `invalidateOptionsMenu` is handled differently (#1702)
- `setContentView` shows the indeterminate progress bar for some reason? just disabling it afterwards works (#1703)

**Comment by cketti** [comment]
:+1: 

Fixes for both issues have been merged.
