### ISSUE TITLE
Please excuse my brevity.

### ISSUE THREAD

**Issue by JungHoonHyo** [k9mail/k-9#1349]
### Expected behaviour
In a written message i would like to know more about the range of brevity.
For example such as less than 25 letters.

### Actual behaviour
In a written message I looked at the letters was a brevity worry about it.

###Environment

K-9 Mail version:5.010

Android version:4.4.2

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by philipwhiuk** [comment]
Unfortunately it's not possible to know the problem you are facing. You may want to try using your native language in a thread to the K-9 mail users list: https://groups.google.com/forum/#!forum/k-9-mail I'm closing this because it isn't possible to work out the issue you are facing so it would be to resolve.
