### ISSUE TITLE
Mail view context menu UX is a bit disappointing

### ISSUE THREAD

**Issue by KopiasCsaba** [k9mail/k-9#1363]
Hi!

The first time i've used K-9 mail (long long time ago) i remember that i was puzzled, "How can i reply to this?". Then I found the "Send -> Reply" menu. 

I think that is not really good from the viewpoint of user experience.

I think the most used feature is the reply menu, that should have it's own button on the toolbar, it should not be hidden under a context menu's second option.

So it would be good to think about which features are the most commonly used, and to put them to a higher visibility / easier to be reached point. 

Like:
 * i never moved any emails of mine (thunderbird's filters doing that).
 * Previous / Next mail should be a swipe to left / right and then it would free up two buttons on the bottom toolbar.
 * Reply, Reply all could go to the right top maybe?
 * Show headers, copy, move, refile (I'm not  even sure what it does) mark unread could go to somewhere a bit out of sight, but still with the most used features (show headers, move) on the top.

So, i thought i share my ideas with you, thank you for k-9 mail!

**Comment by philipwhiuk** [comment]
The visible actions are customisable: Settings -> Global Settings -> Display -> Visible message actions

**Comment by KopiasCsaba** [comment]
Actually, almost none of the problems addressed above could be solved there:(

**Comment by philipwhiuk** [comment]
There's a few things that could be moved into Visible Message Actions.

Swipe left and right will probably not happen, because of HTML e-mail that allows you to scroll left and right breaks that.

Move, Copy, Archive and the parent 'Refile' - which allows you to select one of these are already part of the Visible Message Actions.

A wider point is we have many many tickets for the design overhaul, including: #611 and #1341 We don't need 3 open to cover every single permutation of what people want. 

Nor is it likely for the app to support every single user's personal style. Settings which are used are good. Settings which are barely used just make the app more complex.

Adding more issues with potential solutions just crowds the queue. Realistically, if we make the design more Material based, the ticket may likely become invalid anyway.

This isn't related to the outbox issue either.

**Comment by KopiasCsaba** [comment]
Okay, thats fair enough!
