### ISSUE TITLE
warning on no subject -- make configurable

### ISSUE THREAD

**Issue by njeyaakili** [k9mail/k-9#1415]
When an option like: "#1089 - adding warning on no subject" is introduced, could a configuration option be included so that the behavior (which changes the existing UX) can be optionally disabled by the user.

**Comment by cketti** [comment]
No, we already have too many settings.

Please use the mailing list for questions or discussions

**Comment by z28cueball** [comment]
This is obnoxious. I hate the warning and can't believe you won't allow it to be disabled.

**Comment by Valodim** [comment]
Hm, can't this behavior be easily achieved by "double clicking" the send button?

Right now it sends when the user presses a second time, I wonder if it would solve this problem for everyone if we changed the message to "Hit twice to send anyways", and bound a double-click to send without complaining in the first place.

In general it's better to have functionality in the UI directly, rather than making it configurable. Getting used to double-tapping send rather than single tapping is a "setting" (as in, habit) that stays with the user, rather than the app :)

**Comment by z28cueball** [comment]
You're totally missing the point that if you reply to a message with a subject, you'll only need to click send once. So there's no way to develop a habit, because the necessary number of clicks will not always be the same.
I completely disagree with you. The more configurable something is, the better it is.  One size does not fit all. That's the beauty of Android. If you want someone else deciding what's best for everyone, get an iPhone.

**Comment by Valodim** [comment]
Why? If sending regardless of subject is what you want to do, you can just always double tap, can you not?

**Comment by z28cueball** [comment]
Well, other than not wanting to double tap ever... What happens if you double tap when there IS a subject?  (Answering this from email instead of the website to try that.)


-------- Original Message --------

**Comment by z28cueball** [comment]
Ok so the second click falls on the previous screen. Might be a problem depending on what the previous screen is. 
But regardless... I don't want to double click at all. I don't double click to send text messages, Facebook messages, or anything else. Forming a different habit for one specific message type is annoying.
Everyone is different. That's why this should be an OPTION.
I only upgraded because I thought I might be having some issues with the new battery saving "features" in Marshmallow. I also dislike the new disappearing labels for the header fields when composing a message.
I think my best option is to downgrade to a version without these "features".  Any idea if there are any issues with Marshmallow in the older versions? 


-------- Original Message --------

**Comment by philipwhiuk** [comment]
Text messages and instant messages don't have subjects.

**Comment by z28cueball** [comment]
That's beside the point.  If you are happy with sometimes pressing once to send an email, and sometimes pressing twice, then that's fine.  I have no desire to impose my personal preferences on other people.  That's why I think it should be an option.

**Comment by philipwhiuk** [comment]
We're making an app. Inevitably that **requires** imposing design preferences on people. Emails have subjects. On a personal note I assume emails without subjects will be spam. 

Adding configuration options has a cost. It needs more tests that have to be maintained, it makes building a good UI that incorporates all the settings harder. It's certainly not free.

**Comment by z28cueball** [comment]
Ok but this is imposing a design change.  K9 has been around for YEARS without requiring a subject.
On a personal note, I use e-mail to send quick notes to myself at work, and a few other people that I collaborate with closely.  I don't have the time or inclination to enter a subject, nor is there any need for it, nor do the people I e-mail assume e-mails from me are spam.
I'm not disputing that this is a benefit for some people.  I don't know why you are so narrow-minded when it comes to accepting that this is NOT a benefit for others.
I'd be more than happy to donate.  All I want is to not have to participate in this new "feature".  How much of a donation to make it optional?
And do you know, are there any performance issues with using an older version without this "feature" on Marshmallow?

**Comment by philipwhiuk** [comment]
> I don't know why you are so narrow-minded when it comes to accepting that this is NOT a benefit for others.

It's a feature of every email client I've ever used, so that tells me it is useful. I don't doubt you have use of subject-less emails but I dispute it being widely used.

> And do you know, are there any performance issues with using an older version without this "feature" on Marshmallow?

Behaviour surrounding Doze is broken in both versions but when we fix it, it won't be back-ported. There are probably several performance improvements we've released and numerous definite bug fixes.

https://imgs.xkcd.com/comics/workflow.png

**Comment by z28cueball** [comment]
Well, I'm not going to dispute whether it's widely used or not because I have absolutely no data to base an opinion on.  I have no idea how many people actually asked for this, versus how many people have asked for it to be optional.  Where this changes a well-established behavior of the program, I think it should be optional.  You think it shouldn't.  I doubt either one of us is going to change the other one's mind.  I still think the more flexibility offered, the more adaptable it is to each individual's situation, but from the sounds of things, there's no way I'm going to convince the powers that be to make this optional.
Since Doze is broken in both, I guess the best option here is to just roll back to the last version that had the UI I like.  If I can figure out how to compile the source, once the code is updated for Doze, I suppose I could alter a local copy of the code to remove the no-subject check and compile and use it.
On the Doze note - does turning off Battery Optimization for K9 fix the brokenness?
