### ISSUE TITLE
renaming (rebranding) the entire package

### ISSUE THREAD

**Issue by TDVvDlunn** [k9mail/k-9#1462]
I've thought about this suggestion and whether it will be offensive to post it here rather than to fork, refactor and push it to f-droid myself. A quick online search revealed that I'm not alone with my thoughts.

This e-mail client is fine, very fine, I love it. My respect to all contributors. But most likely it will never be accepted as a serious application. The reason is an ugly name and the the whole branding (icons). Do you really think that any serious company which is not a lemonade stand would like to see an ugly robo-dog icon on their main launcher? Most people don't even know what K9 means or stands for.

How do you think about to rename the entire package into "e-mail" or "eMail" or something similar without any fancy names additions and a simple envelope icon?

**Comment by clawoflight** [comment]
I would argue that `e-mail` is much too generic, and I'm probably not alone with that either.

A different, but unique and otherwise appropriate name, on the other hand, is something more people might consider.

**Comment by gdt** [comment]
Given the history of the project, I find your tone and dismissal of "serious" to be surprising.  People do community-based open source to address their own needs, and others help.  Suggesting changing the name for vague reasons about how unspecified companies might include this instead of the AOSP mail program in locked-down phones is quite a stretch.

I like the robodog icon, FWIW.

**Comment by mad-engineer** [comment]
@clawoflight I think email is fine. In the end you want to send and receive emails. There is no need to find a new name to override a very well established term which makes this app look like some special service but not an awesome email client.

@gdt Lets address the elephant in the room. Just type "k9 mail ugly" in google. The next suggestion will be "k9 mail ugly icon".

In addition the term "k9 mail ugly"  has ~16M hits on google. If only 1/16 are relevant hits, then still 1M hits are related to the ugly naming and icons.

I agree with OP that the app itself is a good piece of software and that the design and naming is a serious "Issue" therefore it's the right place to discuss it here without any sugar coat.

**Comment by Valodim** [comment]
So uh, anyone volunteering to put in the work? How about an icon suggestion?

**Comment by mad-engineer** [comment]
@Valodim I'm not sure but what do you mean by work? Refactor to eMail and use the [suggested ](https://design.google.com/icons/) material (Communication->Email) icon from google? For the launcher, there's just to pick one of the [free](http://www.flaticon.com/free-icons/envelope_495) envelope icons which fits into the 6.0.1 or Android N design.

**Comment by Valodim** [comment]
So your suggestion is to drop the K-9 brand identity altogether? That makes *no* sense.

**Comment by mad-engineer** [comment]
Imagine a poll around the world where unprejudiced people have to choose: "Which of this apps would you start if you want to send an email: eMail or K9-Mail"? How would you rate the score between both? I would go for 80/20% in the best case.

The point about common sense is clear. 

However, in a meritocracy, common sense often does not play a role since personal feelings are involved. It's a justified point from you and all contributors. And I don't want to devalue your work and will use K9 anyways. But as OP still would have been happier if you could make the app suitable for the large scale. It will put a serious note on it and will attract more and more developer as a good side effect.

**Comment by Valodim** [comment]
You base your reasoning on unprejudiced people, but in the real world you will be hard-pressed to find any of those. There is a reason they call 'em "speedos" and not "swim briefs", and that reason is brand identity. People need a specific name to address things by, or they won't be able to talk about them. There is also the matter of googleability - it's impossible to google for an app called "eMail".

Note that I'm not arguing that everything is great as it is. I talked to cketti about the possibility of a new icon and maybe hiring a designer to create one just recently, and we also definitely want a material redesign. It's just a matter that *someone has to do it*. We just don't exactly have volunteers lining up to get stuff done, and the material redesign in particular is a huge amount of work.

**Comment by mad-engineer** [comment]
@Valodim These are valid points.

Brand identity and, googleability, non ambiguous names are quite important. Thanks for pointing out that careless handling can indeed bring more harm than use. Personally I don't think the objection is the name and googleability but more the design an the launcher name. Also the work amount should not be underredistimated.

I need to think about it, look how other projects solve such ambiguous names.

**Comment by clawoflight** [comment]
@mad-engineer Other projects solve that exactly like K9 does: with _unique, catchy names and icons_.

If you wanted to change that, you would need to rebuild a strong brand identity from scratch - and try to carry some of the old over. That may be harder than starting a new project from scratch.

**Comment by Valodim** [comment]
There is an exception to this rule, and these are apps that come preinstalled. If your app comes with the OS, you can call it "Calendar" or "Email" or "Phone", but that's a really special position. Also, even though it's called email there, the name people use to refer to it is the "AOSP Email Client", so even in that case an ad-hoc brand name emerges.

**Comment by cketti** [comment]
Please feel free to fork K-9 Mail and make it a "serious application". Companies that are not lemonade stands sound like a lovely target audience.

Oh, and please let us know how 'attracting developers by having more users' goes for you.
