### ISSUE TITLE
Ability to "Pin" important messages so they're always accessible

### ISSUE THREAD

**Issue by odbol** [k9mail/k-9#1469]
Sometimes I'll get airline/concert tickets in my email months ahead of time. But since K-9 only keeps a limited number of the most recent messages, when I search for them when it's time to board the airplane, it can't find them. 

I'd love a way to "Pin" a message, so that it doesn't get removed when newer messages push it out.
## Possible implementation: 
1. Create a new IMAP folder called "__PINNED" or something.
2. Select a message, hit the menu, and choose "Pin message"
3. It simply copies the message into the "__PINNED" folder.
4. Add some special UI to access that folder, or show those messages at the top/bottom of the inbox?

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by odbol** [comment]
Another possible implementation is to never discard starred messages. If it has a star, it should always stay at the bottom of the list, no matter how old it is.

**Comment by 12people** [comment]
Just for context: Pinning is useful for the workflow of keeping a nearly empty Inbox and pinning messages one needs to return to instead of marking them as unread. "Mark as unread" makes the unread count unreliable, making it unclear how many messages are actually new and unread. That's why Google Inbox doesn't have "Mark as unread".

@obra Never discarding starred messages doesn't seem intuitive to me -- I wouldn't expect them to stay. What would work is changing stars to pins. Minor change, but pins do imply persistence while stars do not.

**Comment by gaborgabor** [comment]
+1
never discard starred messages. If it has a star, it should always stay at the bottom of the list, no matter how old it is.

**Comment by cketti** [comment]
Right now I'm in favor of using starred messages for pinning. Closing this issue in favor of #3369.
