### ISSUE TITLE
request: support more encryption schemes

### ISSUE THREAD

**Issue by incertia** [k9mail/k-9#1516]
k-9 mail can use encrypted authentication with cram-md5. if possible, let users select the encryption scheme so servers that store passwords with sha512-crypt can be accessed without plain passwords

**Comment by cketti** [comment]
To the best of my knowledge there is no encrypted IMAP authentication mechanism that's compatible with SHA512-CRYPT. See http://wiki.dovecot.org/Authentication/PasswordSchemes and http://wiki2.dovecot.org/Authentication/Mechanisms

Nowadays using a plain text authentication mechanism shouldn't be an issue because the connection to your mail server is most likely encrypted using TLS.
