### ISSUE TITLE
Notification stays open when email is read

### ISSUE THREAD

**Issue by joakim1** [k9mail/k-9#1570]
### Expected behavior
When you read/open a mail, the notification should be cleared.

### Actual behavior
The notification stays.

### Steps to reproduce
1. Receive mail.
2. Open mail via app (not via notification)
3. Profit

### Environment
K-9 Mail version: Latest

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange):
Outlook

**Comment by cketti** [comment]
This is most likely already fixed in the development version.

Note: Specifying "latest" as version information is not very helpful because it's changing all the time. And there's no way to tell whether what you believe to be the latest version is the same as what we developers consider to be the latest version. Next time please specify the exact version.
