### ISSUE TITLE
Next poll is skipped after a manual sync. Have to wait following poll.

### ISSUE THREAD

**Issue by botoid** [k9mail/k-9#1577]
### Expected behavior

Let say I have a 15 minutes poll interval. No push. This was with a Gmail account. 
K9 polls at 2.20
I manually sync at 2.27
I expect K9 to poll at 2.35
### Actual behavior

K9 polls at 2.20
I manually sync at 2.27
(I now make sure I have a new email in my gmail inbox -ie not K9 inbox -, by sending one from a PC)
K9 skips the polling at 2.35 (the K9 inbox is not reflecting this email) and poll at 2.50.

I don't know if the polling is effectively skipped, but for sure the folder which are supposed to be updated via polling are not updated until the next polling scheduled event.
### Steps to reproduce

1.as described above
### Environment

K-9 Mail version: 5.0.10

Android version:CM13 (6.0.1)

Account type (IMAP, POP3, WebDAV/Exchange):GMAIL IMAP POLL

**Comment by jktrigg** [comment]
That's better than my experience. What I'd like to see is manual poll resets the poll timer so the next poll is (current time + base poll time). What I've seen is "Next poll 3 minutes ago". I poll manually and it doesn't reset and then polls two minutes later for no good reason. What I'd like to see: manual poll truly resets timer. Last poll 2:20. Manual poll 2:36 (because it hasn't polled at 2:35 for whatever reason). Next poll: 2:51.

Skipping a poll is too much, but ignoring manual polls is too little. The via media of "Manual poll is last successful poll" should be a reasonable compromise.

**Comment by philipwhiuk** [comment]
The reason it might poll a minute late is because we don't ask for exact 'alarms' from Android because we take the view that it's not worth the battery trade-off. So Android can  and often does trigger the event slightly early or slightly late to match a device wake-up window.

This is probably the root cause of the 'Next poll x minutes ago' issue (which is obviously a bug - i think there's an issue already for it).

**Comment by cketti** [comment]
We changed the way we sync. This should no longer be an issue in `master`.
