### ISSUE TITLE
Isn't push notifications from Outlook.com supported?

### ISSUE THREAD

**Issue by joakim1** [k9mail/k-9#1590]
### Expected behavior
Should immediately notify me of new mail from outlook.com account.

### Actual behavior
Only checks for mail every x minute (folder polling interval)

### Environment
K-9 Mail version: 5.010

Android version: 6.0.1

Account type: Outlook.com (not sure what type)

**Comment by philipwhiuk** [comment]
outlook.com (as part of Microsoft's email services - so this includes Hotmail, Office 365 etc) supports POP3, IMAP and Exchange Active Sync. However, they don't support push on IMAP, only on Exchange Active Sync.

We only implement and suppprt POP3 and IMAP (including push on IMAP) - implementing Exchange Active Sync is an awful lot of work for fairly limited gain. The limited discussion towards it, such as it is tracked in #606

It would be nice if Microsoft supported the dominant method of push email rather than just their own protocol. But it's not the case.
