### ISSUE TITLE
New Feature : Mail service with attachment upload limit

### ISSUE THREAD

**Issue by younes778** [k9mail/k-9#1646]
### Expected behavior
Add a mail attachment limit if the server has this limit

### Actual behavior
K9 accept the attachment and upload it.
### Steps to reproduce
1. Add an attachment that excess the limit of size provided by the server

### Environment
K-9 Mail version: 5.111

Android version: All

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
The issue description is very vague. What are you trying to do?

K-9 Mail already supports the SMTP message size extension and won't attempt to send messages larger than what the SMTP server says it supports.

**Comment by younes778** [comment]
Yes. 
But in some mail clients like Gmail, if the server has a limit like for attachments it's 15Mo, when you excess this limit he told you that you can't attach it to the mail.

**Comment by philipwhiuk** [comment]
We don't get told the maximum attachment size until we open a connection to the SMTP server, which we don't do until we send a message.

We could cache the value once we know it and then warn that the message 'might exceed the maximum size'. But because it could be changed we wouldn't want to completely prevent exceeding it.
