### ISSUE TITLE
Server search slow/unresponsive

### ISSUE THREAD

**Issue by Natureshadow** [k9mail/k-9#1656]
Searching the server is very slow in my mailbox. Usually, when I search on the server, I get results, but trying to open one is too much and renders K-9 unresponsive.

The mailbox is 200000 messages large, but that should not bother K-9 because server search only lists matching messages. Even a single result triggers the issue.

Other IMAP clients do fine with searching this mailbox.

**Comment by cketti** [comment]
Can you please record a debug log while running a remote search. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by Natureshadow** [comment]
Well, I just updated to 5.113, and couldn't use K-9 for the last two hours because it is updating some database, draining my battery and filling up 6 GiB of storage.

**Comment by reox** [comment]
I had the same issue with a dovecot server. today I enabled FTS on the dovecot server using the lucene plugin (https://wiki.dovecot.org/Plugins/FTS/Lucene) and the problem is basically gone. The server based search is now almost instant and opening messages is also much much faster. Before I had the problem that the messages in the search would not load their content unless you would open and close them several times. Now the message is shown after about 1 to 2 seconds.

Maybe one should test if enabling FTS on dovecot is actually solving this issue - maybe it was just luck that the search is now faster...
I have about 12k of messages in this mailbox.
