### ISSUE TITLE
K9 is unable to utilize 2FA

### ISSUE THREAD

**Issue by zeroxxx2** [k9mail/k-9#1752]
### Expected behavior
Login to email service secured with 2FA prompts 2nd page to input verification code, app password should be used for last emergency resort.

### Actual behavior
K9 fails to recognize there's 2FA enabled and it throws error message instead

### Steps to reproduce
1. Enable 2FA on Gmail/Hotmail
2. Input user/pass on K9
3. Wrong password appears on screen

### Environment
K-9 Mail version: 5.010

Android version: 5/6/7

Account type (IMAP, POP3, WebDAV/Exchange): all types

**Comment by philipwhiuk** [comment]
Google requires us to implement XOAUTH2 which removes passwords entirely ( #655 ) - replaced by authenticated apps. I have no idea how Hotmail's system works. I will look into it - although it may be that this has to end up being fixed by #606  (Hotmail essentially is just a massive Microsoft Exchange platform).

As for account type - we'll only be fixing it on one type for each provider - which we'll set as the automatic set-up type - I don't think POP3 has the capability to use XOAUTH2 for example.

**Comment by philipwhiuk** [comment]
For Hotmail, capabilities:

CAPABILITY, IMAP4rev1, CHILDREN, ID, NAMESPACE, UIDPLUS, UNSELECT, AUTH=PLAIN, AUTH=XOAUTH2, SASL-IR

So it looks like Hotmail can potentially use XOAUTH2.

**Comment by zez3** [comment]
I think this is still valid and should be reopened. Modern auth like SAML or OIDC do not seem to work.
More concrete, Exchange Online is not working with MFA

**Comment by zez3** [comment]
Does this one help?
https://github.com/k9mail/k-9/issues/6046
Or where would be a better (forum?) place to file a feature request or discuss about medern auth?
