### ISSUE TITLE
try to lookup pgp-keys when *reading* new email

### ISSUE THREAD

**Issue by zoff99** [k9mail/k-9#1764]
### Expected behavior

get new email from "sender" which is signed with pgp-key
when pgp provider like openkeychains is active, k-9 should ask openkeyschain to lookup "sender" and check if there is a key stored online.
if yes -> download key and use it
if no -> just read email normally
### Actual behavior

get new email from "sender" which is signed with pgp-key
email is shown, but key is not download and no dialog is shown to let the user download the key
(also a setting to download keys in the background without user interaction should be available to make it easier for "normal" users to use pgp with ease)
### Steps to reproduce

see above
### Environment

K-9 Mail version: 5.114 (f-droid)

Android version: 6.x

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by Valodim** [comment]
The problem with this is that doing a key lookup from keyservers automatically upon receipt of an email is quite problematic for privacy, which is why this feature doesn't really qualify for default behavior :/

**Comment by zoff99** [comment]
make it optinal then. but without these features normal users won't use pgp.

**Comment by lbdroid** [comment]
I'm not really sure what the advantage of this would be... an automatically downloaded key wouldn't be trustworthy until you go through verification steps anyway, so it really isn't any extra burden to obtain the key at the actual time when you're validating it.

**Comment by zoff99** [comment]
yes it is an extra burden, and most users will not do it.
why not just open the same intent, as when receiving and encrypted email and that key is not yet available? (e.g. openkeychains screen which asks you to download the key)

why is a downloaded key not trustworthy?
why is a key more trustworthy if i manully download it from the keyserver as opposed to automatically?
what use are the keyservers then?

**Comment by lbdroid** [comment]
Your lack of understanding regarding how the key exchange works proves that this MUST be a manual step.

The downloaded key is not trustworthy because **you do not know who generated the key**.
In order to trust the key, you MUST perform manual verification by communicating with the person who the key CLAIMS to be owned by.

In this communication, one of you reads the key signature to the other. If the signatures match, you can TRUST the key. If the keys do NOT match, then somebody ELSE generated the key, and you MUST NOT trust it.

The use of keyservers is for CONVENIENCE. Just because a key is on the keyserver, does not mean that it was generated by the person who it claims to be its owner.

key servers are NOT a mandatory part of PGP key exchange for email. The public key can also be attached to an email message, and it is JUST as valid when exchanged in that manner, since the manual verification steps are identical and just as secure.

Understand this; it doesn't help for there to be more people USING pgp, if they are all using it incorrectly.

Here is an example of what can happen when you blindly trust the keys;
You receive a key from a key server for "John Doe". Unbeknownst to you, that key was generated by "Jack Smith" in the name of "John Doe". Jack Smith also happens to have obtained the password to John Doe's email account, AND knows Jack Smith's REAL public key, as well as the private key matching the public key that YOU have.

So you send an "encrypted" message to John Doe using the FAKE public key uploaded to a keyserver by Jack Smith.
Jack Smith has a bot permanently logged in to John Doe's email account, which receives that email message, downloads it from John Doe's email account, DELETES it, DECRYPTS it, RE-ENCRYPTs it using John Doe's REAL public key, and uploads it back to John Doe's inbox.

Guess what? That means that JACK SMITH has intercepted that email that you THINK was encrypted to John Doe. All because you blindly trusted some public key that you found on a key server.

**Comment by lbdroid** [comment]
Follow-up: Given the breach described above, it is MORE secure to use NO encryption AT ALL, because at least then you will be cognizant of the fact that it is NOT encrypted, which may impact the sensitivity of the data you send in that message. I.e., you will choose NOT to include super sensitive information that must not leak out.

**Comment by Valodim** [comment]
Yeah I'm pretty convinced people mostly don't use pgp because they get yelled at, sometimes even in caps, when they show an understanding of how keys/trust/whatever should be handled that is not in line with what someone else believes who feels all warm and fuzzy in their dogma.

**Comment by zoff99** [comment]
:-)

**Comment by konturger** [comment]
I strongly need to **disagree** with "poeple wont use PGP/GPG". 
I myself just installed K9 (the latest Beta 5.115) on all my android devices, just _because_ it supports PGP that well! :-) 
Intention is, in Germany (for instance) the Law legalized mass sourveillance, and even the concstitutional court is not allowed to controll or review the "selector targets". Reliable encryption is one of most powerful features nowerdays, and will be requested more in future. Using PGP/GPG and Signal etc is the only way to escape from this witch hunt.

Not Only journalism, science, but also economy, companies and political movements will depend on a way for a secure eMail transfer. It will not become THE "mainstream", but keeping this way of secure communication minimzied is really dangerous. Having a perfect working secure  open source program like K9 is a sign, and it is unbeatable at the play store, atm.

**Please keep up good encrytion support in K9! :-)**

**Comment by philipwhiuk** [comment]
Please let's keep discussion of an issue to the actual issue itself rather than general comments on technology usage. Please also do not raise new feature requests in existing issues - it means they will most likely be ignored.

I'm going to limit this to collaborators because it's clear what the desired behaviour is.

I'm also convinced that remote vs. local key lookup is not K-9's concern. It's up to the implementing app. The place to discuss that is OpenKeychain's GitHub. If they need/want us to implementing Intent handling for an option, they can do that by updating the API.

Hence, closing as not a K-9 bug.
