### ISSUE TITLE
Update cipher list to latest Mozilla recommended cipher suite

### ISSUE THREAD

**Issue by rugk** [k9mail/k-9#1775]
It would be nice if K9 mail could support this recent cipher for TLS (**Edit:** ChaCha20/Poly1305).
See https://timtaubert.de/blog/2016/04/a-fast-constant-time-aead-for-tls/ for an explanation of what this is.

The cipher is especially designed for mobile devices without AES hardware implementation and may therefore be especially good for smartphones.

**Comment by philipwhiuk** [comment]
We use the ciphers built in to the operating systems. At most we would be potentially be providing a version of BoringSSL / OpenSSL with the app but BoringSSL supports them (https://www.zeitgeist.se/2014/08/23/optimize-aes-and-chacha20-usage-with-boringssl/ )so it should be available in more recent versions of Android. 

If the OS supports them, we do. Right now we don't have any plans to provide our own copy of BoringSSL. But we could do potentially. We'd probably be releasing more often in that case (although I guess less often than some devices get updates).

We don't currently prefer Cha20 and Poly1305 - we prioritise a small list (which is the GCM ciphers, followed by CBC - https://github.com/k9mail/k-9/blob/78d3b011e658fcddd3c23d284b32a16e49f467e3/k9mail-library/src/main/java/com/fsck/k9/mail/ssl/DefaultTrustedSocketFactory.java) and then any others are just in whatever order the device is.

We could do this, but I'd rather see a consensus of security literature rather than one blog post.

Also unless it's actually deployed on email servers there's not much value in it.

**Comment by philipwhiuk** [comment]
I think we probably could justify at least updating the order to the latest Mozilla ciphers:

https://wiki.mozilla.org/Security/Server_Side_TLS

Also consider blacklisting stuff like aNULL and eNULL if they are there.

**Comment by rugk** [comment]
All right, this sounds good. I agree that shipping your own version of BoringSSL would be cumbersome and is not worth it.

**Comment by rugk** [comment]
In any case I think you should prioritise ChaCha20/Poly1305 if the device does not has AES hardware support (most likely the case).
