### ISSUE TITLE
Don't try to encrypt messages if key doesn't support encryption

### ISSUE THREAD

**Issue by ArchangeGabriel** [k9mail/k-9#1897]
### Expected behavior
I should be able to send emails without having a key selected if I want to use PGP support only to check sigs. It kinda works, but not sure if the behaviour is really the one expected.

### Actual behavior
Sending does not work, clicking on the icon returns « Aucune touche de signature n’est configurée ! Veuillez vérifier vos paramètres. », which translates approximately to “No signature key configured! Please check your setting” with a translation error (« touche » does stand for “keyboard key”, not “cryptographic key” which is a « clé »).

It does not depends on whether the “support signed only email” box is ticked or not, however it works if I move the slider in the composition mode to “Do not encrypt” instead of “Encrypt if possible”. Maybe that’s the desired behaviour, but I would have expected every position excepted “Encrypt” to work in this situation (in fact even this one, but I’m aware of your position on encrypt-only, so this last one is OK here since it implies signing too).

### Steps to reproduce
1. Go to Cryptographic settings, select OpenKeyChain as PGP app. Do not select any key.
2. Write an email.
3. Tap “Send”.

### Environment
K-9 Mail version:
5.200

Android version:
CM13.0/6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP here, but not sure that does matter

**Comment by cketti** [comment]
Thanks for the report.

It'd be great if you could help with the translation by fixing the error over at https://www.transifex.com/k-9/k9mail/

Only verifying signatures of received emails is not a use-case we want to encourage. That being said, it probably won't be too much work to set the composition default to "Do not encrypt" when no key is configured. However, then we probably also want to change the crypto provider setup flow to make sure users don't accidentally end up having no key selected.
@Valodim: What are your thoughts on this?

**Comment by ArchangeGabriel** [comment]
Not @Valodim, but those look like good ideas.

I understand that verifying signature only is not the setup you want to encourage, but at the moment I just can’t handle adding a subkey to my smartphone so it’s the only thing I can do, and even if I have yet to stumble on a wrongly signed email, I’ll prefer having a way to check in one sighting if emails I receive are legitimate ones or not rather than having to wait being on my computer for that. ;)

P.S.: Proposed a fix on Transifex.

**Comment by robertkosten** [comment]
I just ran into this and, as someone familiar with PGP I would never have assumed that "Do not encrypt" equates to "Do not sign". That is a really unexpected conflation of two very distinct functions.

**Comment by cketti** [comment]
@robertkosten: https://k9mail.github.io/2016/11/24/OpenPGP-Considerations-Part-I.html
Please post to the mailing list if you want to discuss this further. This issue is about being able to tell whether a message was properly signed without ever encrypting/signing outgoing messages.

**Comment by robertkosten** [comment]
@cketti After reading that link I don't think I will bother, it is clear that my perspective is completely incompatible with it :-(

**Comment by nickmdowson** [comment]
Hi, I'm not sure if this is exactly the same issue but since a recent update, it's not very clear how to turn off automatically signing emails (maybe that's just without a key selected - i've now selected keys so will try that) - and it won't let you send the email if one isn't...
would be good if the error message could make it clear how to deal with the issue, or signing emails could be made more opt-in (or is that in setting up APG a while back I have changed a setting? I'm not sure...)

**Comment by aryoda** [comment]
I am using K9 5.205 and OpenKeychain 4.2.4 with LineageOS 14.1:

I cannot encrypt any email because K9 shows: "No key configured for signing! Please check your settings"

But in my settings I have set "No key selected" in ("Cryptography > My Key").

The setting "OpenPGP app" is set to "OpenKeyChain"...

**It looks like K9 is always trying to sign emails that I want to send encrypted.**

Is this by design? Or can I disable signing of encrypted emails anywhere?

**Comment by Valodim** [comment]
Encrypt-only is not, and will not be supported. See [here](http://valodim.stratum0.net/k9/2017/01/23/OpenPGP-Considerations-Part-II.html) for our reasoning on this subject.

As for the issue at hand, I have a WIP branch I'm working on that changes this behavior.
