### ISSUE TITLE
No way to supress "mark all as read" confirmation dialog.

### ISSUE THREAD

**Issue by instance** [k9mail/k-9#1923]
### Expected behavior
Menu > settings > interaction > confirm actions:  should contain "mark all as read"

### Actual behavior
Irritating dialog shows up every time "mark all as read" is selected

### Steps to reproduce
1. Select "Mark all as read"
2. Get mandatory dialog.
3. Search for new mail app, note many similar complaints on play store
4. Sad face.

### Environment
K-9 Mail version: 5.201

Android version: any

Account type (IMAP, POP3, WebDAV/Exchange): any

**Comment by lynnwr** [comment]
I am having the same problem occur after the recent update to ver. 5.201. I have Andoid ver. 6.0.1 running on Samsung Galaxy S7. No new field appears in Settings that addresses this notification preference to turn on/off.

**Comment by lynnwr** [comment]
This new warning dialog Cancel/OK seems to be more of a BUG with the new 5.201 update since it was either previously managed via settings or was not a feature in the previous version. There is no new settings field to turn this new warning on/off. I am running Android ver. 6.0.1 on Samsung S7. Was this issue coded Enhancement to add the settings field in v5.202?

**Comment by Valodim** [comment]
This is a simple feature to implement. Anyone? :)
