### ISSUE TITLE
Loading messages now extremely slow

### ISSUE THREAD

**Issue by roccol5** [k9mail/k-9#1942]
### Expected behavior
When reading messages by scrolling, deleting, etc. next message should load at a reasonable speed.

### Actual behavior
Message loading has become extremely slow with 5.201 release.

### Steps to reproduce
1. Open Inbox
2. Read a message
3. Scroll to next message
4. Wait

### Environment
K-9 Mail version:
5.201
Android version:
6.0
Account type (IMAP, POP3, WebDAV/Exchange):
POP3 and IMAP

**Comment by cketti** [comment]
Probably same as #747.

**Comment by Valodim** [comment]
not so sure, since this is not something that changed in 5.200. is it very slow during scrolling, too?

**Comment by roccol5** [comment]
Sorry, perhaps I shouldn't have use the word "scrolling".  What I meant is after opening a message (which opens slowly)  you hit the next or previous arrow and the next or previous messages also load slowly.

**Comment by PanderMusubi** [comment]
Same here. You also have the build from F-Droid?

See also https://github.com/k9mail/k-9/issues/2001

**Comment by jonas-lundqvist** [comment]
I also experience this issue and I think it started when going from 5.0x to 5.2x.
Just a shot in the dark: can this be related to what @Valodim stated in #1903 

"[...] Mails are now rendered from their structure and only then displayed, rather than just showing a saved html blob. This allows us to do various things that weren't possible earlier (e.g. pgp/mime), but it's also not as fast."

**Comment by svenberkvens** [comment]
I had the same problem: K-9 was totally unresponsive. I've since fixed it (and it is very fast again) by going to the Accounts list, pressing long on an account to get the context menu and then choosing "Recreate data (Last resort!)". Works like a charm afterwards. It seems that the database upgrade that the K-9 release does moves all messages' data to so many places on the flash storage that it becomes incredible slow.

**Comment by philipwhiuk** [comment]
Lack of indexes probably worsens the database performance. I suspect it'll be worth revisiting this after 5.204 which will contain #2158
