### ISSUE TITLE
COMPOSE UI with BCC Missing 

### ISSUE THREAD

**Issue by dabear2** [k9mail/k-9#1964]
### Expected behavior
In previous android version 5.010; Go to the COMPOSE screen.  at the top there are several ICONs (K-9 (screen name)  --- Compose --- two heads (show BCC/CC address fields) --- PaperClip+  --- Triangle (send)  --- and 3 dots (menu).
In the new version 5.201 the icon with **two heads (show BCC/CC address fields)** is missing.
I expect this two heads (show BCC/CC address fields) to be in the top header menu.

### Actual behavior
In the new version 5.201 the icon with **two heads (show BCC/CC address fields)** is missing.

### Steps to reproduce
1.   tap on compose a new email.
2.   Observe the absence of the icon with **two heads (show BCC/CC address fields)** is missing.
3.

### Environment
K-9 Mail version:  5.201 
Android version:  6.0

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

**Comment by cketti** [comment]
Press the button/symbol at the right end of the "To" line to expand the CC and BCC recipient fields.

**Comment by dabear2** [comment]
Thank you.  I could not see that pull down triangle at the end of the TO: line.  It's very faint but I do see it now.

**Comment by cketti** [comment]
That's a bug. See #1893. It will be fixed in the next bugfix release.

**Comment by dabear2** [comment]
Thank you for fixing this.  In the dark theme, it looks more obvious now.  
BTW - why the change from the double heads icon to do CC/BCC vs. this down arrow?  Seems like a six in one half dozen in the other thing.

**Comment by Valodim** [comment]
If you're wondering about compose dialog design choices, those are mostly "what gmail does", since that's a pretty good baseline.

As for the down arrow in particular, it just looks a little more material than before and is a little less pronounced, optimizing for the majority of users who just use `To` in their daily mails. People who know what they are looking for are likely still able to find it though - unless we mess up the icon in the dark theme of course :)
