### ISSUE TITLE
ATTACHMENTS IN THE kp MAIL ANDROID VERSION 5.201 AND 5.202

### ISSUE THREAD

**Issue by solideo1971** [k9mail/k-9#1977]
### Expected behavior
Tell us what should happen

Usually when in an email conversation there is an attachment the button "show attachment" appear on the right side on top of the mail.

### Actual behavior
Tell us what happens instead

the attachment is showed at the foot of all conversation

### Steps to reproduce

1.take an email conversation write a reply with attachment
2. send the mail 
3.when the mail is received the attachment is showed at the foot of all conversation

### Environment
K-9 Mail version:
5.201 -5.202
Android version:

6.0 (HUAWEI P8) - 6.0.1 (SAMSUNG S5)

Account type (IMAP, POP3, WebDAV/Exchange):

imap / pop3

**Comment by cketti** [comment]
Works as intended.

**Comment by solideo1971** [comment]
Dear sir good day, i am sorry to tell you that isn't works as intended, because in this two new versions the attachments is not showed on top of the mail.

**Comment by solideo1971** [comment]
if you have used the previous version before the mentioned two, may understand what i mean..

**Comment by ArchangeGabriel** [comment]
Yes, they understand it. They moved it on purpose, although we all agree this is not optimal. But it’s not going back at the top of email, that wasn’t good either. There is a need for a better UI regarding attachment, if you have ideas or opinion don’t hesitate to share them. ;)

**Comment by solideo1971** [comment]
a possibility should be a insert a new line (after from/bcc/cc/subject), where is possible to find the attachements. Or to re insert the button....anyway if no possible to modify or to improve the UI...we will see

**Comment by solideo1971** [comment]
thanks, i think this should be a good compromise, Hoping as soon they will introduce it, or any further developments, in order to fix this issue, or to minimise the impact of this on the lon email conversation....

**Comment by Valodim** [comment]
Maybe a "scroll to bottom" button could help?

**Comment by solideo1971** [comment]
I think the best way is the solution suggested from ArchangeGabriel, with a small button with a "clip" that directly show the attachements...

**Comment by ArchangeGabriel** [comment]
Or the Material Redesign, with @moctodot proposed solution. ;)

**Comment by K-9-Freak** [comment]
Hello there...
I'm new here and use the K-9 together with colleges. We are in terrible crises after the new version of the app, with the attachments at the bottom of the email. It is not workable at all.
It seems to be more like Apple structure???
Please redesign the buttons at the top again. A simple way you could do it, is that it could be a setup choice in the settings menu. You have already so many ways for setting up the K-9 for your specific needs, so why not the possibility to choose to have the attachement in the top or bottom of the email.
Look forward for your comments.
Patrick

**Comment by philipwhiuk** [comment]
We are not adding more settings. K-9 has far too many already - the ability to test new useful features is already very difficult because of the multitude of combinations that are possible.

Especially when such as setting ought to be short lived given the Material rework as already mentioned which will undoubtedly change the UX again.

**Comment by K-9-Freak** [comment]
Hi philipwhiuk
Thanks for your comments.
I'm still wondering why you move the attachement link to the bottom and still have the "show graphics" at the top.
So there is no space gain at the top anyway.... 
Please see attached screenshot.
![screenshot_20170109-222958](https://cloud.githubusercontent.com/assets/25007554/21797401/17792940-d70f-11e6-802e-a26f05dabfb2.png)
Best regards Patrick

**Comment by bah0071** [comment]
if k-9 developers think that the "show attachment: button is not good then why did they keep "show pictures...takes the same room
the "show attachments" button should be an option in settings for people that want it, instead of unilaterally removing it...

another option is to have the attachments right under the first email (the email that the attachments came in on)  as having to scroll down through multiple emails is really annoying when you have an email string of 10 emails in the same email...

I went to bluemail for a week andloved it but went back to k-9 because they don't synchronize the sent folder in imap which is stupid...

**Comment by christianhaessler** [comment]
Same Problem on Version 5.600. I think it would be ok to have a "jump to attachement" option in the "burger menu" as well. So you don't use to much space at the top.
