### ISSUE TITLE
Moto Display lock screen custom indicator remains blank when K-9 notification occurs

### ISSUE THREAD

**Issue by k9foo** [k9mail/k-9#2011]
### Expected behavior
A mail icon (an envelope inside of a circle) should appear on the Moto Display lock screen when new mail arrives. 

### Actual behavior
When new mail arrives, the Moto Display lock screen shows an empty circle instead of a mail envelope inside of a circle.  

![img_20170107_174508](https://cloud.githubusercontent.com/assets/24979475/21746265/4e95319c-d504-11e6-9bd2-8b87fbc49e4e.jpg)

All Moto apps (including Moto Display) are up-to-date.

This issue does not exist for other apps that notify in Moto Display (i.e., Calendar, SMS, Voice Mail, Missed Call, etc. all display their respective icons on the Moto Display lock screen).

This issue started within the last two K-9 Mail updates (5.201 I believe).

### Steps to reproduce
1. Lock phone screen (with Moto Display enabled)
2. Send an e-mail message to a K-9 Mail configured account from another device
3. When the new mail arrives on the problem device, notice the lock screen notification icon is just an empty circle.

### Environment
K-9 Mail version:
5.202

Android version:
5.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

Phone version:
Republic Wireless Moto X 1st Gen
All Moto apps, including Moto Display, are up-to-date.

**Comment by cketti** [comment]
Again, we don't really care about this proprietary OS feature. If anyone provides a fix we'll happily include it. But we won't invest any of our time to investigate this.

**Comment by k9foo** [comment]
Unfortuntely it makes your app that much less useful for me since about 75% of the active display notifications on my phone are for new e-mail.

It's obvious this is due to a K-9 Mail change since it's the only change introduced and is verified on two phones. Really, how hard could it be to track it down? Has to be related to icons or something.

I regret that I will have to start sampling other mail apps now. And I will also have to consider rating K-9 Mail in the app store in a manner commensurate with its developers' "we don't really care" attitude...

**Comment by cketti** [comment]
Feel free to find out yourself how hard it is to track this down. For added fun try without owning an affected device yourself.

Please also note that we're working on the app in our spare time and give it away for free. There's nothing wrong with asking nicely that we spend time on something that isn't working for you. But you have to live with the fact that something you care about is not important to us.

**Comment by Valodim** [comment]
The notifications changed structurally in the latest release to be compatible with newer Android design patterns, which are required in particular for smart watch display.

Tracking down how this affects a proprietary os feature would first require even obtaining a device with that os on it.

I understand this is frustrating for you, and I wish I could help out, but please understand that development is (besides pgp features) fuelled exclusively by a small number of people's motivation to work on this in their own free time.

We would love if someone who owns a device and can do it Android development tracked this down and contributed a fix. In this spirit, I'll reopen the issue with a help wanted tag.

**Comment by k9foo** [comment]
@Valodim Completely reasonable and acceptable. Thank you!

@cketti No so much

**Comment by philipwhiuk** [comment]
http://stackoverflow.com/questions/36372449/showing-notifications-on-motorola-active-display

I think this is what we should look at. Not going to be able to test it but we could probably be fairly sure it won't break anything.

**Comment by ahoh77** [comment]
I guess it depends on issue #1981 - where already exists a pending pull request. I don't know the Moto but when the widget is not shown inside the circle maybe it is caused by a wrong widget size (?). Sounds plausible to me...

**Comment by philipwhiuk** [comment]
Not really. Widgets and notifications are totally separate.

**Comment by brasseagle** [comment]
My problem is similar to k9foo, except that I don't get any notification on the Moto Display screen (rather then empty circle).  While looking for advice, came across this:
"Moto display doesn't show *permanent* notifications"  - see web page
https://forums.lenovo.com/t5/MOTO-X-2nd-Gen/Some-notifications-not-appearing-on-Moto-Display/td-p/3051601

Don't know if this makes sense, but hope it may help somebody that understands these things.  
It would be really useful to me, k9foo, and probably lots of other Moto users if a solution could be found!

**Comment by gothamrob** [comment]
I am having the same issue as k9foo after the Android system update. If anybody can figure it out, it would make my life better. Thanks for all your work! I do love the app.

**Comment by funnydog** [comment]
Hi,

Since I had the same problem with my Moto X 2013 I checked out the K-9 Mail git repository to see if I could pinpoint the issue.

I found that adding .setGroupSummary(true) to controller.createNotificationBuilder() in BaseNotifications.java didn't work at all.

However in the same SO [1] page it's clearly specified that the icon has to be a raster/bitmap icon, not a vector icon, while right now "notification_icon_new_mail" is a vector file.

So I converted the xml vector file in SVG[2] and from SVG to png. Then I added a temporary notification_icon_new_mail_png to the resources with Android Studio, changed BaseNotification.getNewMailNotification() to load the new resource and built the APK.

Result: the mail icon is back in the Active Display!

I can submit a pull request if needed. However I wonder if it will be accepted, since the conversion from png to vector icons seems to be deliberate.

Android Studio generates 12 png files (4 resolutions, 3 APIs) and their size is IMHO acceptable: 676 bytes for the xxhdpi resolution.

I'm waiting for comments.

[1] http://stackoverflow.com/questions/36372449/showing-notifications-on-motorola-active-display
[2] SVG for the vector file
```
<svg width="72" height="72" xmlns="http://www.w3.org/2000/svg">
  <path d="M1,8.655v11.508h22V8.655l-11,5.47L1,8.655z" fill="#ffffff" transform="scale(3,3)"/>
  <path d="M1,3.837v3.062l11,5.467l11-5.467V3.837H1z" fill="#ffffff" transform="scale(3,3)"/>
</svg>
```

**Comment by cketti** [comment]
That seems like a bug you should report to the device manufacturer. The Android platform supports vector drawables since API 21 (Android 5.0). I'm sure other apps that also switched to vector drawables for their notifications are affected by this as well.

If someone finds a reliable way to identify affected devices we can use a bitmap icon for notifications on those devices. But I don't want to use bitmap icons on all devices just to work around a bug on a few devices.

**Comment by pshem** [comment]
@funnydog , write an email linking to this thread and emphasizing that the problem affects all applications using .SVG icons. Include a screenshot if you can take one on the lock screen. <a href='https://motorola-global-en-uk.custhelp.com/app/prod_ask/'>Their contact form is</a> and they use some pretty annoying anti-spam(to the point of _"do not bother us"_) measures.
<a href='https://motorola-global-en-uk.custhelp.com/app/mcp/service?g_id=5141&session=FSWuswgn'> Here </a> is a chat if that's what you prefer, but expect chat help to be 1st line bots without a clue

I would expect Motorola devs to be aware of the issue, but a bug report can't hurt if you have the time

**Comment by funnydog** [comment]
Fair enough.

I will certainly report the bug but I expect that the chances that Motorola will fix it are near to 0. The phone is old, and I doubt I will receive fixes anymore.

I can also live with the empty notifications from k9 mail, so I don't bother if you don't fix it.

I sympathize with the developers since I'm a developer too and I care enough for my code and try to avoid kludges. Unfortunately I also know that sometimes a pragmatic approach is necessary.

Since I can code and since I own a Moto X, I thought I could finally track the source of the problem and I did it. Now the fix is known. That's all there is about it.

Bye

**Comment by cketti** [comment]
@funnydog: Get the values for ` android.os.Build.MODEL` and `android.os.Build.MANUFACTURER` on your device and we can add code to use a bitmap icon just for Moto X devices.

**Comment by funnydog** [comment]
@cketti: Is the output of 

```
adb -d shell getprop | grep product
```
enough?

```
[ro.build.product]: [ghost]
[ro.mot.build.product.increment]: [201]
[ro.product.board]: [MSM8960]
[ro.product.brand]: [motorola]
[ro.product.cpu.abi2]: [armeabi]
[ro.product.cpu.abi]: [armeabi-v7a]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: []
[ro.product.cpu.abilist]: [armeabi-v7a,armeabi]
[ro.product.device]: [ghost]
[ro.product.display]: [Moto X]
[ro.product.locale.language]: [en]
[ro.product.locale.region]: [GB]
[ro.product.manufacturer]: [motorola]
[ro.product.model]: [XT1052]
[ro.product.name]: [ghost_retde]
```

**Comment by daniele-athome** [comment]
I'd like to create a patch for this (I own an XT1052 :-). I don't think a resource specificier can be used for device and model, so I guess I'll have to hardcode them, right?
