### ISSUE TITLE
use .asc file extension for PGP/MIME

### ISSUE THREAD

**Issue by DreamFlasher** [k9mail/k-9#2031]
### Expected behavior
When I receive a PGP/MIME encrypted email from K9 at a client which doesn't support PGP/MIME (mailvelope, inherently), I would like to see files with the attachment .asc because then I can click on them to get a preview, which then can be decrypted my mailvelope. When sending with Thunderbird the encrypted message appears as an attachment with extension .asc.

### Actual behavior
The PGP/MIME attachments don't have a file extension. 

### Environment
K-9 Mail version: 5.202

**Comment by philipwhiuk** [comment]
@Valodim @cketti What do you think of:

```
Content-Disposition: inline; filename=<<EmailSubject>>.asc; 
      creation-date="Wed, 12 Feb 1997 16:29:51 -0500";
Content-Description: Encrypted email
```

We don't want to use `attachment` because per the spec we want clients that can to display it as normal. But hopefully giving it a filename with extension of `.asc` solves the other case?

**Comment by DreamFlasher** [comment]
@philipwhiuk <<EmailSubject>> contains potentially difficult characters. I'd just do "encrypted_email.asc" or sth like that, just had the case with someone who didn't use pgp for years, didn't have their setup anymore and didn't realize that I sent an encrypted message, could help with signaling.

**Comment by philipwhiuk** [comment]
Yeah, I was hedging on that bit. I'm really asking whether we think Content-Disposition: inline + filename is okay or if it's going to cause more problems than it solves.

**Comment by cketti** [comment]
I don't mind the change. But I'd like someone to test this against common PGP/MIME implementations to see if it causes any problems.

**Comment by J-J-Chiarella** [comment]
Is the suggestion here to sign and encrypt using MIME and then also save a signed&encrypted copy of the message in a .asc file? Would it include the attachments, as well? This basically doubles the size of any message. On the topic, I'd like to see Mailvelope do this instead of its current model of expecting the user to change file attachments names to something less revealing (file-May_24.pdf instead of strange_accounting_files_needing_investigation-May.pdf) and then individually encrypting attachments. There's also the onus of the user to put a hash digest of the encrypted file in the message body to prove no attachments were stripped in transit.

However, for anyone with Enigmail or K-9 Mail, we would get messages that are double in size. Not the end of the world, but something to consider. If I have a 10 MB send limit per message and I have 6 MB e-mail, including a copy of the whole thing (in pure text, base64 encoding of attachments, all itself encrypted with PGP and armored in base64) would make my e-mail above the limit. Users may be confused as to why their 6MB attachments of a couple photos now are unable to be sent.

**Comment by DreamFlasher** [comment]
No, this is not the suggestion. The suggestion is to use .asc as a file extension instead of none.
