### ISSUE TITLE
Permanent notification icon

### ISSUE THREAD

**Issue by catfluoride** [k9mail/k-9#2040]
Hi,

Would it be possible to implement a permanent icon confirming that background sync is actually active?
It would be just a visual remainder, but I think it could be useful.

Thanks!

**Comment by rugk** [comment]
> It would be just a visual remainder, but I think it could be useful.

Not only this, it could also prevent Android from killing that app in low-memory situations.

**Comment by harjot-oberai** [comment]
@philipwhiuk : I would like to work on this. Is there some guidelines that I should follow ?
 I was thinking of a simple indefinite notification (with a progress bar, maybe) that ends as soon as refreshing is done.

**Comment by harjot-oberai** [comment]
I was looking at the code, there is already a notification that should be shown while fetching mails if `mNotifySync` is set to true (Controlled by `Sync Notifications` under `Account Settings > Notifications` ). But when using pull to refresh, no notification is shown.
Is the `Sync Notifications` preference used for some other task, or do I have messed up understanding of the code 😅 ?

**Comment by philipwhiuk** [comment]
Hmm yeah that sounds like a bug which should be fixed. I guess it's just some faulty logic.

The original issue for this ticket basically calls for a permanent notification while (for example) a push connection is open - a different idea.

**Comment by catfluoride** [comment]
Hi,

I'm the OP. Effectively, my proposal was that a permanent notification icon would appear whenever push is active. Unfortunately I don't have coding skills, but I'd gladly perform beta-testing, if needed.

**Comment by harjot-oberai** [comment]
Please clarify "push connection". Are you talking about folder synchronization ?

**Comment by harjot-oberai** [comment]
Nevermind, got it 👍 . So the notification should be shown whenever the `pusher` scheduled by the `MailService` is running, right ? @philipwhiuk

**Comment by cketti** [comment]
I don't like this. Mail sync is something that should happen in the background without the user being aware. So I'd like to get rid of the existing mail sync notification rather than adding another one.
I can understand that people want to make sure Push is still working, because it's a bit unreliable right now. But that's the problem that needs fixing. An ongoing notification when Push is active is not the solution.

At some point we might have to use a foreground service when using Push. That means showing an ongoing notification. However, if we can avoid that, we should.
