### ISSUE TITLE
Can't encrypt without signing

### ISSUE THREAD

**Issue by hadmut** [k9mail/k-9#2096]
### Expected behavior
I'd like to encrypt emails to protect them against eavesdropper. I have the pgp key in a yubikey neo, not permanently in the mobile phone.

Choice of encryption and signature must be independent. 

### Actual behavior
Can't send. k-9 demands to sign the message and thus to have a key present, even if I don't have the yubikey with me or don't want to enter the pin because of people around watching. 

### Steps to reproduce
1. Send an email and encrypt it.
2.
3.

### Environment
K-9 Mail version:

Android version: 4.4

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by Valodim** [comment]
This is by design and won't change. Encrypted but unsigned mails are a misfeature that should never have been made available to users. I'm planning to write a blog post explaining this decision.

**Comment by sedrubal** [comment]
Did you already write a blog post? Because I absolutely don't understand this decision: E.g. a whistle blower wants to be anonymous (he mustn't sign its mail) but wants to encrypt the content when delivering it to a press.

**Comment by philipwhiuk** [comment]
Signing doesn't link a person to am email it links an email address to an email.

**Comment by sedrubal** [comment]
OK. But I strongly disagree: when generating a key you can write any address into the key. IMHO a proper key is linked to a person (this is what you verify before signing another's key). And I think you sign your mails to give a proof that this mail was sent by you and not by a highjacker which has stolen your login credentials of you mail account.

**Comment by hadmut** [comment]
At the moment I do not see that this decision could make sense.

But I'm waiting for this blog post before I will respond.

**Comment by ArchangeGabriel** [comment]
I agree that a key as no value without trust in it, and thus in the person using this key.

whistleblower should probably not be using mails in the first place, and probably not an Android smartphone either. For other eventual use cases, K-9 devs seem to be suggesting to create a dummy key maybe named “Dummy key for K-9 mail usage, don’t trust me or encrypt for it”, however I’m not sure people would check the key name…

Anyway, I think we should wait for @Valodim to write his blog post, it would be more clear then and maybe a real discussion on this could then start. Probably to be held on the [messaging ML](https://moderncrypto.org/mailman/listinfo/messaging) btw?

**Comment by aryoda** [comment]
You can find @Valodim 's blog post here: http://valodim.stratum0.net/k9/2017/01/23/OpenPGP-Considerations-Part-II.html

**Comment by sedrubal** [comment]
Now I can understand this decision a bit better, but this are 2 (weak) contra arguments:

- You don't want to allow encrypted-only mails because there is no proof that the sender did send the mail. But then you have to disallow unsigned mails at all. If someone thinks encrypted-only mails proof the sender, this is a problem with the user and not with the mail... A red warning is the best thing you can do. (But maybe it is better not to make it fullscreen but rather add a red banner to decrease the warning fatigue effect?)
- Yes, you can simply add a (sub)key to your device, but what should I write as description into it? "Don't trust this key, it is used on my smartphone?" And users will receive this key and see, oh the mail is signed, I'll trust it. People will use TOFU because it is the most convenient way using PGP. I'm also not sure if it is a good idea at all to share a key you don't even trust yourself, because there is no way to be sure that a revoked key reaches the users...

I understand your decision but I think most people don't want a 100% secure messaging channel. They just want to be safe against surveillance and save personal information. And imho it is too hard to make PGP user friendly. PGP imho can't be user friendly, but it can encrypt mails. So please let do PGP the job it can do - encrypting mails 😉

**Comment by philipwhiuk** [comment]
> You don't want to allow encrypted-only mails because there is no proof that the sender did send the mail. But then you have to disallow unsigned mails at all.

I don't agree.

The problem here is that there are three main properties to convey to the user that something is secure - confidentiality, integrity and availability. Security requires all three. 

In PGP confidentiality is encryption, integrity is signing, availability is provided by the network and not really handled at all in email.

If you don't provide signing, then you aren't providing security. So in order to convey the lack of security you have to show it somehow.

There is a difference between in-secure with no guarantee of security and a half-way house. 

Browsers will refuse (initially) to connect to bad SSL implementations (e.g. untrusted certificate (a good parralel for unsigned)). They are, in several ways, considered worse than insecure pages. Because the website has actively chosen to mislead the user by implementing partial security, the browser treats it as bad.

In the same way, I would be more skeptical of an encrypted-only email than I would unencrypted and unsigned e-mail. You're doing something out of the ordinary.

>  If someone thinks encrypted-only mails proof the sender, this is a problem with the user and not with the mail... 

If the user gets the wrong impression the application is wrong, not the user. Building user-friendly secure applications starts with that. This is not a defensible position for UX design.

> A red warning is the best thing you can do. (But maybe it is better not to make it fullscreen but rather add a red banner to decrease the warning fatigue effect?)

PGP deployment is really rare. Broken PGP is even rarer. 

> PGP imho can't be user friendly,

It can't be if you insist on breaking the security model.

>  but it can encrypt mails. So please let do PGP the job it can do - encrypting mails

PGP can sign them too. This is a terrible closing argument.

**Comment by Valodim** [comment]
From a cryptographic perspective, a messaging protocol that has confidentiality but not authentication simply doesn't offer "secure" communication, at least from the recipient's point of view. It's wrong to give recipients of such messages any sense of enhanced security about this message, but because we have to ask for their password to display the mail in the first place, this leads to an impossible mental model.

If having a password on a key wasn't accepted "best practice" for openpgp (this too is a thing I disagree with in specific cases - blog post will follow), I would probably just decrypt encrypted-only messages and display them like regular plaintext mail, because that's the actual security estimation that can be assigned to such a message.

The single biggest insight that Signal et al. have brought us in recent years, is that TOFU is a *good enough* authentication model for almost all users, and just a small number of users who do verification drive the cost in terms risk of detection to a high enough level. Trying to learn from that brings up the issue that it's impossible to assign any kind of trust (TOFU or otherwise) to encrypted-only messages. There is no remedy for that, and an ecosystem that includes the idea "sometimes, messages are encrypted but not secure" simply isn't viable at any scale.

It's perfectly possible to make PGP (a lot more) user friendly, and the way to do that is simple: Get rid of all the ways users can shoot themselves in the foot, stop making tools that require cryptographic knowledge to use, stop asking users for decisions that they aren't equipped to make, stop pressuring users towards absurdly high standards of security.

Unfortunately, this particular issue can't be fixed on the recipient side.

I spent a lot of time thinking about this and discussing this, which is why I'm going to drop the subject here. That said, I know this is an ongoing thing, and I really need to write down some kind of vision statement for this. I appreciate everyone's input so far! :)

**Comment by sedrubal** [comment]
Thanks for all your thoughts. I can understand your opinion and I'm more or less OK with it.

But what I tried to say is that it is impossible to use pgp as simple "transport end-to-end encryption" in k9 (when you don't have a key on your smart phone (because of reasons)). You might want to have some encryption because you don't know if all SMTP servers on the way to the recipient use TLS. But you might don't want to handle keys and struggle with the rest of pgp.

But you don't want to allow this feature because it has too much disadvantages for inexperienced users and that's OK.
