### ISSUE TITLE
Syncing Disabled

### ISSUE THREAD

**Issue by nebutron** [k9mail/k-9#2135]
At random times, to which I can't figure out when, K-9 Mail will show Syncing Disabled under my Inbox and notifications will not show up.

### Expected behavior
Notifications should arrive when mail arrives. Inbox should not be showing "syncing disabled"

### Actual behavior
Under the inbox you will see 'syncing disabled" and during this time no notifications will show up. A pull to refresh in the window will grab new email but it goes back to syncing disabled. All regular settings to allow syncing and intervals are set up correctly where this should be working.

### Steps to reproduce
1. Possibly not using the app for hours. Do not know the cause.
2. Notice on another device (desktop client) that new mail arrived.
3. Check K-9 Mail (the inbox) and see syncing is disabled

### Environment
K-9 Mail version: 5.203
Android version: 7.0 (Nexus 6)
Account type: IMAP

**Comment by philipwhiuk** [comment]
This is caused by Doze #857

**Comment by ralphsims** [comment]
K-9 Mail, Global settings -> Network -> Background Sync == Always

Seems to work for now.

**Comment by dstimson** [comment]
This problem begin for me after update to Nougat.

The following setting (which I already had) does not work for me.  I still get "Syncing disabled".

Does not work for me: K-9 Mail, Global settings -> Network -> Background Sync == Always

**Comment by wetnun** [comment]
This happens for me also.

Android 7.0
Galaxy S7
K9 5.206

The application is not set to be battery limited (no doze), and the background sync is set to always.  I'm using a IMAP with TLS.  I have to setup sync and polling to I can figure out if I have email.  It's only been happening since the update to Android 7.

If I go into account settings, fetching mail, incoming server and just hit next it will go back to doing a full sync,  But then fail sometime during the next day and not recover unless I do that again.

**Comment by philipwhiuk** [comment]
We know about this issue and additional reports aren't that useful.
