### ISSUE TITLE
Remove language selection feature from K-9

### ISSUE THREAD

**Issue by philipwhiuk** [k9mail/k-9#2262]
Per comments on #2246 we plan to remove the language selection feature as it was originally designed to solve a problem in Android (lack of support for certain languages).

Right now it's an underused and fairly obscure feature which just makes the app more complex.

**Comment by mis2417** [comment]
I realize this is not a vote, but please reconsider removing features from project. Apart from that, it's not unused - I'm sure I'm not the only one using it, and it's actually first setting on the list (so not obscure).

**Comment by philipwhiuk** [comment]
I find it difficult to think of a use case that isn't "Work around this bad translation"

Ignore that one, why would you want your email client in a different language to the rest of your device (and all other apps).

**Comment by Valodim** [comment]
The other question is, is this a lot of complexity? Does this cause us headaches anywhere, or require maintenance?

**Comment by mis2417** [comment]
well actually I can't tell why my phone isn't set to english globally, but I can't stand my native language in apps. from bad translations (not the case in k9mail), to 'too long texts', to just 'simply sounds stupid'. 
anyway, this is kind of like kde-gnome debate, I always thought iphone was more remove-options-we-know-better, while android was the tinker-away approach.

**Comment by cketti** [comment]
There is a maintenance cost. When adding a new language it has to be added to the `supported_languages` string array (which I'm sure I forgot the last time I added a new translation) so users can select it in K-9 Mail's settings.

To properly override the system language we'd have to ignore all locale change events. I'm fairly certain we don't do this a) everywhere and b) properly (we don't want to ignore those events when we don't override the system language).
Also, the notification thing has probably been broken since forever. The fact that nobody reported this as a bug until now is a strong indication that language selection is not a heavily used feature.

**Comment by mis2417** [comment]
I have to admit, I personally never noticed notification bug (although, come to think of it, it affects me too), so.. well.. I see your point. Shame, but maybe this will finally make me change the language globally.

**Comment by verdulo** [comment]
@cketti Ho ne, kial vi volas forigi tiun ĉi eblon? Mi antaŭnelonge finigis traduki K-9 al Internacia Lingvo Esperanto kaj mi eĉ ne povas ĝin uzi! Bonvolu rekonsideri vian decidon kaj realdoni tiun ĉi eblon al la programo!

**Comment by philipwhiuk** [comment]
@verdulo This won't stop K-9 from being translated by your device. It'll mean K-9 is (like every single other application on your device) the same language as every other application.

**Comment by verdulo** [comment]
2-signaj kodoj estas preferataj, la problemo estas, ke Esperanto NE estas elektebla en Android, do tial mi petas programistoj pri aldoni eblon por ŝanĝi aplikaĵan lingvon...

**Comment by Valodim** [comment]
Message deleted. Please speak english if you want to communicate on our issue tracker, we don't want to use google translate to find out what you are talking about.

**Comment by verdulo** [comment]
Why should I speak English, instead of Esperanto? Esperanto is easy international language, unlike English which is almost impossible to learn and not-international.

The problem is, that Esperanto is not selectable on Android, that is why I ask developers to add option to change interface language.

**Comment by carbsk** [comment]
Hi, 

Well, for me, the reason to select a different language to K-9 is because in spanish strings translations are to long and when I got a new e-mail "DELETE" button is not shown because "MARK AS READ" is to long in spanish, before the update to select a language in K-9 I had to put my device in english to avoid that, but that means that all speak apps do in english, like google maps finding places, streats with spanish name making a english pronunciation, gps and all, it sounds funny but it's a problem, and when select language came I inmediatly put my device in spanish and set english to K-9, I thought "this is great", but surprice!, some times notifications are in english and other times in device language (spanish for me). 

I think a situations like this are same for others who do the same for same issue, what I suggest, if you want to remove language selection (at least for me), you can remove all text from buttons, nowadays every body knows whats each button for, trash container to delete, arrow to reply, double arrow to reply to all, open envelop to mark as read, folder to archive or move to folder, etc, so, if you remove text at least from notifications you will have an extra space to set other buttons there and make more usefull this app.

I've been saying this in other posts, maybe is to difficult for you to do it or you just don't want it to do, how ever is your call...

Regards.

**Comment by AEaut** [comment]
As a "new" user, I, from time to time, switch to English just to compare "what did they mean when they phrased that in my (system default) language (German)?" Like e.g. "Empfangsbestätigung" ... here we usually either say "Lesebestätigung" (Read Receipt) or "Übermittlungsbestätigung" (DSN) ... by checking the terminus used in the english localisation, I found out what the feature actually is about (Read Receipt).
