### ISSUE TITLE
Font default size is hardcoded

### ISSUE THREAD

**Issue by mirh** [k9mail/k-9#2280]
### Expected behavior
System font size should be respected. 

I see that you even went so far to make possible to customize every single screen then, but sometimes one would just like not to care much about details. 

### Actual behavior
Font default size is hardcoded. 

### Environment
K-9 Mail version: 5.203

Android version: 6.0.1

**Comment by cketti** [comment]
There's no such thing as a system font size. There's a default font size per theme, but apps are free to choose/define their theme. By default K-9 Mail uses the default's of Android's Holo theme which is probably as close as you can get to a "default system font size".

Android does provide a way for users to scale the font size, i.e. make all text smaller or larger. K-9 Mail supports this mechanism by setting font sizes in "scaled pixels".

**Comment by mirh** [comment]
In display settings it's called literally font size. And most apps seem to respect it. 
But regardless of anyhow you want to call it, this should be default behavior.

**Comment by cketti** [comment]
I just tested changing the system's "font size" and it does indeed not work. This seems to be related to us manually setting the theme each time an Activity is created.

**Comment by cketti** [comment]
Actually, it was the language selection feature that broke this.

**Comment by voidzero** [comment]
Speaking about font sizes — personally I am happy that K9 provides this level of granularity —  I have the following on my mind: when I reduce the font size of the message folder list, there remains a lot of spacing between the folder names. Could something be done about this? The entire point of reducing the size was to reduce their height so that more folders would fit on the screen.

I guess that the height might currently be how it is due to the 'new messages' dot, and the 'marked messages' star. These appear to be images - if that's why the height is fixed, then perhaps these could be replaced with utf-8 characters, or emotes or glyphs (or however they're called). This might also enable to make their color customizable.

Oh, I should probably mention that I've just started using the material design version that I found via XDA-developers. Since that name is com.fsck.k9.material, I assume it's by youse guise. But if not, please correct me.

Anyway, just one other thing since I was on the subject of colors. Could it be made possible to customize colors for all of the fonts that of which sizes can already be adjusted? Even if just with html color codes. My reason for asking is that I would customize the sender and subject, to make things easior to catch on a glance.

I was about to write up an issue that would get a very similar title, so I might as well write it here, the previous issue seems to have been triaged and to be waiting for a fix. But if it's inappropriate do let me know and I'll gladly move these into separate issues - in case there's a chance for them anyway.

**Comment by voidzero** [comment]
Hey @cketti, I'd appreciate some form of feedback to what I typed above!
