### ISSUE TITLE
Send outgoing text/plain as format=flowed

### ISSUE THREAD

**Issue by Valodim** [k9mail/k-9#2302]
Outgoing text/plain mail can be formatted as format=flowed according to [rfc2646](https://tools.ietf.org/html/rfc2646).

We already have a method in `FlowedMessageUtils` from an the apache-licensed Apache James project, so this should only be a matter of calling the right method at the right place.

Starting point should be around `MessageBuilder.buildBody`

**Comment by AnirudhBadri** [comment]
I am a beginner to the open-source community and would like to start with this bug. Can I go ahead?

**Comment by danwain** [comment]
I have submitted a pull request with my take on the feature. Any feedback would be welcome. #2305

**Comment by cketti** [comment]
We currently always use quoted-printable as transfer encoding. However it shouldn't be used with format=flowed.

Right now I don't think we gain anything by using format=flowed. It's unnecessary when using quoted-printable. And the spec notes that it might cause some problems with right-to-left languages.

**Comment by Valodim** [comment]
Ah, you're right. Sorry, I didn't see that @danwain

**Comment by tya99** [comment]
In Thunderbird `format=flowed` is default and is used. It only uses `quoted-printable` for pgp messages. A lot of the email I send isn't actually encrypted.

I have found wrapping works reliably with `format=flowed` particularly on mobile devices.

**Comment by benbucksch** [comment]
@cketti , @Valodim : Format=flowed solves a number of real world issues with plaintext. It not only allows wrapping lines properly and adapting to different screen sizes (which is particularly important for mobile clients like K9Mail) and avoids "comb wrapping", but also specifies clearly how quotes should look like, unambiguously fixes the mbox "From at the start of the line" issue in a reversible way etc..

format=flowed is essentially plaintext mail done right.

Please note that you already do implement format=flowed (RFC 2646), in [`FlowedMessageUtils.java.flow()`](https://github.com/k9mail/k-9/blob/bf33cfd73a81e37df2f48f35ee4c2f1ec3fe2427/app/core/src/main/java/com/fsck/k9/mailstore/util/FlowedMessageUtils.java#L120). You're just not invoking it.

**Comment by janilowski** [comment]
Shouldn't this issue be opened again?

**Comment by shader** [comment]
Coming from  #7084, I would also like to reopen this issue.

https://useplaintext.email/ includes "Wraps text or format=flowed" as a criteria for clients supporting plaintext, and K-9 currently does not meet that requirement.

With some basic testing, it seems that indeed K-9 is not wrapping the text being sent, which is improper formatting for text emails. The 'soft breaks' in quoted-printable are an encoding-level feature, not real line breaks, resulting in long lines that some clients do not wrap.

To reiterate the points from @benbucksch and others:
- for users who care about plain text emails (rare, I know), proper wrapping may be important
- plaintext emails *should* be wrapped at ~72 lines
  - K-9 could get a recommendation at useplaintext.email if handled correctly
- `format=flowed` improves line wrapping flexibility while maintaining backward compatibility
- the code is already in the code base, and K-9 already supports reading `format=flowed` emails, so why not support sending it?

I am willing to do the work to support this, I just want to reopen discussion so we can figure out the best way to fit it into your existing design goals. At the very least I think it could be an option in the "Sending mail" settings; I think the question is how you think that option should be presented.

Some ideas:
- an alternative plain text format (in the same drop down as Plain Text, HTML, and Auto)
- as a separate dropdown for choosing which plain text format to use

**Comment by benbucksch** [comment]
> format=flowed is obsolete

Format=flowed also specifically defines how to unambiguously mark quotes, and how to preserve flowed text in quotes.

1. Where does quoted printable define what a quote is? Or which other standard defines it? Where in the standards is defined how the combination of quotes and flowed text works?
2. You said that all "modern" email clients implement quoted-printable and flowed text correctly. Do they also all, without exception, interpret and send quotes correctly? Including quotes of quotes and flowed text in quotes? 100% all of them? Or are there email apps in significant use which have shortfalls there? Which then affect everybody else, including K9mail users?

The advantage of format=flowed is that it works with all clients. Email has many vastly different implementations, and only 1 sub-par email app destroys the thread for *everybody*.

**Comment by belkka** [comment]
@cketti 
> Soft line breaks in `format=flowed` are no different from soft line breaks in `quoted-printable`. They are part of the encoding, not the content.

Actually, `format=followed` is a media type rather than encoding (meaning it's different than quoted-printable). Compare:
```http
Content-Type: text/plain; format=flowed
```
```http
Content-Transfer-Encoding: quoted-printable
```

I emphasize this because `format=flowed` allows to mix different chunks of text — _flowed_ (human text) and _fixed_ (code chunks/git patches). To be precise, it defines [fixed](https://datatracker.ietf.org/doc/html/rfc3676#autoid-3) and [flowed](https://datatracker.ietf.org/doc/html/rfc3676#section-3.1) _lines_ and then defines [a paragraph (4.1)](https://datatracker.ietf.org/doc/html/rfc3676#section-4.1):

> A series of one or more flowed lines followed by one fixed line is
   considered a paragraph, and MAY be flowed (wrapped and unwrapped) as
   appropriate on display and in the construction of new messages
   
[Also (4.2)](https://datatracker.ietf.org/doc/html/rfc3676#section-4.2):

> Any number of fixed lines can appear between paragraphs.

I can think of it as of "light-weight" markup, where only semantic equivalent of HTML `<pre>` or Markdown code blocks are allowed.

As I understand, advanced "plain-text-email" users (lets call them hackers) actively work with code blocks and git patches in email message **bodies** (not attachments, https://git-send-email.io/). Since `format=flowed` is not widely adopted, they have to deal with usual (not flowed) plain text emails a lot.

> No modern email client treats long lines in text/plain parts to mean "this is a very long line, don't wrap it for display purposes; scroll horizontally if you have to"

True, but my guess is, plain-text-hackers **intentionally disable** soft-wraps in "usual" text/plain emails (even if their clients are **capable** of it), because it's more important for them to review included patches (code). Therefore even if I send a long personal pure-human-text email to a hacker from K9 mail, they still have soft-wraps disabled in their global settings for displaying non-flowed text/plain. With `format=flowed` I can explicitly indicate that soft-wraps should be enabled **for my message**. Even more — I can **mix** different types of wrapping, not just toggle it for the whole message.

## Possible solutions

#### 1. Lightweight solution, no UI changes
Since K9 Mail is an Android app, it's more reasonable to assume that users do not send **any** pre-formatted plain text chunks (code blocks/patches) **at all**, rather than **whole** email is pre-formatted (fixed) text/plain. In other words, it may be reasonable for the client to send `text/plain; format=flowed` and silently assume that every input line is a _flowed paragraph_ (in terms of [RFC3676](https://datatracker.ietf.org/doc/html/rfc3676)). It's impossible to send fixed lines between paragraphs (code blocks)

#### 2. "Perfect", complex solution
Implement some additional UI to allow creating "semantic equivalents" of HTML `<pre>` blocks in composed **text/plain** messages. They are sent as sequences of "fixed" lines between "paragraphs" of `format=flowed` as described in rfc3676. The solution requires maintaining more complex internal representation when composing emails ("_slightly_ rich text").

#### 3. Middle ground, little UI change, but less user-friendly
Add a "toggle format=flowed" option either in global settings or email editor. The main consequence of enabling this option is switching `Content-Type: text/plain` header to `Content-Type: text/plain; format=flowed`. The experienced user (aware of rfc3676) is responsible for typing spaces where they want to define a "flowed" line. K9 mail then (optionally) "decodes" and "re-encodes" format=flowed in order to re-balance lengths of flowed lines (for unaware recipients, mailing lists etc). This approach may be easier to implement if we can find and reuse existing libraries for "decoding" format=flowed -> "slightly rich text". Otherwise there is no advantage over solution (2)
