### ISSUE TITLE
pgp/mime decrypt BUT to not show up anything

### ISSUE THREAD

**Issue by oniter** [k9mail/k-9#2356]
Problem/Issue: After decryption, no content is shown at all.

The mail is build after this norm [https://tools.ietf.org/html/rfc3156](url)
and looks like:

```
from: address
to: address
subject: test.Multipart
MIME-Version: 1.0
Content-Type: multipart/encrypted; boundary=foo; protocol="application/pgp-encrypted"

--foo
Content-Type: application/pgp-encrypted

Version: 1

--foo
Content-Type: application/octet-stream

-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQGMA/X0t99 ...

-----END PGP MESSAGE-----

--foo--

```
Process of decryption works fine as far I can see 
(It asks for the key and shows red lock after; like in a MIME text/plain message).
But no plain text or html rendering is shown after, just nothing.

I can reproduce this every time. 

Just sending MIME text/plain with encrypted text works fine.

I use:
K-9 Version:5.203
OpenKeychain 4.2.4
Android Version: 6.0.1 

Note: Using Version 5.010 before, the text was shown in OpenKeychain after encryption.

**Comment by Valodim** [comment]
please send a mail like this to me at look@my.amazin.horse, encrypted to my key 0xdeadfa11 so I can investigate

**Comment by oniter** [comment]
Hi. I continued investigating this problem and found out 
if you have choosen OpenKeyChain as OpenPGP App
which you find under Settings --> Accountsettings --> Cryptography --> OpenPGP App
than the described behavior will occur.
But if you choose None Selection than you get the pgp/mime parts as files in your message.

Should this be the right behavior? 
(Note: The menu items are my translation and can be differ in the english version)

**Comment by oniter** [comment]
And as an off-topic question:
Have you plans to support the direct showing up off pure html encrypted messages in K9 itselfs when they are send as multipart/encrypted (pgp/mime) messages?

And as a second off-topic question:
Why is the type of a file more important than the content itselfs?
Means if I encrypt a pure html message which is stored in .html file or is stored in a .png file and send the encrypted part in correct pgp/mime messages like above (build after the mentioned standard) it will lead to different open options in OpenKeyChain after encryption because the former file type is recognized and therefore is not recognized as pure html text?

And all that said, please where is the major difference of version 5.010 to 5.203 for users other than that I save to clicks (not have to press "show message" --> "more" )?

**Comment by philipwhiuk** [comment]
@oniter Did you send @Valodim an example?

As for the intended behaviour, the expectation is that the decrypted mail is rendered correctly in the e-mail app. If you don't have an encryption provider the expectation is that the application suggests you install one, not that provides the content as attachments.

> Have you plans to support the direct showing up off pure html encrypted messages in K9 itselfs when they are send as multipart/encrypted (pgp/mime) messages?

That's the aim of the system and in most cases it works as expected, hence why Valodim wanted an example.

> Why is the type of a file more important than the content itselfs?

We look at the MIME type, then the file type. If you don't give us either we don't try and work it out. The reason is because it's a potential security vulnerability - passing unknown content to lots of different file loaders and seeing which works is asking for problems.

Guessing content from contents is a time consuming strategy that's unreliable. MIME types exist for a reason. Most email applications send the correct MIME type. Doing so is a requirement of creating valid emails.

> And all that said, please where is the major difference of version 5.010 to 5.203 for users other than that I save to clicks (not have to press "show message" --> "more" )?

Properly generated encrypted email is automatically shown inline in the app.

**Comment by oniter** [comment]
@Valodim 
Today I send you the above messages (two) to [look@my.amazin.horse](url). One encrypted with your pub key 0xdeadfa11.
Should it be a problem with the gmx provider I can send you the sec_key and passphrase and the logins for the gmx_account.

**Comment by oniter** [comment]
Is there something in common with request #2349 ?

**Comment by Valodim** [comment]
Got your message. The problem is that it is not well-formed: The outer mime structure of the encrypted message is fine, however to conform with rfc3156 the encrypted data must be a mime structure itself.

In your test mail, the encrypted data has no mime header, and immediately begins with `<html>`. This is not correct, and there is no way for a user agent to know that the contained data is indeed html. The simple fix is to have a line `Content-Type: text/html` on top of your encrypted content, followed by an empty line.

**Comment by oniter** [comment]
Thx very much for investigation.
I can confirm that with that line of Content-Type it works great.

I didn't read this in the rfc specification and nor did I when searching web for how to build up multipart/encrypted messages right. 

And yes, I think to support messages only which were built up after standard and only after standard is the best/rigth way. And if you have a little to-do that says what the standards are maybe with an example it would be great, specially now while K9 supports PGP/mine messages.

So sorry for the extra work and thx in general for that great mail-client.

Tino

Am 22. März 2017 10:52:24 MEZ, schrieb Vincent Breitmoser <notifications@github.com>:
