### ISSUE TITLE
Reset/lost settings in irregular intervals

### ISSUE THREAD

**Issue by psaaa** [k9mail/k-9#2371]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
K-9 Mail should keep its settings after setup

### Actual behavior
K-9 Mail resets itself/loses its settings in irregular intervals. I have to re-import all settings again and again. 

### Steps to reproduce
1. Install K-9 Mail
2. Setup K-9 Mail with your own settings
3. After some time if you start K-9 Mail it prompts if you want to import settings, after that it works for some time until the setup dialog comes up again.

### Environment
K-9 Mail version: 5.203

Android version: 7.1.1 with update from March 5th, 2017

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
See #750.

**Comment by cdpxe** [comment]
Just happened for the fourth time on my phone. Here is more detail:

- Started k9-mail. First thing I see is the unexpected "Welcome" screen that appears ("K9-mail is a ... + features"). This should not happen as I already configured+used the app since a few months (countless times a day). After this screen, I am allowed to setup a first e-mail account (because everything else is visible). The loss is always visible after a re-start.
- version 5.206 (and several previous versions)
- Android 5.x
- Account types: 3xIMAP + SMTP (all connections w/ TLS)

Hope this helps. Would be great to get a fix for this.
