### ISSUE TITLE
Huge Issues-Android Client to IMAP

### ISSUE THREAD

**Issue by GiantDogg715** [k9mail/k-9#2470]
So I use K9 Mail because it is seamless for my Squirrlmail corporate email and my personal GMAIL.  I had issues beginning last night as I got a message that my Authentication failed.  I could not log back in, and deleted/reinstalled the app this morning.  It still took several hours to connect, even though my laptop (windows 10 utilizing Outlook 2010 as the client) had no issues.  After FINALLY getting my phone to connect, it once again stopped connecting and I get this upon a sync "ErrnoException: open failed.
I use the app a lot because I am on the go quite often, and I am thinking I may have to go to another app for my Corporate email?

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

**Comment by GiantDogg715** [comment]
Thank you for not even trying to assist.  My company (I am CEO) and all 35 staff members are going to move to another client for email.  You have lost a corporate client for your laziness.  Feel free to have a senior member email me for any other details.

**Comment by philipwhiuk** [comment]
With respect, this is a technical issue tracker for a community developed open source project, not a paid 24/7 support solution for a corporate product. 

The mailing list is the best place to handle configuration issues because they are nearly always not bugs but rather misconfiguration.

If it was an issue, you would have a got a more productive response by filling out the issue form that we provide.

You provided no useful debug information, like the version you're running, the Android version of the device, the device itself or even the type of email account Squirrlmail.

In this particular case the `ErrnoException: open failed` suggests it can't open a file stored on the device. This could be the email database or something else. If your device has remote storage that could be a reason. Without a debug log or any of the information we ask for it's impossible to know.
