### ISSUE TITLE
Draft loses attachment

### ISSUE THREAD

**Issue by coogor** [k9mail/k-9#2547]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Saving a mail with attachment from KMail, syncing it with K9:
On the overview in the draft-folder the attachment is shown (paper clip symbol), when opening the mail no attachment is in, and when sending the mail there is no attachment either.

### Actual behavior
see the attachment in the mail, download the full attachment, and send draft with attachment

### Steps to reproduce
1. write draft
2. attach file
3. save as draft

### Environment
K-9 Mail version: 5.206

Android version:
7 on Galaxy S7 Edge
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by Trophisme** [comment]
Hello ,

I believe that the "expected behavior" and "actual behavior" should be switched.
I encountered the same problem here: almost lost important files that I saved on draft.
Only had to shut down the internet connexion from my phone before sync so I can get them directly from my computer.

People should be aware to not open a draft with attachment on their phones, whether it is to complete it or to send it.

I would gladly help to provide any information to help solving this issue.

**Comment by coogor** [comment]
You are right, actual and expected are swapped...sorry

**Comment by MarkCDSys** [comment]
I just had the same problem in 5.208
Please fix, this is a really annoying issue.

**Comment by itsbrody** [comment]
same to me in 5.2.0.8 with the speciality, that I wrote the e-mail with the attachment online, then saved as draft. In the mail overview (draft drawer) I see the e-mail and showing that it contains an attachment. When opened in k9 editor the attachment seems to be vanished, because it's no more viewable. Saving the draft as draft again finally looses it.

**Comment by chrisrapson** [comment]
Is this a duplicate of [#954](https://github.com/k9mail/k-9/issues/954) and [#1566](https://github.com/k9mail/k-9/issues/1566)?

I would also say it is related to [#2485](https://github.com/k9mail/k-9/issues/2485), which is a duplicate of [#3110](https://github.com/k9mail/k-9/issues/3110). 

So it seems like this is affecting a number of people. Are there plans to fix it? What can I/we do to help?

**Comment by cketti** [comment]
Duplicate of #954

**Comment by qwirl** [comment]
The attachment isn't solved, as PGP encryption issue with drafts are horrible.
If you save an encrypted draft, you are left with a draft that is epmty, and 2 attachments that you can neither open or download.

So if one draft a long email, like I did, and then save it to drafts, all work is lost.

Please take a loot at this, as PGP encryption is of upmost importance in todays neo 1984 society.

**Comment by kewisch** [comment]
I added 954 to the issues we'll look in to. No promises at the moment, but I understand your use case and hope we can find a fix.

**Comment by ZoomRmc** [comment]
Still an issue, at least with gmail.
