### ISSUE TITLE
Impossible to send Gmail mail since 2 days

### ISSUE THREAD

**Issue by Looping83** [k9mail/k-9#2634]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by Looping83** [comment]
Hi. Since to days, it's impossible to mail via my Gmail account with K9.
I get this error : Negative SMTP reply: 530 5.5.1
I've changed nothing in my settings and everything worked fine 2 days ago !
Any help ?

**Comment by Looping83** [comment]
MIUI 8.6, 7.6.6 beta
Account SMTP
The last release of K9

**Comment by nshiff** [comment]
@Looping83 I also had brief trouble with Gmail. It was because I enabled [two-factor authentication (2FA) for my Google account](https://www.google.com/landing/2step/). If you recently enabled 2FA, then a workaround is to generate and use an [application-specific password](https://support.google.com/mail/answer/185833?hl=en).
