### ISSUE TITLE
WebDAV should sync starred message status (IMAP's \Flagged)

### ISSUE THREAD

**Issue by cgogolin** [k9mail/k-9#2673]
### Expected behavior
After the flag representing the star action in an exchange account is removed on the server, this should be reflected in k9 after the next sync. In IMAP accounts this works flawlessly.

### Actual behavior
In Exchange accounts messages remain stared

### Steps to reproduce
1. Star a message in an exchange account (office 365 in my case) 
2. Remove the star flag with some other mail program or the web mailer 
3. Sync k9 and observe that the star is still there. 

### Environment
K-9 Mail version: 5.207

Android version: 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange): Exchange

**Comment by philipwhiuk** [comment]
WebDAV is an imperfect implementation due to the limited functionality and documentation for WebDAV. Office 365 does support IMAP by the way. It mostly exists now for Exhcnage 2003 and earlier. Prior to my work upgrading I did some fixes for it (e.g. #1143 ).

Nevertheless, in order to make this work we need to fetch the other flags in the `fetchFlags` method of `WebDavFolder`. We simply don't fetch anything other than `SEEN`.

https://github.com/k9mail/k-9/blob/master/k9mail-library/src/main/java/com/fsck/k9/mail/store/webdav/WebDavFolder.java#L495

The issue is how it is encoded in WebDAV. We need to know how to query it.

The appropriate schema is https://msdn.microsoft.com/en-us/library/ms874577(v=exchg.65).aspx

The closest might be the 'messageflag' field but some experimentation is required to work out what it's set to.

Honestly for now we should probably remove the star completely from WebDAV messages to indicate that we can't fetch or update the star.

**Comment by cgogolin** [comment]
Thanks for the fast reply! 

Please don't remove/disable this feature. Syncing stars to the server does work reliably! Staring a message sets a flag interpreted by evolution mail als "follow up" and this is very very useful.

A comment on imap: Yes, Office 365 supports it, but is so broken that it doesn't work correctly with both k9 and evolution. Here marking messages as "read" doesn't work, so that they come back as unread on average two to three times. That's the only reason I restored to using Exchange. I don't think it is a bug in k9, but one in Office 365, that's why I didn't bother you...

**Comment by philipwhiuk** [comment]
Starring a message in IMAP works. Starring a message in WebDAV won't. I was proposing hiding the star for WebDAV messages.

**Comment by cgogolin** [comment]
It does work with both imap and  WebDAV/Exchange. I am using this feature every day.

In imap accounts the star sets something that marks messages as "important" after beeing synced to evolution and in Exchange accounts it sets something interpreted as the "follow up" flag by evolution. The end result is almost the same: The messages appear in red color in evolution. If the "important" flagis then unset in evolution this is reflected in k9, unsettling the "follow up" flag is not synced back to k9.

**Comment by philipwhiuk** [comment]
I'm not sure how Important works - possible it edits the X-Priority header of the message. But setting, unsetting or unsyncing the star in K-9 in WebDAV will do absolutely nothing - there's no code for sending it over WebDAV.

**Comment by cketti** [comment]
Obsolete because of #4251
