### ISSUE TITLE
Why not providing HTTP and SOCKS proxy implementation?

### ISSUE THREAD

**Issue by aurora-potter** [k9mail/k-9#2689]

**Comment by philipwhiuk** [comment]
Duplicate

**Comment by aurora-potter** [comment]
I love the way you develop software.

**Comment by Valodim** [comment]
In our free time, you mean ;)

But yes, @philipwhiuk could have referenced what it's a duplicate of. Then again, could have searched for the issue before opening as the template instructs rather than just deleting it to post a question that is like to have come up in the past couple of uh, years.

See #980
