### ISSUE TITLE
Refresh folder list and Folder settings issues

### ISSUE THREAD

**Issue by rancidfrog** [k9mail/k-9#2703]
K9mail has issues with setting proper folder lists.
In particular for spam folders.
For example, my outlook account defaults to spam folder when it should be junk.
Even after changing folder settings for spam folder to junk(it appears as an option), and clicking menu/refresh folder settings, the folder does not get updated:

![](https://s29.postimg.org/as5drbk8n/Screenshot_20170825-131208_01_01.png)

**Comment by rancidfrog** [comment]
I found the proper folder after clicking menu/show folder/all
The proper spam folder appears as "Junk (Spam)" and I am able to refresh it.

So, now I am confused.
I already went to "account settings/ folder settings"
and selected "Spam folder as junk" but nothing happens when I refresh folder settings or when I check for mail.
Spam folder is linked to non-existent junk folder, and not to the proper junk (spam) folder

**Comment by cketti** [comment]
"Junk (Spam)" means the name on the server is "Junk" and it's marked as the Spam folder in K-9 Mail. Sounds like everything is working as it should.
We'll change this in the future to display a special Spam icon instead of appending "(Spam)" to the folder name. Hopefully that will be less confusing.

**Comment by philipwhiuk** [comment]
I think the real issue here is that K-9 creates special folders when they don't exist. It shouldn't.

**Comment by rancidfrog** [comment]
It is a little confusing.
As refreshing folder list should remove non-existent Spam folder, especially after setting spam folder to "junk".

- What does refresh folder do?
- Why have setting to set spam folder when it does not really do anything but display "(Spam)" beside folder, (if you set junk folder as spam and it shows accordingly, then when you refresh folder list one would expect the automatically created spam folder would be removed since you already selected proper folder in folder settings)
- Why are non-existent folders being created, k9mail-errors (for errors?), 2 Outbox folders, non-existent Spam folder,  Notes folder (need to check outlook, might be one of the default folders)

**Comment by philipwhiuk** [comment]
1. What does refresh folder do?

It fetches the list of folders from the server.

2. Why have setting to set spam folder when it does not really do anything but display "(Spam)" 

So that when you click 'Spam' it goes to the right folder.

3. one would expect the automatically created spam folder would be removed

K-9 has created an actual folder called Spam I suspect. We can't just delete folders like this. As I said the bug is creating the folder.

4. Why are non-existent folders being created?

In certain cases this is a bug. However k9mail-errors is not a real folder, it's contents aren't uploaded.

5. 2 Outbox folders

One of those is a probably real folder on the server called Outbox the other is the local Outbox which K-9 puts emails waiting to be sent.

6. Notes folder

That's an Outlook folder.

**Comment by philipwhiuk** [comment]
@cketti Are you happy with me removing the ability for K-9 to create missing special folders and handling the appropriate errors with Toasts?

**Comment by cketti** [comment]
Not creating special folders sounds like a good idea.
Using toasts as error reporting mechanism is not that great. A snackbar might be better.
We still need to create some of those folders for POP3 accounts.
This probably requires some more thought about edge cases before someone starts to work on this.

**Comment by philipwhiuk** [comment]
Maybe this should wait until @rhari991's MessageController rework changes land?
