### ISSUE TITLE
[Feature] PGP Signature

### ISSUE THREAD

**Issue by ouafnico** [k9mail/k-9#2734]
Hi,

Is it possible to add an option to sign automatically all emails ? 

Actually for each even if I don't want to encrypt it with pgp, we can't tell k9mail to always sign it.

I'm using K9 5.208, with openkeychain.

Thanks

**Comment by Valodim** [comment]
Signed-only mails are of questionable use, which is why we removed this particular workflow.

Please see my blog post for more thoughts on this: https://k9mail.github.io/2016/11/24/OpenPGP-Considerations-Part-I.html

**Comment by simbalion** [comment]
Signed only Emails are the best way to defeat phishing. Companies should sign all outgoing correspondence with customers. By removing this feature you've made it impossible to use K9 in a convenient way for someone operating a business, like me, who wants to provide that extra level of security for their cautious customers.

**Comment by Valodim** [comment]
For a solution that actually works in practice for this use case, I encourage you to look into DKIM

**Comment by simbalion** [comment]
I'm a little stunned that you even said that. Literally everyone in the world is using DKIM, has been using DKIM for years, and Phishing has not been affected at all. It might even be on the rise. And the solution to that has been DMARC, which takes all the control out of the hands of users and places it in the hands of postmasters. I wrote about DMARCs failure here: https://tailpuff.net/dmarc-is-not-the-solution-to-e-mail-fraud/

No sir, the solution to phishing has been PGP/GPG signing all along, and will continue to be in some form or another. Thunderbird + Enigmail offers a great option to always sign everything, and K-9 mail should include a similar feature. The only thing holding back GPG/PGP as a standard feature of E-mail that people just know how to use is developers who aren't making it a default feature of their E-mail clients because they think the peasants can't handle it, so you'll understand I think your decision is a step backwards.

**Comment by Valodim** [comment]
I read your blog post, and from my several years of experience actually developing openpgp software, I fully disagree with almost all of its points. My stance on signed-only mails, as I have written about in the k-9 blog (link above), hasn't changed.

I noticed, however, that my comment above might have been ambiguous: We did not remove support for signed-only mails, only for sending signed-only mails by default. You can still sign e-mails.

**Comment by simbalion** [comment]
Yeah and I appreciate that the feature is at least manual, but has to be enabled every time I send an E-mail which is a pain in the butt. 

K-9 Mail used to be featured on EFF's website with a tutorial for PGP on Android, which is how I heard about it. That tutorial is gone these days, and I can't help but wonder if that's because of your "stance". I mean no offense, but your opinion amounts to "users aren't smart enough to use the tools responsibly so we'll take the tools away".

It's too bad, K9 is the best email client on android with PGP support. I looked at alternatives last night, and saw there's a fork but it's just some guy's scam to sell his own keyring app. What a shame. PGP features should be standard in all email apps. And it should not require a per-email special effort to enable them. And it would be, except for people's agendas or greed getting in the way.

Again, I don't mean to offend you (but I probably will), but I wish you'd just bring back the feature instead of trying to save us all with your personal opinion of how we should use E-mail.

In your blog post you ask "If you receive an unsigned email are you really going to not trust the source?" Yes. The answer is yes. Especially if the source typically does sign their E-mails. And if that E-mail contains tradtionally suspicious content like "Your account is at risk of whatever!, click here to fix it!" then I would trust it even less, and seeing that it is unsigned would validate my mistrust. Your reasoning is very narrow and the action taken extreme. I hope you'll reconsider.
