### ISSUE TITLE
Email notification grouping doesnt allow group deletion

### ISSUE THREAD

**Issue by jimimaseye** [k9mail/k-9#2842]
Previously, when multiple new emails arrived for a single account, those emails were grouped in to a single notification (1x swipe down) which on a single press could be all deleted (ie, DELETE ALL).  Now, a group requires expanding (the 2nd swipe down), and when the group is expanded, each email is shown individually and each one then needs expanding (the 3rd swipe down) to get the DELETE button.  However, after doing a delete of an individual email and confirming YES to delete, the notifications need to be opened again (with 3x swipe downs) to then delete the next email in the list.

Imagine doing this if you have multiple emails - it takes ages!  8 emails = 24 swipe downs.  (This is very possible for accounts that have, for example, forum or mailing list notifications, or emails that come in over night.) 

This was not the behaviour in a previous version.  Emails were grouped and offered a single 'Delete all' button.  I do not know if it is the version of K9 or the version of android that makes it behave differently (previously I was running the latest version of K9 on android 4.2.1).  I am now running on android 7.0 (Samsung). Of course it is easier to instead tap the notification and do rapid select and delete from within the account inbox but this is a backward step given we once had the option to delete from notification.

### Expected behavior
All new mail notifications for a single account should appear grouped in one header.  That header, once expanded to show the subset of individual mails (to a certain limit - previously it was 6) should have the option to DELETE ALL to then effect a delete of all the emails in that account group.  It could also enable further swipe down to expand individual emails and offer individual delete oif required.

### Actual behavior
3 swipe downs for each email with ability to only delete one at a time.  (Process explained above)

### Steps to reproduce
1.  Send in 5 emails to the sam address
2.  Receive notifications
3.  Get swiping!

### Environment
K-9 Mail version:  5.208

Android version:  7.0 (Samsung)

Account type (IMAP, POP3, WebDAV/Exchange):  IMAP

**Comment by cketti** [comment]
That's the way notifications are grouped in newer Android versions. We could make K-9 Mail behave like it did before and only generate a summary notification. But to me that is a step backwards. Optimizing for batch operations in notifications rather than for individual actions is not something I want to do.

And before anyone can ask, no, we won't make it a setting either. The notification code already is way too complex.

You could "optimize" your process by disabling delete confirmations. That way you only have to swipe to expand the notification of an individual message, then press the button to delete, swipe to expand the next message, etc.

**Comment by marki555** [comment]
@cketti I have also the same issue after upgrading to Android 7. Isn't it possible to have an action (Read / Delete) for the entire group in addition to the individual emails? Right now the group on my Samsung has only "Block notification"s and "Clear" actions.
