### ISSUE TITLE
Second line header is always presuming UTF-8 instead of the email's real encoding

### ISSUE THREAD

**Issue by Massedil** [k9mail/k-9#2851]
### Actual behavior

![1](https://user-images.githubusercontent.com/20357783/31827315-a94ba4d8-b5b7-11e7-81a5-7df8d0a6a8ec.png)

Both emails are ___well displayed___ in the display view.

### Steps to reproduce

Just send a text email with no encoding specified.

It works :

	------BOUNDARY
	Content-Type: text/plain; charset="utf-8"
	Content-Transfer-Encoding: 8bit
	
	...est dÃ©sormais crÃ©Ã©.
	

It is not working :

	------BOUNDARY
	Content-Type: text/plain
	Content-Transfer-Encoding: 8bit
	
	Nous vous remercions pour l'intérêt que...

### Environment
K-9 Mail version: 5.208
Android version: 7.1.2

**Comment by cketti** [comment]
Up until RFC 5322 ASCII was assumed when no charset was specified. I believe with RFC 6532 this changed to UTF-8. However, we don't support RFC 6532 yet. So not specifying a charset is asking for trouble. And it's unlikely that we'll ever add charset detection heuristics.
Try asking the sender to explicitly specify the charset. And tell them to make it UTF-8, because everything else is insane in 2017.

**Comment by Massedil** [comment]
> Up until RFC 5322 ASCII was assumed when no charset was specified.

So you have to presume ASCII ? Not UTF-8 ?

Exactly like the view when I open the mail, no ?

> And it's unlikely that we'll ever add charset detection heuristics.

I understand it, you do not have to add a charset detection heuristics, I think it's better to presume ASCII if there is no encoding specified (as you say RFC 5322 assumes it's ASCII).

And, for sure, I understand it's ___really___ better to precise an encoding and to use the UTF-8 encoding.
