### ISSUE TITLE
Adding Unread Mail Widget

### ISSUE THREAD

**Issue by RonenGolan** [k9mail/k-9#2947]
### Expected behavior
Using Sony Xperia Z5, with Android 7.1.1, when adding the unread mail widget to home screen, an envelope icon of the selected mail account should appear. 

### Actual behavior
Nothing happens. the Envelop icon doens't appear for some reason. other widgets of other applications work perfectly fine. 
Important: I have read similar issues which don't seem fully address this. while i was able to add the widget before the last android upgrade (i.e. 6.1), i'm currently unable to do so. consequently i added a new email account but couldn't add it's unread widget. while the previous accounts widgets are still there. 

### Steps to reproduce
1. go to widgets section after a long press on home screen.
2. select the K-9 unread widget and drag it to home screen
3. select a mail account in k-9
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by cketti** [comment]
Sounds like this might be a problem with Sony's launcher rather than a bug in K-9 Mail.

If there's an easy way to work around this bug we'd be happy to include it. But short of a developer with an affected device tracking down the exact cause and coming up with a work-around I don't see this being fixed by changing K-9 Mail. You'll probably have more luck asking Sony to look into this.

**Comment by RonenGolan** [comment]
Hi,

 

Thank you for addressing this issue. 

This problem happens also with the Nova launcher. With the CM launcher it works fine.

So maybe you can reproduce it by installing the Nova launcher on a 7.1.1 Android.

 

Thank you.

Ronen.

**Comment by cketti** [comment]
Works for me with Nova launcher. Make sure to press the "save" button in the action bar after configuring the widget. Pressing the back button will abort the widget creation.
