### ISSUE TITLE
SQLite3 error causes application crash

### ISSUE THREAD

**Issue by TeryWhenett** [k9mail/k-9#2955]
### Expected behavior
I open K9 mail, all four accounts synch and I browse my new mails

### Actual behavior
I open K9 mail, it tries to snych and instantly closes.
If I turn my WLAN off so that there is no connection, I can browse my mails as intented - but as soon as I turn it on again, K9 mail jumps to account overview and then quits.

### Steps to reproduce
1. Open K9 mail without internet connection
2. Connect to the internet OR Open K9 mail with internet connection
- done -

### Environment
K-9 Mail version: 5.208
Android version: 5.1 on Huawei LYO-L21
Account type: IMAP

**Comment by philipwhiuk** [comment]
Hmm? @cketti - do we have crash logs for this?

**Comment by deconya** [comment]
Im having the same problem. I check with different IMAP accounts and seems that happens when check INBOX. Im using a huawei mobile, but looking last upgrade was justly to solve a problem when syncro, so can be the problem is not solved?

**Comment by freica** [comment]
I have the same Problem also with an Huawei Phone, Android 5.1 since a few days.
HUAWEI LYO-L21C577B128, EMUI 3.1

**Comment by lifesabeach72** [comment]
K-9 Mail version: 5.208
Android version: 5.1 on Huawei LYO-L21
Build: HUAWEI LYO-L21C577B128, EMUI 3.1
emailprovider: gmx.net

Seems to be the same problem here:
- opening K-9 and starting a sync by swyping down
- sync stars
- app closes (crashes) immediately after sync starts
- sync-icon is still displayed in notification bar but sync never completes
- reopening K-9: same old mails, no new mails synced.

Problem exists for a while, last successfull sync in K-9 was on Nov. 18th
The G-Mail app syncs the same gmx-mailaccount without a problem - on the same phone.
But i would prefer using K-9 by far. So i followed your instructions to provide a logfile to you.

Downloaded adb, captured a logfile, created a github account, just to add the needet logfile to this issue - but always get a "Something went really wrong, and we can’t process that file."

My experience in reading logfile is quite limited.
All i can see is, that the sync starts and that the gmx-mailserver answers with a messagecount but a lot of lines later:
12-05 12:09:55.431 I/Zygote  (  279): Process 13668 exited due to signal (6)
12-05 12:09:55.434 I/ActivityManager(  990): Process com.fsck.k9 (pid 13668) has died

I try to upload the logfile later - any hints, what could have gone wrong?

**Comment by deconya** [comment]
Seems to be a general bug produced by this firmware. Im using email client from mobile and goes without problems. Now the question is how to open a bug to advise developer, This topic was opened days ago and is continue marked how needs info.

**Comment by lifesabeach72** [comment]
Yes, because @philipwhiuk asked for a logfile. I finally managed it to upload my logfile from yesterday:
 [k9-log.txt](https://github.com/k9mail/k-9/files/1536421/k9-log.txt)

Hopefully this helps to get closer to a solution.

Ah, don´t know if its important: I use POP3.

**Comment by philipwhiuk** [comment]
```
2-05 12:09:54.772 I/AEE/AED (13711): Build fingerprint: 'HUAWEI/LYO-L21/HWLYO-L6735:5.1/HUAWEILYO-L21/C577B128:user/release-keys'

12-05 12:09:54.772 I/AEE/AED (13711): Revision: '0'

12-05 12:09:54.772 I/AEE/AED (13711): ABI: 'arm'

12-05 12:09:54.772 I/AEE/AED (13711): pid: 13668, tid: 13688, name: MessagingContro  >>> com.fsck.k9 <<<

12-05 12:09:54.772 I/AEE/AED (13711): signal 6 (SIGABRT), code 0 (SI_USER), fault addr --------

12-05 12:09:54.800 I/AEE/AED (13711): Abort message: 'external/sqlite/dist/sqlite3.c:91450: sqlite3DeleteFrom: assertion "pPk || iDataCur==iTabCur" failed'

12-05 12:09:54.800 I/AEE/AED (13711):     r0 00000000  r1 00003578  r2 00000006  r3 00000000

12-05 12:09:54.800 I/AEE/AED (13711):     r4 a2416db8  r5 00000006  r6 00000002  r7 0000010c

12-05 12:09:54.800 I/AEE/AED (13711):     r8 b459c380  r9 00000000  sl 00000001  fp 00000000

12-05 12:09:54.800 I/AEE/AED (13711):     ip 00003578  sp a2415ee8  lr b6d9a821  pc b6dbda7c  cpsr 600e0010

12-05 12:09:54.800 I/AEE/AED (13711): 

12-05 12:09:54.800 I/AEE/AED (13711): backtrace:

12-05 12:09:54.800 I/AEE/AED (13711):     #00 pc 0003aa7c  /system/lib/libc.so (tgkill+12)

12-05 12:09:54.800 I/AEE/AED (13711):     #01 pc 0001781d  /system/lib/libc.so (pthread_kill+52)

12-05 12:09:54.800 I/AEE/AED (13711):     #02 pc 00018427  /system/lib/libc.so (raise+10)

12-05 12:09:54.800 I/AEE/AED (13711):     #03 pc 00014c77  /system/lib/libc.so (__libc_android_abort+34)

12-05 12:09:54.800 I/AEE/AED (13711):     #04 pc 00013058  /system/lib/libc.so (abort+4)

12-05 12:09:54.800 I/AEE/AED (13711):     #05 pc 00015e81  /system/lib/libc.so (__libc_fatal+16)

12-05 12:09:54.800 I/AEE/AED (13711):     #06 pc 00014d01  /system/lib/libc.so (__assert2+20)

12-05 12:09:54.800 I/AEE/AED (13711):     #07 pc 0005d503  /system/lib/libsqlite.so

12-05 12:09:54.800 I/AEE/AED (13711):     #08 pc 0005c94d  /system/lib/libsqlite.so

12-05 12:09:54.800 I/AEE/AED (13711):     #09 pc 0005cbb5  /system/lib/libsqlite.so

12-05 12:09:54.800 I/AEE/AED (13711):     #10 pc 0005d2e9  /system/lib/libsqlite.so

12-05 12:09:54.800 I/AEE/AED (13711):     #11 pc 0005db25  /system/lib/libsqlite.so

12-05 12:09:54.800 I/AEE/AED (13711):     #12 pc 0006516f  /system/lib/libsqlite.so

12-05 12:09:54.800 I/AEE/AED (13711):     #13 pc 000677ed  /system/lib/libsqlite.so

12-05 12:09:54.800 I/AEE/AED (13711):     #14 pc 00067abf  /system/lib/libsqlite.so

12-05 12:09:54.800 I/AEE/AED (13711):     #15 pc 00067e07  /system/lib/libsqlite.so

12-05 12:09:54.800 I/AEE/AED (13711):     #16 pc 0006819b  /system/lib/libsqlite.so

12-05 12:09:54.800 I/AEE/AED (13711):     #17 pc 00068897  /system/lib/libsqlite.so

12-05 12:09:54.801 I/AEE/AED (13711):     #18 pc 00068b6d  /system/lib/libsqlite.so (sqlite3_prepare16_v2+12)

12-05 12:09:54.801 I/AEE/AED (13711):     #19 pc 00079f53  /system/lib/libandroid_runtime.so

12-05 12:09:54.801 I/AEE/AED (13711):     #20 pc 0022ee3d  /data/dalvik-cache/arm/system@framework@boot.oat
```

Looks like an sqlite bug to me. :(

**Comment by lifesabeach72** [comment]
Thank you for taking a look at my logfile.
Please allow a question for all who are new to participating in open source software issues (like me):

How does this is going on?
Means sqlite bug that this list is the wrong place an we shoult try to adress sqlite?
Or is there a chance that someone can/will fix it within K-9 and we just have to wait?
Or is the priority of this issue to low to solve because it seems that only the Huawei LYO-L21 is affected?

If my questions seems to be improper or impatient - sorry, its not ment to be. Im just new to that and no native english speaker.

**Comment by philipwhiuk** [comment]
It's the Android version of SQLite on the Huawei LYO L21. Either it's a Huawei issue or a Google issue. I'm not sure there's much we can do as app developers. :(

**Comment by cketti** [comment]
This is most likely a firmware bug that K-9 Mail just happens to trigger. Please report this bug to your device vendor.

**Comment by YtvwlD** [comment]
@TeryWhenett @freica @deconya @lifesabeach72 
Have you all installed K-9 from Google Play?
The crash seems go away here if I install K-9 from F-Droid.
