### ISSUE TITLE
K9 + Openkeychain + OTG + Yubikey makes virtual keyboard (gboard) dissapear

### ISSUE THREAD

**Issue by VocUdmas0oms** [k9mail/k-9#2972]
### Expected behavior
Tell us what should happen: Virtual keyboard should still appear

### Actual behavior
Tell us what happens instead: Virtual keyboard hides when OTG + Yubikey plugged in.

### Steps to reproduce
1. Install K9
2. Install Openkeychain
3. Plugin OTG + Yubikey
(upon recognition, virtual keyboard dissapears)
4. Attempt to type email with OTG + Yubikey plugged in

### Environment
K-9 Mail version: (latest at the time of this issue)

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): Any

**Comment by cketti** [comment]
That's probably because the Yubikey is recognized as a keyboard by the OS. If that's the case you should see a notification in the status bar. Clicking it will bring you to "physical keyboard" settings where you can (re)enable the virtual keyboard.

If that doesn't work please try the [mailing list](http://groups.google.com/group/k-9-mail) for help. This issue tracker is the wrong place for support requests.
