### ISSUE TITLE
Request: Add possibility to backup with adb

### ISSUE THREAD

**Issue by Agno94** [k9mail/k-9#2993]
### Expected behavior
I'd like to backup K9-mail with adb in order to restore it faster after updating Android.
But in "k9mail/src/main/AndroidManifest.xml"  android:allowBackup is set to false.
To allow adb backup it should be' android:allowBackup="true" '.

### Steps to reproduce
1. run adb backup -f filename.ab -apk com.fsck.k9
2. an 41b empty backup file is produced

K-9 Mail version: master 
Android version: 4+

**Comment by philipwhiuk** [comment]
We allow you to export your settings (without passwords). Everything else is synced to your mail-server so doesn't benefit from back-up.

We deliberately don't allow back-up via ADB as it allows someone to export your email and passwords in plain-text.

Works as intended.

**Comment by stebeh** [comment]
I think that securing access to data on the device should be handled at the OS level; not per app - and I believe it is already taken care of: you have to trust the computer you are connected to and confirm the backup on the unlocked device.

Disallowing backup forces me to have a different procedure for each app; which cannot be scripted on the PC and requires a lot of manual intervention every time I want to create a backup.

Very counter-productive IMO.

**Comment by sbin-umount** [comment]
Philip,
I feel very sorry to read that is broke by design.

There might be a couple of reasons not to support adb backup,
like the fact it is marked as depreciated.
But I don't like the assumption to be smarter than the user.
Yes exporting the email and whatnot in plain-text, that would constitute a backup.
To be left to the discretion of the user to accept or not.

One of the use cases (and it happens to be the one I need a solution)
is the mail-server no longer exists and the mailbox in K9 is the last resort.
Please let me know how else I would do it.

Requirements of a good mail client go beyond receiving and reading email.
