### ISSUE TITLE
CTRL-A & CTRL-C

### ISSUE THREAD

**Issue by smvsmvsmv** [k9mail/k-9#3057]
### Expected behavior
On tablet with full keyboard, CTRL-A while editing email should "Select All" and CTRL-C should "Copy to Clipboard" 

### Actual behavior
CTRL-A - Opens address book
CTRL-C - Opens a dialogue box about encryption

### Steps to reproduce
1. Open new/reply/forward email
2. Edit text in body
3. Hit either CTRL-A or CTRL-C

### Environment
K-9 Mail version:
5.400
Android version:
7.0
Account type (IMAP, POP3, WebDAV/Exchange):
Various

**Comment by fat-tire** [comment]
Yeah-- I agree many of these keys need to be remapped.  Here are the current shortcuts in the message list/readmode (MessageList.java) -- they're different in the folder view.
```
voldown -- next message
volup -- previous message
C - Compose a new message
Q - show folder list (go back)
O - Cycle message sort order
I - reverse cycle sort order
D -Delete (move to trash folder) selected mail or thread (NO CONFIRM?! No undo?!)
S - message select toggle
G - toggle star
M - move to another folder (it prompts you)
V- archive selected
Y - copy to another folder (it prompts you)
Z- toggle read/not read status
F - forward email (same as forward option)
A- reply all
R - reply
J/P - previous message
N/K - next message
H - toast?
left dpad :  previous message
right dpad: next message
```
Some of these make sense I guess, but some like "D" should be something more intuitive like the DELETE button.  Also most of these you'd think would be control-commands rather than straight letters to be sure they were deliberate.

In the actual editor:
```
^n - new attachment
^s - send (NO!!! this should be SAVE)
^a - add from contacts
^d - save drafts (this should be ^s)
^q - quit/discard
^r - read request read receipt
^c - enable/disable encryption (should obviously be copy)
^g - openpgp sign enable/disable
^i - inline PGP enable/disable
```
^S for send is a horror show.  I can't tell how many messages I've sent in the middle of writing!

There are all kinds of other issues with using a mouse I've found.  If you select text in a message with your finger, you get the copy/paste menu.  Do the same selection with the mouse pointer, and you get nothing.  (And of course if you ^C at that point, you get the weird encryption menu).

Looking at [Thunderbird's shortcuts](https://support.mozilla.org/en-US/kb/keyboard-shortcuts) might be a little helpful and more sensible default options.

There should also be some kind of easy way to know what these shortcuts are!

I'll play with it and report back here.

**Comment by fat-tire** [comment]
Okay I just converted everything to much better match Thunderbird and avoid mistakes:

        ^N, ^M - Compose a new message
        ^R - Reply
        ^-SHIFT-R - reply all
        ^L - Forward email
        DEL - Delete selected mail/thread
        SPACE - Select/Deselect message
        S - Toggle star
        R - Toggle read status
        ^-SHIFT-M - Move to another folder
        A - Archive selected
        ^C - Copy to another folder
        F - Next message
        B - Previous message
        O - Cycle sort order
        I - Cycle sort type
        H, /, ? - This help

During composition, it's also similar to Thunderbird:

        ^-SHIFT-A - New attachment
        Ctrl-ENTER - end now  
        ^P - Add from Contacts
        ^S Save drafts
        ^Q - Quit/discard
        ^R - Read request read receipt
        ^-SHIFT-C - Toggle encryption
        ^-SHIFT-S - Toggle openpgp signature
        ^-SHIFT-I - Enable/Disable inline PGP
        ^A Select All
        ^C Copy
        ^X Cut
        ^V Paste
        ^Z Undo
        ^-SHIFT-Z Redo

The EditText has its short cuts intact to help navigate forward/backwards with like control arrows to jump through words and such.

To implement all this, I had to use the Compat library as the modifier keys on menu items were only introduced in api 26.  No big deal, as it was already all set up for material design.

I have to say this ***MUCH*** better and more intuitive on Chromebook and I imagine anything using a hard keyboard with any device.

I'll test a bit more-- maybe post a link to the commit in my repo and/or a PR soon.  I don't know how exactly to do the PR as it requires the Material Design stuff which is not yet accepted.  Also my version is slightly different than the PR that has been submitted already.

Also, I notice there are more KEYCODE tests in `FolderList.java` which I haven't looked at yet.  This is the list of mailboxes and probably would not be as important.

**Comment by JonasT** [comment]
Even worse, pressing `CTRL+C` on a hardware keyboard when *viewing* a message in your inbox will actually leave the message view and start the composer! That is even more disorienting than the odd encryption message. Would be really cool if this could be fixed
