### ISSUE TITLE
Notification light not working properly

### ISSUE THREAD

**Issue by bigtreiber** [k9mail/k-9#3098]
### Expected behavior
Notification light should be activated when a new message arrives, independent from any other settings

### Actual behavior
Notification light is only working when at least "vibrate when mail arrives" is activated

### Steps to reproduce
1. Set ringtone to "none"
2. Disable "Vibrate when mail arrives"
3. Get new mail => no notification light

### Environment
K-9 Mail version:
5.4.2

Android version:
8.0.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment]
I believe this is expected Android behavior.

**Comment by Hawk777** [comment]
If this is expected Android behaviour, then the options menu shouldn’t let you configure something that the OS won’t allow. That is, if you don’t choose a ringtone and you don’t enable vibration, then the options menu shouldn’t let you enable Blink LED given that that setting will be ignored.

**Comment by IgitBuh** [comment]
> I believe this is expected Android behavior.

No, it's most certainly not. I'm using LED notifications for other apps without any sound or vibration notification. I'd like to be notified about emails discretely, thus only by LED, not by vibration or ringtone.

Please re-open this issue. A fix / adjustment for newer Android versions would be highly appreciated.

**Comment by cketti** [comment]
We're not doing anything special. Just configuring what we'd like a notification to look/sound/feel like. What the OS does with that information is highly dependent on the particular Android flavor on a device.

The next K-9 Mail version won't allow you to configure vibration and notification light on newer Android versions because it's now handled by Android itself. Maybe this will fix your issue. If not, you'll have to take it up with the vendor of your Android device anyway.

**Comment by IgitBuh** [comment]
Please don't remove these configuration options. Newer Android versions offer a new notification API that you need to implement for allowing notification configuration for certain events. I see many different notification options for some apps (messengers, calender, todo-app, etc.) but only enable/disable notifications for K-9, because apparently it doesn't use that API. If you want to remove the options from the app, you would at least need to implement that notification API, otherwise there won't be any way to configure notifications at all. But as I see it, this API doesn't allow configuration of the LED light, only sound and vibration, so it wouldn't be a good alternative anyway.

Please leave the options in K-9 as they are and try to find a way to start the LED notification without having to use sound or vibration additionally. Would it be possible to enable vibration but set the vibration number to 0 or alternatively the rythm to a *very* short, unnoticeable vibration duration? That way the vibration trigger will trigger the LED vithout actually vibrating. That might also be a workaround you could implement if only LED notifiction is enabled on newer Android devices, so it would just work for everyone.
