### ISSUE TITLE
Not fetching mails

### ISSUE THREAD

**Issue by sbhandari-7** [k9mail/k-9#3104]
### Expected behavior
Sync to the emails

### Actual behavior
Not syncing emails
Doesnt matter if set at any interval
Sometimes it says next sync in 1 hour ago and other times syncing disabled
Fetches emails if manually synced by pulling down screen

### Steps to reproduce
1. Setup IMAP acct
2. Default settings

### Environment
K-9 Mail version: 5.403 updated on 6 Jan 2018

Android version: OxygenOS 5.0.1
Android 8.0.0
Phone: onePlus 3t
Build: A3003_28_171227

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by sbhandari-7** [comment]
It is set to “when auto-sync is turned on”.

 

Regards,

 

Sandeep Bhandari

Partner

logo

+91 99161 75844

 <mailto:sandeep@diasporesoftware.com> sandeep@diasporesoftware.com

 <http://www.diasporesoftware.com/> www.diasporesoftware.com

**Comment by aucklander** [comment]
I use tasker to enable autosync every 30mins, it does the job but i think with doze the mail gets delayed over a long period of time.

**Comment by pshem** [comment]
I have the same issue - I get out of the range of WiFi a lot, and I don't use mobile data. I expect my email to be synched when I get inside WiFi range. Instead sometimes I'll get "Synching Disabled" shown instead of "Synch in X minutes". Switching between "Synch always" and "Synch when synch is turned on" makes it work again... for some time, usually 1-2 disconnections. I think there is something in the code that blocks synchronisation after an attempt fails.

Android 7.0, K-9 mail from Play store, version 5.403(it's been happening ever since my Android got updated to 7.0, it didn't happen on 5.1.1). I have K-9 mail set to be exempt from powersaving, but it doesn't make a difference.

**Comment by cketti** [comment]
Probably Doze issues. 5.600 should work a bit better.
