### ISSUE TITLE
Cannot find copied .k9s files in Download

### ISSUE THREAD

**Issue by stanlane** [k9mail/k-9#3133]
### Expected behavior
All files with .k9s as filename extension should appear in the Download directory

### Actual behavior
I didn't find them.

### Steps to reproduce
* I exported a file named k9_settings_export_2018-01-23.k9s on a Android 4.4.2 device with K-9 Mail 5.403 ([F-Droid build](https://f-droid.org/packages/com.fsck.k9/))
* On another device with Android 4.4.4: 1) I copied k9_settings_export_2018-01-23.k9s to the download directory 2) I tried to import it with: Settings Import & Export -> Import settings. The Download directory is empty. Then I exported the (empty) K-9 Mail settings on the new device for test purpose and I found them in the Download directory via Settings Import & Export -> Import settings.

### Environment
K-9 Mail version: 5.409

Android version: 4.4.4

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Android has a database storing additional information for "downloads". Simply copying a file to the Downloads folder using a file manager isn't enough to make the file be added to that database and show up in the Downloads app. So that's an Android issue, not a bug in K-9 Mail.

You should still be able to see all files in the Downloads folder by using the "Show internal storage" option in Android's file selection screen.

**Comment by stanlane** [comment]
@cketti Do you know where I can find a URL for this Android bug? Or for Android bugs in general.

**Comment by cketti** [comment]
I don't think it's a bug. It's a design choice. They don't want you to manually write files to the Downloads folder. If you do it the "right way" (e.g. how K-9 Mail does it when exporting settings) the file will show up as expected.

To report Android bugs see https://source.android.com/setup/report-bugs

**Comment by stanlane** [comment]
@cketti Thank you for the link.

I did export the settings the right way. How do I transfer a setting file to another device then?
