### ISSUE TITLE
Feature Request: Optionally use an own contacts book (instead of the system's one)

### ISSUE THREAD

**Issue by Hocceruser** [k9mail/k-9#3184]
### Expected behavior
If K9 realizes that it does not have access to the system contacts it should create and use its own contacts book. Alternatively, there could be an option for this in the settings.

### Actual behavior

When K9 does not have access to the contacts book:
- Composing a mail: "Add from Contacts" uses the system contacts book while proposing contacts after I typed the first characters does not work at all
- Creating a new contact: it is created in the system contacts book

There are some proprietary apps that want access to my contacts. I do not want them to also know the email addresses of all my contacts, therefore I will not use the contacts book for emails.

By the way, in some countries it is illegal to give other people's email addresses to third-party companies without their permission.

### Steps to reproduce
1. Deny contacts permission for K9 or disable the contacts app
2. Do something that involves contacts (add an address to contacts or compose a mail)

### Environment
K-9 Mail version: 5.403 (F-Droid)

Android version: 6.0

Account type: IMAP

**Comment by fat-tire** [comment]
FWIW #3159 includes a realtime permissions interface for requesting access to the contacts list (and will continue to run if you deny this either initially or after the app has already run.  It does not include a separate fallback database if you deny the contacts permission however.  A question-- what happens if the user denies the contact, but then later accepts?  Would the contact books be merged somehow?

Anyway, just wanted to note this is at least partially done.

**Comment by Hocceruser** [comment]
> A question-- what happens if the user denies the contact, but then later accepts? Would the contact books be merged somehow?

Well, merging (adding all internal contacts to the system's one except if a contact with the same email address already exists there) would probably be the best option (although I do not think that there are going to be many users that do this, so it is not _that_ important).

> It does not include a separate fallback database if you deny the contacts permission however.

Actually, this was the most important point for me :-(. Privacy is the main reason for which I am using an open source email client and not having to use Android's system contacts book would greatly improve privacy.

PS: Someone has even proposed not to use Android's contacts book at all for DeltaChat, another email client: https://github.com/deltachat/deltachat-android/issues/236

Anyway, apart from this K9 is great! 👍

**Comment by fat-tire** [comment]
So I gave this a little thought-- I'm wondering if rather than re-implement a local database and contacts provider, it would make more sense tolook at the AOSP Contacts [app](https://github.com/LineageOS/android_packages_apps_Contacts) and [provider](https://github.com/LineageOS/android_packages_providers_ContactsProvider) (and [common](https://github.com/LineageOS/android_packages_apps_ContactsCommon) repo).  Either use portions of these within k9 or allow k9 to have contacts provided from a non-google source for privacy.  In other words-- rather than have k9 build in its own contacts system, the contacts in the 2nd contacts app would be kept but not synced with anything is the idea.  And maybe you'd toggle between the two.  That way you can keep your k9 contacts separated in its own app.

I'm not gonna actually implement this myself, but for anyone who wanted to pursue it, it's an idea, and there's the source.

**Comment by cketti** [comment]
We have no interest in adding contact manager functionality to K-9 Mail. However, allowing auto-completion for addresses to which the user has already sent messages is something we might add in the future. See #1006.
