### ISSUE TITLE
newer K9 version isn't retrieving new mail

### ISSUE THREAD

**Issue by eworbit** [k9mail/k-9#3209]
### Expected behavior
K9 Mail  should retrieve read and unread imap messages.

### Actual behavior
K9 Mail only retrieves imap messages in which *another* mail program has already retrieved and marked as read.   Therefor, I have to check my mailbox using anything else (webmail/Thunderbird/Outlook/etc.).  They get the new email fine.  Then K9 Mail will retrieve the newest emails but will not retrieve anymore beyond this point until, again, another mail program fetches the emails first.   This started happening sometime late 2017.

### Environment
K9 Mail version:   Should be the latest.  K9 Mail is a hard program to determine what version I'm using.  There is no About K9 Mail menu option.

Android version:
7.1.1 - There is an About Phone option.  Nice.

**Comment by cketti** [comment]
There is no setting where K-9 Mail limits itself to downloading only read messages. 
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests. Make sure to include information on how you set up your account, what email server you're using, etc.

**Comment by eworbit** [comment]
cketti,  You did not read carefully.  

I send email to my account.  K9 does not see the new email(s).   Once another mail program checks mailbox and gets the emails, then K9 can retrieve the email(s).   The server is self built sendmail server.  No other mail programs have problem.

**Comment by philipwhiuk** [comment]
You didn't fill out our issue template so it's unsurprising cketti is redirecting you to a help forum.

Sendmail is.. shockingly, used to send email.

What are you using on the server to receive it? What protocol are you using? 

As cketti said, the fact that this works for everyone else and the fact that you are using a self configured setup suggests this a configuration problem.

In fact  I suspect it's a SELECT vs EXAMINE problem.

K-9 uses EXAMINE so that the read status of new messages aren't changed. However some servers misinterpret this as not fetching new messages at all.

**Comment by eworbit** [comment]
It's an old version of http://www.washington.edu/imap/.   Perhaps all other programs use EXAMINE, and upon seeing no new email, they fall back to SELECT as a second effort.    I don't know.  K9 doesn't have to be backward compatible to everything or have legacy code in it forever to be polished. 
 
For giggles, just now, I setup Windows 10 Mail.    Even it successfully pulled in my new email which K9 can not.  Now K9 can pull in the email since it was first pulled in via another program.   Astonishing. 

I uninstalled K9 and reinstalled.   Re-setup my account - like I just did for Windows 10 Mail and still it can't see new email.    I don't know guys.  I'm just trying to report what K9 can't do.

**Comment by cketti** [comment]
See https://github.com/k9mail/k-9/issues/3022#issuecomment-355287881

**Comment by Xeeke** [comment]
A bit late to the party here but I ran into this and was able to confirm that this results from how some servers handle your system mail spool. uw-imap for instance will move your new mail from the spool (eg: /var/mail/$user) into your imap inbox the first time you issue a command against the inbox that allows writing, such as SELECT or when you mark any mail read/unread. If the app only ever uses EXAMINE to check for new mail, the imap server will never move your spooled mail over as this is a read-only command. Depending on your server setup and what sort of access you have you may be able to get around this by using a local delivery agent like procmail to kick your incoming mail into your inbox on receipt instead of waiting for an imap client to connect.

**Comment by eworbit** [comment]
yes, I use uw-imap.  I guess they removed SELECT and only use EXAMINE.  I assume they used to fallback to SELECT.   Bottom line is that K9 is the only mail program I've ever uses that doesn't *reliable* retrieve messages.  And it used to work just fine.
