### ISSUE TITLE
k9mail as default email app

### ISSUE THREAD

**Issue by taturati** [k9mail/k-9#3231]
It should be possible to set k9mail as defualt email app. However there is no way to do so. 

Setting app as default is useful for example if one wants to start it by pressing "email" button on  hardware keyboard.

K-9 Mail version:
5.403

Android version:
7.0

**Comment by philipwhiuk** [comment]
What device is this - the concept of a default email app is not a stock OS idea.

Android uses intents to decide which app to launch.

**Comment by cketti** [comment]
https://developer.android.com/reference/android/content/Intent.html#CATEGORY_APP_EMAIL

**Comment by taturati** [comment]
The device is Samsung SM-J330F.

It seems that this simple change in  k9mail/src/main/AndroidManifest.xml fixes it:

--- old/AndroidManifest.xml     2018-02-27 11:27:30.000000000 +0100
+++ new/AndroidManifest.xml     2018-03-03 00:29:35.186948000 +0100
@@ -75,6 +75,7 @@

                 <category android:name="android.intent.category.DEFAULT"/>
                 <category android:name="android.intent.category.LAUNCHER"/>
+                <category android:name="android.intent.category.APP_EMAIL"/>
             </intent-filter>
         </activity>

**Comment by dhebbeker** [comment]
Can anybody please provide more specific instructions on how to reproduce the undesired behavior and what the expected behavior would be exactly?

Also I am wondering what is the
> "email" button on hardware

I looked up the [manual][] for the SM-J330F/DS and could not find any true hardware button for e-mail in the layout. Am I missing something? Is a supplementary peripheral device attached?

In my understanding the steps to reproduce are to trigger Android to send an e-mail. For example using the contacts app and pressing on a (software) e-mail button like this: <img src="https://user-images.githubusercontent.com/1594340/53681031-bbf2b900-3ce3-11e9-82db-f79f0f0215a9.png" width=200> Or to tap on a `mailto:` link on a website for [example][]. Testing both, Android prompts me to select the app to use for this action and offers me the option to remember this decision: <img src="https://user-images.githubusercontent.com/1594340/53681102-ae89fe80-3ce4-11e9-94b0-50fceb3fbc47.png" width=200> Isn't this the common way to define default apps for specific activities? I have tested this on Android 7.0 (Nougat) - API 24 on an emulated device and on an Samsung SM-A310F and the current version of K-9 (3e1a8da32a7e2bbb55441acf6e5de26e707ac878).

[example]: https://www.rapidtables.com/web/html/mailto.html#examples
[manual]: http://org.downloadcenter.samsung.com/downloadfile/ContentsFile.aspx?CDSite=UNI_DE&CttFileID=7141106&CDCttType=UM&ModelType=N&ModelName=SM-J330F/DS&VPath=UM/201810/20181005162901467/SM-J330_UM_EU_Oreo_Eng_Rev.1.0_180823.pdf&OriginYN=N

I would like to contribute to the fix of this issue. At the moment I don't know how to verify the changes.

**Comment by stonecrusher** [comment]
> Can anybody please provide more specific instructions on how to reproduce the undesired behavior and what the expected behavior would be exactly?

Open settings --> Manage Apps --> Open menu (three dots on top right) --> Default Apps --> E-Mail

Here K9-Mail should be offered as choice. Instead, only GMail is offered and selected by default.

Android version 9 PKQ1.181021.001 on a Xiaomi Redmi 7
K9-Mail 5.600 both via PlayStore and F-Droid

**Comment by KlausH** [comment]
Same on SM-T830 Samsung Tab S4 with Android 9. No way to set K9Mail as default email app.
e.g. useful for starting the email app with the email key from the bluetooth keyboard.

**Comment by dhebbeker** [comment]
> > Can anybody please provide more specific instructions on how to reproduce the undesired behavior and what the expected behavior would be exactly?
> 
> Open settings --> Manage Apps --> Open menu (three dots on top right) --> Default Apps --> E-Mail
> 
> Here K9-Mail should be offered as choice. Instead, only GMail is offered and selected by default.

With most Android configurations I have available the breadcrumbs are Settings → Apps & notifications → Default apps. This then looks like this:

- Samsung Galaxy SM-A310F Android 7.0: <img src="https://user-images.githubusercontent.com/1594340/72746872-84b72000-3bb3-11ea-91a1-2d5aac2e08a8.png" width=300>
- Pixel 2 Android 10.0 <img src="https://user-images.githubusercontent.com/1594340/72746661-f3e04480-3bb2-11ea-8912-614c5875a9bd.png" width=300>
- Sony Xperia XZ1 Compact Android 9 <img src="https://user-images.githubusercontent.com/1594340/72747092-00b16800-3bb4-11ea-8a91-550e4359e625.png" width=300>
- Lenovo Tab P10 Android 8.1.0 (no screenshot)
- Motorola XT1794 (no screenshot)

Note: The screenshots above were taken after installing a version of K-9 mail including 3a95316c670a35f45039bd7ba8002833c3063b61 rebased to current master.

As you can see those configurations have no default e-mail app setting. Maybe it is only available with OEM-customized Androids? Or do you mean something different? Does it look different on your device?

**Comment by stonecrusher** [comment]
Unfortunately I can only test it in about three months (it was my father's phone).
However thanks for working on this!
