### ISSUE TITLE
Encrypted credentials

### ISSUE THREAD

**Issue by csabavirag** [k9mail/k-9#3318]
### Expected behavior
Is it possible to encrypt the account password with RSA keypair to improve the security of the used credentials? The KeyStore is protected by screen lock code, so if somebody removed the lock code, the keypair would get destroyed. 

### Actual behavior
Currently the account details are stored in plain text on the Android filesystem which might be vulnerable when the device is lost or compromised.

### Environment
K-9 Mail version: Any
Android version: 4.3+
Account type (IMAP, POP3, WebDAV/Exchange): Any, preferably IMAP

**Comment by cketti** [comment]
Possible, yes. But potentially very annoying. See https://doridori.github.io/android-security-the-forgetful-keystore/

My recommendation is to use full device encryption.

**Comment by Valodim** [comment]
Actually, 1) this has been fine for more recent versions of android, and 2) worst case we'll have to ask for the password again. I don't think this should be particularly high on our list of priorities, but if someone made a PR I wouldn't reject it on principle.

**Comment by kramprabhu** [comment]
Hi Cketti.
I would like to add password encryption and password prompt (if got erased) enhancement. Would like to which branch I need to fork out?

**Comment by cketti** [comment]
@kramprabhu: `master` is our development branch. New features go there.

**Comment by GNUDimarik** [comment]
@Valodim @cketti on some projects we use locksceen at start of the app and pin code as encryption key for sqlcipher.
Please let me know if that's acceptable here.

**Comment by cketti** [comment]
@GNUDimarik: You're suggesting what amounts to an app-specific lock screen. See issue #753 for that.

**Comment by Kein** [comment]
> My recommendation is to use full device encryption.

Full device encryption is not very reliant on Android unlike IPhone, we have almost 15 years of history which both proves and showcases this moment. Moreover, people who dont use device encryption (read: ALL unlocked and rooted devices, because in 99% if your deice is unlocked or rooted - FDE is absolutely useless)

There is plenty of advantages, double-layer of encryption is just low-hanging surface fruit. The only disadvantage is that someone has to implement it.

**Comment by cketti** [comment]
> Full device encryption is not very reliant on Android unlike IPhone, we have almost 15 years of history which both proves and showcases this moment.

If you make statements like this, you should back them up with evidence. Otherwise I'll just assume you're spreading FUD.

> Moreover, people who dont use device encryption (read: ALL unlocked and rooted devices, because in 99% if your deice is unlocked or rooted - FDE is absolutely useless)

This makes it sound like you don't understand what service full-disk encryption provides. When using FDE data stored on the device is encrypted using a key that is protected by a user secret (e.g. a password). Without that secret the data can't be decrypted. 
So if someone grabs your device while it is powered off, they are missing that secret and can't decrypt the data. If your bootloader is unlocked, an attacker can run arbitrary code on your device. But they're still missing the secret and thus your data remains protected.

For more information about the encryption used by Android see https://source.android.com/security/encryption

Side note: Newer devices should support re-locking after installing a custom ROM. See https://source.android.com/security/verifiedboot/device-state#user-settable-root-of-trust
