### ISSUE TITLE
Synch AND Notification not working on ONE account, but is on the other

### ISSUE THREAD

**Issue by Click2Grow** [k9mail/k-9#3326]
### Expected behavior
I've read issue #3167 and tried the battery optimization and other suggestions. I expected that the mail app will synch at the interval set and provide a notification in the menu bar when new mail arrives. 

### Actual behavior
On one of my two accounts it randomly shows synching disabled so I have to swipe down to get it to load. But whether it synchs by itself or I manually download the messages I do not get a notification in the menu bar at the top. This is for the default account. My second account also randomly shows synching disabled, but the notifications DO appear in the menu bar. My default/primary account is more important and essential for my job. I have missed so many emails because I get busy and don't pull out my phone to manually check to see if there are emails. My phone connects to my smart watch so I get the notifications for the second account, but I need the primary account notifications. 

### Environment
K-9 Mail version: 5.403

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by Cindy62707** [comment]
Did you find a solution to this problem?  I have the same issue and have tried all the suggestions everyone has mentioned but one account will not sync.

**Comment by Click2Grow** [comment]
@Cindy62707. I had to delete the primary account and set it back up again. I'm not sure why it worked this time, but I receive all notifications now.

**Comment by Cindy62707** [comment]
That was one of the things I tried.  I've been dealing with this so long I'm tired of it.  Reporting it until I'm blue in the face and the developers don't seem to care.  Testing Aqua Mail this week and I'm loving getting my new emails almost immediately when they hit the ISP site.  And I can delete emails and not have the program crash 99 % of the time.  Will probably delete K9 soon since they aren't doing anything to fix the issue.  Hate to do that but the problems have been going on for several months now without a response from the developers on what is causing the problem and why they can't solve it.
