### ISSUE TITLE
K-9 answers not to the original from-address

### ISSUE THREAD

**Issue by eugomat** [k9mail/k-9#3327]
The issue occurs on a mail which was sent to multiple recipients.
There is no 'Reply-to' tag in the mail header.
'From' and 'To' lines in the original mail are like this (in this order).

```
From: =?UTF-8?Q?Name_contains_an_=c3=bc?=
 <info@somemailbox.somedomain>
To: mailinglist1@mailman.somedomain, mailinglist2@mailman.somedomain,
        mailinglist3@mailman.somedomain
```

The sender name has non-latin characters.

### Expected behavior
The new message should be addressed to the email address in the 'from' field of the original mail header.

### Actual behavior
The new message is addressed to the first email address in the 'to' field of the original mail header.

### Steps to reproduce
1. Find an email matching the criteria above and open it.
2. Tap on 'answer' (not 'answer all')

### Environment
K-9 Mail version: 5.403

Android version: 7.1.1

Account type: IMAP

**Comment by cketti** [comment]
I created a test message with the exact header lines you provided and everything works as expected. The 'to' field of the reply was populated with `info@somemailbox.somedomain` (including the properly decoded display name).

But since the recipients are mailing lists chances are the email also contains a `List-Post` header line. In that case the lists address is used for replies. See #2588.

**Comment by eugomat** [comment]
Actually I had no idea what the trigger for this behaviour of K-9 is. But 'List-post' seems to be the right answer to this question. The reason I couldn't find the thread #2588 before creating this one is probably the topic that is chosen a way too specific. :)

This issue can therefore be closed.

**Comment by eugomat** [comment]
thanks to cketti
