### ISSUE TITLE
Yahoo IMAP fails login.

### ISSUE THREAD

**Issue by cobaltdr** [k9mail/k-9#3382]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

I have seen issue #1698 and #2653, #1742, but they're not quite the same.

### Expected behavior
Correct Yahoo username and password entered in IMAP fetching credentials should allow K9 to connect and fetch mail.

### Actual behavior
Randomly over the past week, (without changing any settings) I get an authentication failed when attempting to fetch new mail from Yahoo mail. This behaviour continues _until_ I log on to the web interface. Without doing anything else, if I then if I click in K9 mail again, it goes through fine. When it connects, using either imap.mail.yahoo.com or android.imap.mail.yahoo.com works.

### Steps to reproduce
1. It occurs randomly, but usually within 12h of having last logged into the webmail service; this seems to have started over the past week.

Less secure login is enabled in Yahoo Mail settings on their website.

### Environment
K-9 Mail version: 5.403.

Android version: 5.0.2 (appreciate this is rather old, but my phone manufacturer has not released updates).

Account type (IMAP, POP3, WebDAV/Exchange): Yahoo IMAP.

**Comment by cketti** [comment]
Sounds like a Yahoo issue rather than a bug in K-9 Mail.

**Comment by chroche77** [comment]
Hello, 

The same has been happing to me for about 2 weeks : each IMAP connection attemp by K9 to Yahoo mail, be it with either imap.mail.yahoo.com or android.imap.mail.yahoo.com, always fail, while it was working like a charm previously. 

But I am not sure this is a Yahoo issue since with another client app (Gmail in my case), it is working. 

Thank you very much in advance for your help. 

Kind regards,

**Comment by yourxlncy** [comment]
I'm having the same problem. I have three yahoo email addresses. One of them will not authenticate the last couple of days and worked perfectly up until then. The other two work perfectly. I have checked and rechecked the spelling and accuracy of the entries. I have deleted the account in K9  and re-added it. I restarted my phone(Samsung S20+ 5G). I even unstalled and reinstalled K9. The problem remains. Two of them work perfectly. The problem one gives an "Authentication error" every time and doesn't work. Please help me.

**Comment by crazyrexz** [comment]
face the issues, cannot connect to host popped up, any fix?

**Comment by falket** [comment]
I have configured k9mail for yahoo usage at the end of december 2020 on a phone and an year ago for another, everything was fine using imap. now i get too authentication failed. With thunderbird from pc it works. k9 version 5.600

**Comment by Akroma85** [comment]
I have had the same issue for a week. Authentication failed although k9mail was working for months before that. Thunderbird from a PC worked fine.
The problem is on yahoo server side, it's not allowing you to connect through "unsecure" applications. You will have to login to your yahoo mail account through a web browser, go to [account > security panel](https://login.yahoo.com/account/security). There you can generate a ["one time app password"](https://login.yahoo.com/account/security/app-passwords/list). After generating your password, simply use the one time password as you account parameters in k9mail.

**Comment by falket** [comment]
> I have had the same issue for a week. Authentication failed although k9mail was working for months before that. Thunderbird from a PC worked fine.
> The problem is on yahoo server side, it's not allowing you to connect through "unsecure" applications. You will have to login to your yahoo mail account through a web browser, go to [account > security panel](https://login.yahoo.com/account/security). There you can generate a ["one time app password"](https://login.yahoo.com/account/security/app-passwords/list). After generating your password, simply use the one time password as you account parameters in k9mail.

solved, a big thank you!
