### ISSUE TITLE
Add reply-to-header again if reply-to-header was set

### ISSUE THREAD

**Issue by dex2000** [k9mail/k-9#3386]
Got a Mail on me@example.com with reply-to-header to reply@example.com
### Expected behavior

reply to this mail will send to 
1. reply@example.com
2. should set the old reply-to-header (reply@example.com) for reply as new again.
### Actual behavior
reply-to-header isnt set, have to add it manually

**Comment by cketti** [comment]
Why would you expect the Reply-To header from the source message be added to the composed message?

Maybe relevant: #3738

**Comment by dex2000** [comment]
@cketti its the behavior for example in Thunderbird. If reply-to is set the reply goes "back" to the reply-to-adress with the reply-to-header.

If i get a reply-to the sender has a plan. The sender wants to communicate with the reply-to adress and not his or my own.

simple example:
i send a mail on an adress which redirects to 10 mail-accounts
10 mail-accounts are using k9, and all answers correct back to the reply-to-adress.
But: in the answer is the "old" reply-to not set, 5 people check this (maybe) and re-set reply-to manually and 5 other people send a mail to a "single" adress.

**Comment by cketti** [comment]
Maybe I misunderstand. But it sounds like you want to use a mailing list software rather than trying to emulate the functionality on the client side.

Here's how `Reply-To` works:
When you reply to a message that contains a `Reply-To` header, the address from the `Reply-To` header is used as `To` address. The `From` address and `Reply-To` address are set depending on which identity you have selected in K-9 Mail to send the message. By default the `Reply-To` field of new identities (and the default identity) is empty. And so the reply won't contain a `Reply-To` header.
