### ISSUE TITLE
[enhancement] please enable installation to SD card

### ISSUE THREAD

**Issue by leggewie** [k9mail/k-9#3539]
I'd certainly welcome if you enabled this app to be installed to an SD card instead of the limited internal flash memory.  Please have a look at https://developer.android.com/guide/topics/data/install-location.  I don't see a reason why your app can't be installed on the SD memory. Thank you for your consideration.

**Comment by cketti** [comment]
See [Applications that should NOT install on external storage](https://developer.android.com/guide/topics/data/install-location#ShouldNot). K-9 Mail uses quite a few of those features.

It's unfortunate that adoptable storage seems to reuse `android:installLocation` instead of introducing a new attribute. Compared to apps-on-SD-card (API 8+) adoptable storage is actually useful because it allows storing app-private data on external storage. I guess we'll set `android:installLocation="auto"` and hope nobody with Android versions prior to 6.0 will move the app to external storage without knowing what this entails.

See also #1187
