### ISSUE TITLE
Huge battery drain on OnePlus 5

### ISSUE THREAD

**Issue by coldpatrix** [k9mail/k-9#3567]
In the last 4-7 days, the app is using a huge percentahe of battery.

### Expected behavior
The percentage of battery usage has to be less than 2-3%

### Actual behavior
The percentage of battery usage goes up to more than 5%

### Environment
K-9 Mail version:
5.403

Android version:
8.1.0

Account type (IMAP, POP3, WebDAV/Exchange):
three IMAP accounts

**Comment by mypiandme** [comment]
I second that. I get 26% battery usage.
Phone: Pixel2
Android 9
2 IMAP accounts with Push/Imap Idle

![screenshot_20180824-150827](https://user-images.githubusercontent.com/5851721/44586477-0f71d080-a7b0-11e8-9a87-3e2678184ad3.png)

**Comment by gerritnottorf** [comment]
Same here, Motorola Moto X4

**Expected behavior**
The percentage of battery usage has to be less than 2-3%

**Actual behavior**
K9 mail consumes more than 50% 

**Environment**
K-9 Mail version:
5.600

**Android version**
8.0.0

Account type (IMAP, POP3, WebDAV/Exchange):
One IMAP account, sync time set to one hour. Tried both battery optimization on and off, makes no difference.

**Comment by elem089** [comment]
Same here on Sony Xperia X1c: lost approx. 40% within 3 hours after installing / configuring K-9. Meanwhile I disabled / froze K-9 using Titanium. Since then battery consumption is back to normal

Environment
K-9 Mail version:
5.600

Android version
7.1.2 root / LineageOS 14.1

Account type (IMAP, POP3, WebDAV/Exchange):
3 IMAP accounts, sync time for each is set to one hour, no push mail

**Comment by cketti** [comment]
Without more information we can't fix this. 

Please record a debug log and create a new issue. See https://github.com/k9mail/k-9/wiki/LoggingErrors
