### ISSUE TITLE
[Feature Request] - Disable/enable sync for one a account

### ISSUE THREAD

**Issue by raychinov** [k9mail/k-9#3594]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Disable mail sync for one account (e.g. work mail during the weekend), but keep syncing the other one (personal). Is also will be nice if this is done with a widget or easier menu option 

### Actual behavior
Sync is done for all of none

### Steps to reproduce
Settings > Network > Background sync > (Always / Never / When 'Auto-sync' is checked)

### Environment
K-9 Mail version:
5.403

Android version:
7.1.1

Account type (IMAP, POP3, WebDAV/Exchange):
All

**Comment by Avispa** [comment]
I guess I have the same or at least similar request even though my intention is different.

### Expected behaviour
Disable one or more specific account(s) from synchronising or disable account somehow at all (to keep mails locally of an expired/suspended account as some kind of archive).

Could imagine to get those disabled accounts moved (opt. A) visual separated to the bottom of the list of accounts or (opt. B) into an extra tab.

### Actual behaviour
K-9 Mail tries to sync every $whatever minutes and drops an error about failed authentication at the server.

### Environment
K-9 Mail 5.403
Andoid 5.0
Account type IMAP (in my case)

**Comment by cketti** [comment]
You can set 'Account settings > Fetching mail > Folder poll frequency' to 'Never'

**Comment by Avispa** [comment]
@cketti Sure I can do that but it doesn't solve the issue nor it is related to the presented problem. It still tries to sync the account and fails. Actually I have it set to _never_  already.

To be clear: this is _no_ solution.

**Comment by eMPee584** [comment]
Yes, this is not a solution. I continuously get an **Authentication failed** notification because my account is currently locked on the server (organisational migration).. and no way of completely disabling  sync for this account without deleting it. Folder Poll Frequency = Never does not prevent connection attempts.. So I can choose between losing my mail or getting blacklisted for repeated unsuccessful logins, ouch :face_with_head_bandage:
