### ISSUE TITLE
Since version 5.6, in some emails From appears with 'null' as text

### ISSUE THREAD

**Issue by JavierDiaz** [k9mail/k-9#3617]
### Expected behavior
Until version 5.6, From field of emails was viewed correctly

### Actual behavior
Now, in some cases, instead appearing the value of From field, it appears as 'null'. If you choose to show all headers, From field exists and is viewed correctly. It seems there is some issue with emails with some encoding error.

It is desired instead 'null', appears the actual From header.

### Steps to reproduce
1. Open an email with a From header with some problematic character, for example:
From: FÁTIMA  <xxx@xx.es>

### Environment
K-9 Mail version: 5.600

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by spencersun** [comment]
I think this may be related: since upgrading to 5.600 emails from Yahoo Groups mailing lists no longer display the sender's name, and instead show the list name which is not very helpful in the message summary list.

The From: header on Yahoo Groups emails has the general pattern of

From: "First name Lastname addr@example.com [listname]" <listname@yahoogroups.com>

**Comment by cketti** [comment]
I believe this is fixed in `master`.

**Comment by JavierDiaz** [comment]
hello, in version 5.6 is not working. which version is master?
i'm using android and i think 5.6 is the newest version available
