### ISSUE TITLE
Support Firefox Webview

### ISSUE THREAD

**Issue by Zazie-Lavender** [k9mail/k-9#3625]
### Expected behavior
K9Mail renders messages.

### Actual behavior
Message bodies are not rendered or displayed; no error message emitted that explains this problem to the user

### Steps to reproduce
Uninstall / Disable Chrome (Must be preinstalled, and No Android System Webview preinstalled)
Have Firefox for Android installed and configured to allow itself to be called by other applications

### Environment
K-9 Mail version: 5.403

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): GMail / IMAP

**Comment by cketti** [comment]
As far as I can tell Firefox doesn't provide a `WebView` implementation. What exactly are you proposing?

**Comment by nuntius35** [comment]
There is [GeckoView](https://wiki.mozilla.org/Mobile/GeckoView), but that's currently not an option for productive systems (and maybe never will).

I also think, that the bug has the wrong headline. People who have no webview on their device, might worry about the fact that untrusted input is sent to an html renderer. The expected behaviour from the bug description could be achieved, if K-9 displays the content of the mail as plain text without webview. (Maybe implement  issue #906 without webview.)
