### ISSUE TITLE
Add otion to place menu bar

### ISSUE THREAD

**Issue by coogor** [k9mail/k-9#3724]
I noticed that the menu bar, containing <>, Trash folder, new-mail icon etc is located on the bottom of the screen for smartphones, while at the top of the screen for tablets. This is quite uncomfortable, as the 'back' button on the tablet is at the bottom  of the screen as well. So you are moving your hand from bottom to top and vice versa constantly.

Expected behaviour: Have menu bar constantly on the bottom of screen, or have this configurable (all options I tried do not give the desired result....)
K-9 Version: 5.600
Android: 7 & 8
Devices: Samsung Galaxy S7 Edge, Tab-A

**Comment by cketti** [comment]
Making this configurable is quite a bit of work. And once implemented it's one of those things that make maintenance hard. So we'd like to avoid adding these kinds of features.

We will probably get rid of the `<` and ´>` actions and instead allow swiping left and right to move to the next/previous message. See #585.

On a tablet you could enable split mode: Global settings > Display > Show split-screen
That will display the message list next to the message view and you won't have to use the back button to get from a message to the list.

**Comment by coogor** [comment]
@cketti, thanks for your explanations.
First question is WHY are Tablet and Smartphone implemented different. Reducing this to one standard, e.g. menu bar at bottom, should already reduce complexity.
Swiping looks, good, but is already some years in the pipeline....

**Comment by cketti** [comment]
We use a flag that tells the Android framework to show actions using a "split action bar" on narrow screens. There's no extra work involved for us as app authors.

For phones this means action buttons move from the bottom to the top when switching from portrait to landscape orientation. This is a source of great confusion to some users. Which is why we will get rid of this in the next major version. Actions will always be at the top.

**Comment by coogor** [comment]
> Actions will always be at the top.
Considering the fact that Task Manager, Home- and back button are at the bottom of Android Smartphones, this seems not to be the most ergonomic decision....

**Comment by homlett** [comment]
> Which is why we will get rid of this in the next major version. Actions will always be at the top.

Oh gosh, please don't! Action buttons at the top are terrible. I would really like to be able to have these buttons at the bottom all the time, including tablet view.

**Comment by aherz81** [comment]
Hi, i have a related Problem. I am on Android 9 and k9 5.600. In the Android system settings I can change the size of items (display-extended-display size). When switching from default to small, k9 starts to treat my Nokia 8 like a tablet and moves the actions to the top (always, not just when I turn out to the side). That Alone is very annoying, but since the device is to narrow to display all the action buttons (no matter if held horizontally or vertically) and action buttons that overflow the screen are not accessible in any way, it becomes impossible to reply to an open mail, I have to go back to the list of mails am long click the mail in offer to access the reply button. 
This seems to be a bug to me. 
It would be a nice fix, if I as a user, could overwrite the flag that you use to determine if you split the actions into top and bottom or not (so I want to overwrite what ever heuristic you are using to determine this flag). Shouldn't be much effort. 
Thx for all the great work in k9. 
Alex

**Comment by ZX-SPECTRUM128** [comment]
Yes I agree cannot we have  a choice between one action bar or two
I need the action bar at the bottom in landscape mode

**Comment by chadszinow** [comment]
Got the K9 upgrade looking for a way to put the actions bar back to the bottom.
On a big smart phone it's a terrible user experience when using one handed. Holding the phone at the bottom it is near impossible to hold it and get your thumb to the top.
