### ISSUE TITLE
Very slow until mail is displayed

### ISSUE THREAD

**Issue by coogor** [k9mail/k-9#3725]
When opening a mail, it partly takes 10 seconds until the payload (mail content) is displayed. This happens more with HTML mails, but as well with text-only mails

### Steps to reproduce
1. Opem mail account
2. Display mail
3.

### Environment
K-9 Mail version: 5.600

Android version: 7 & 8, Samsung Galaxy S7, Galaxy Tab A

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
We do have plans to optimize the way K-9 Mail is loading messages. But most of the slowness is probably due to the `WebView` component we're using to display messages. Replacing it is not something we're currently considering. Chances are another browser engine won't be much faster. And writing an own engine that only supports the subset of features we need is a project that is bigger than writing an email app. So we're probably not doing that either.
