### ISSUE TITLE
In Folders, when click the back button, the app exit.

### ISSUE THREAD

**Issue by suyeon-9706** [k9mail/k-9#3828]
### Expected behavior
When click the Back button in 'Folders', want to return to Inbox, which is the previous page.

### Actual behavior
When click the Back button in 'Folders', the app exit

### Steps to reproduce
1. Move Inbox
2. Pressing the 'Folder' button in the upper right corner
3. In Folders, when press the back button, the app exit.

### Environment
K-9 Mail version: 5.600

Android version: 8.0.0

Account type (IMAP, POP3, ##WebDAV/Exchange):

**Comment by philipwhiuk** [comment]
It's not really a back button. It's an 'up' button. If you only have one account there's nothing 'Up' from Folders.

**Comment by cketti** [comment]
"Up" (the button in the upper left corner) will always go to the Accounts activity. Pressing the device's back button will do different things depending on how you got to the screen. This doesn't make for a great user experience. But since we're changing the UI for 5.800 this will no longer be an issue.
