### ISSUE TITLE
Simple color picker

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#3904]
For the account color I want us to switch to a simpler color picker. It should only offer a limited set of colors that work well in the app.

Recent changes to the app have proven that supporting a large range of colors make things unnecessarily difficult.

**Comment by danbruegge** [comment]
Providing a good set of default color would be fine. But can you also provide a field for hex values? Maybe hidden for powerusers or something.

I have mail accounts from companies i work for, which have a brand color. It would be nice to use the brand color hex values from the company to better visualize the accounts.

**Comment by newhinton** [comment]
@cketti Would it be an option to provide both?
We default to like 8 or 10 standard colors. 
In the settings, we allow the user to switch to the more advanced holopicker, which could also allow for hex values.

(I have multiple accounts which belong together, and i'd like to group them together by very similar colors, that wouldn't work with "only" 8 colors)

Since you added the label "help wanted" if we can get a more granular control in there somehow, i'd develop that :)

**Comment by newhinton** [comment]
Also regarding my last comment, you mentioned that a wide range of colors are difficult to maintain, could you explain why that is and what i need to take care of when i develop this?

**Comment by cketti** [comment]
No, I don't want to add an option to provide your own colors. This feature is not nearly important enough to warrant the complexity.

If you absolutely have to, you can export your account settings, modify the account color in the settings file and then import those settings. This is completely unsupported and may break at any moment. Also, if this leads to display issues, you're on your own.

**Comment by newhinton** [comment]
it doesnt need to be complex at all, one way would be to expand the holopickerfragment to have some sort of tabbing, with one tab showing a list if provided colors (the default colors provided by k9)
and a second tab with the advanced picker.

that would only require changes to the holopicker, and not k9 itself.

since the toggle or whatever we want to call it would all be inside the library, and k9 would only need to increase/change the version of the holopicker, and doesn't need to be changed further

**Comment by ByteHamster** [comment]
If there is a button that allows users to set the account color to white, they will do that. Then they will complain that they can't read anything. It's trivial to support selecting all colors but to make the app look good with *every* color is hard. That's why only a specific number of colors (that work well) should be included.

**Comment by danbruegge** [comment]
@newhinton - my expectation for k9mail users is that they know what they are doing. Users that select white and complain about it are users that don't usually install k9mail, i guess.

**Comment by newhinton** [comment]
@ByteHamster @danbruegge Also even if we disregard that the user does not now what he does, in the worst case a color should look bad, and i think the usage of color in k9 is only uses in places where it would not influence the important parts of the mailclient. I dont think that providing a set of defaults is a bad idea, and i even support making it the default, but i don't think we should take away customizablitiy completely, and there are some good ideas that would combine the best of the two worlds

**Comment by ByteHamster** [comment]
> the usage of color in k9 is only uses in places where it would not influence the important parts of the mailclient

The design overhaul will most likely use colors in more places

**Comment by newhinton** [comment]
@ByteHamster I was refering to the overhaul ;)
But again, custom should not be the default, but an addition ;) there are many great examples on how to do this

**Comment by newhinton** [comment]
We wouldn't even need to develop this, there are alread libraries for our exact usecase:

https://github.com/jaredrummler/ColorPicker/blob/master/README.md

**Comment by toast** [comment]
I tried setting an 'Account color' to see what effect it has. I didn't realise that there is no way to undo this. Now I cannot get back to the comfortable muted grey that I had originally - only choose from a set of eye watering hues.

I think there is a clear case from a user experience perspective to be made for allowing people to set custom colours; they know what's best for their own needs (and have [good reasoning](https://github.com/k9mail/k-9/issues/3904#issuecomment-460921298)). If they can play around and undo their choices they'll pick something meaningful to them; it's an empowering and delightful feature of K-9.

@newhinton 's [proposed design](https://github.com/k9mail/k-9/issues/3904#issuecomment-461114392) seems like a good compromise as it allows K-9 to suggest a small set of sensible default colours for less adventurous users. And it still allows people the freedom to choose a better colour if they know that these simple defaults are not right for them.

**Comment by phpAddict83** [comment]
Hello,

As a long time K9 user, I just wanted to provide a user's perspective. I just ran into the issue of selecting my account colors and not too pleased with the lack of darkening a color. If you're concerned that some less savvy users may choose too light of a color when using the light theme, or too dark of a color when using the dark theme, just make it so the color option can't be too dark or too bright, problem solved. Sum the three hex values and if they're outside of a range, like 150 - 690, either don't allow it or warn the user. At the very least offer an "advanced colors" option that less savvy users would have a hard time to enable.

**Comment by ikcalB** [comment]
Too I'd like to vote for more freedom.

I'd like white i.e. (cause the standard webmail theme for that service is mainly.... white!)

AFAIK the accout color is only used for aesthetic purposes, ANY color should be selectable.
(for other color options a warning should be considered)

**Comment by cketti** [comment]
This change was implemented via #4275.
