### ISSUE TITLE
Can't download current builds

### ISSUE THREAD

**Issue by mruwek** [k9mail/k-9#3940]
### Expected behavior
It would be nice to have an opportunity to download and test current builds.

### Actual behavior
"Build status" from README.md redirects to notice that DEV@Cloud (Cloudbees) reached the "end of life" status.

**Comment by gene-git** [comment]
That  would be terrific  - also wondering if you're getting close to a 5.700 beta release too. My app is on the beta channel but  it too hasn't updated since 5.600 last fall. 
 Really looking forward to trying out the material design changes. Thank you for all the work you guys do and also for your leadership participation in openpgp.

**Comment by wiktor-k** [comment]
> It would be nice to have an opportunity to download and test current builds.

Yep, that'd be a really good idea. `master` build is surprisingly stable, I'm using it daily for months and did not see any major problems.

**Comment by cketti** [comment]
I don't want end users without development experience testing development builds.
