### ISSUE TITLE
PEP vs Autocrypt  - question

### ISSUE THREAD

**Issue by gene-git** [k9mail/k-9#3941]
PEP removes many of the control/options vs Autocrypt.

I am aware that PEP is the default for new users.
Is this because PEP is 'simpler' or because PEP is winning the battle over Autocrypt?

If PEP is the preferred way forward, can we expect the "advanced" options available for Autocrypt to become available in PEP mode too?

thank you!

**Comment by wiktor-k** [comment]
K-9 doesn't implement pEp as far as I know. Maybe you meant to report this issue to https://play.google.com/store/apps/details?id=security.pEp ?

**Comment by gene-git** [comment]
Geez i'm silly - yes wrong list - so sorry ... actually was meant for enigmail.

**Comment by Valodim** [comment]
Actually, this sounds like a question for Enigmail rather? I believe PEP is no longer the default mode in Enigmail due to technical issues, but maybe that's only in an upcoming release.

Either way, K-9 Mail does not implement PEP, among other reasons because there is no specification that could be implemented, and including their "engine" as a black box is not an option for us.

**Comment by gene-git** [comment]
Good to know, thank you and hopefully enigmail will stick with Autocrypt as well - I have a strong preference for Autocrypt approach over PEP.  Apologies again for noise.
