### ISSUE TITLE
High battery usage since upgrade to Android 9 Pie

### ISSUE THREAD

**Issue by King555** [k9mail/k-9#3968]
I use K-9 Mail on a Samsung Galaxy S8+. I upgraded from Android 8 to Android 9 a few weeks ago.

### Expected behavior
In Android 8 I had a background battery usage of the K-9 Mail app of under 5% in 24 hours. I would expect the same value in Android 9, if not a lower value (because I've read that version 9 has more energy optimization features for longer battery life).

### Actual behavior
In Android 9 I have a background battery usage of 30% in 24 hours (only the mail K-9 Mail app).

### Steps to reproduce
I just have the app installed with 7 IMAP accounts, all set to push mode. I actually open the app only a few times a day for seconds or a few minutes.

### Environment
K-9 Mail version: 5.600
Android version: 9 (with Samsung One UI 1.0)
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
The next K-9 Mail version will contain some changes we hope will improve power efficiency.

Diagnosing power issues remotely is hard. And this issue doesn't contain any information that would allow us to start anyway. So closing this.

**Comment by schlueter-de** [comment]
Hi,
i know its closed  but i can still comment on this. Since the last Update on my Pixel 3 i see alot of powerdrain on the k9 mail app. its always nr 1 on the list. Today it was 35% with 2 min aktive time in the app. I would show u my screens but i cant submit any files.

This is alot and its only in the backround. I'm using k9 with just one account with push otification.

Pixel 3 Android 9 Update 04.05.19
K9 Mail 5.600
No battery optimization on k9 mail app

I would love to help but dont know what information u coule use.

schlueter

**Comment by King555** [comment]
@schlueter-de 
Is the higher battery usage on your phone since the upgrade to Android 9 or since an update within version 9?

**Comment by MartinX3** [comment]
Xperia XZ2 with kernel 4.9 and omnirom 9.0 from 22. April 2019 here.
Thousands of wakelocks according to better battery stats.

**Comment by MartinX3** [comment]
@cketti 
Sadly, since we don't know any hint of the release plans of the new version with better battery live,
https://github.com/k9mail/k-9/issues/3968#issuecomment-474900159
(even no changelog of unstable releases or a 5.7xx development release to test -> I mean there are 860 commits since the last stable version), I go and try the p≡p email app.
It is also open source and supports GPG.
https://play.google.com/store/apps/details?id=security.pEp

The K9 mail app floods my device with wakelocks.
19% battery loss after over 8h night with WiFi and RIL
0.5% battery loss after over 8h night with plane mode

Maybe the added logs from the bug report and the "better battery stats" are helping you. :)

[BetterBatteryStats-2019-05-16_105618556.txt](https://github.com/k9mail/k-9/files/3186207/BetterBatteryStats-2019-05-16_105618556.txt)
[dmesg-2019-05-16_105619224.txt](https://github.com/k9mail/k-9/files/3186208/dmesg-2019-05-16_105619224.txt)
[logcat-2019-05-16_105619102.txt](https://github.com/k9mail/k-9/files/3186209/logcat-2019-05-16_105619102.txt)
[bugreport0.zip](https://github.com/k9mail/k-9/files/3186247/bugreport0.zip)

PS:
Except the battery drain which leads me to charge my device 1.5x - 2.0x times each day, I love K9 :)

**Comment by itpp16** [comment]
Workaround: the app needs to be stopped, select K9 from the app list and hit the stop button (ignore the warning), touch the k9 icon to start it. A reboot or shutdown/start of android does not do this, you need to manually stop the app. Any battery drain by K9 should stop.
