### ISSUE TITLE
k-9 tries to decrypt using sender's gpg key in mails sent from thunderbird

### ISSUE THREAD

**Issue by einalex** [k9mail/k-9#4002]
### Expected behavior
k-9 should look for recepient's key and try to decrypt mail using that.

### Actual behavior
k-9 looks for sender's key and fails decryption due to sender's private key not being present.

### Steps to reproduce
1. Setup enigmail as per the screenshots ![tb1](https://user-images.githubusercontent.com/5766095/55407877-cad4c180-5556-11e9-8b19-65f8ca85aeb3.png) ![tb2](https://user-images.githubusercontent.com/5766095/55407878-cad4c180-5556-11e9-8652-597812083de3.png) ![tb3](https://user-images.githubusercontent.com/5766095/55407879-cad4c180-5556-11e9-9244-fbb9b2a851d8.png)
2. send mail
3. suffer

### Environment
K-9 Mail version: 5.600

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): imap

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

Raw mail (redacted keys and addresses):
-----------------------------------------------------------
Return-Path: <sender@example.com>
Delivered-To: recipient@example.com
Received: by example.com (Postfix, from userid 116)
	id 7E9FC40213; Tue,  2 Apr 2019 15:15:06 +0200 (CEST)

Received: [...]
To: recipient <recipient@example.com>
From: sender <sender@example.com>
Openpgp: preference=signencrypt
Autocrypt: addr=sender@example.com; prefer-encrypt=mutual;
 keydata= [..]
Date: Tue, 2 Apr 2019 15:15:00 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101
 Thunderbird/60.5.1
MIME-Version: 1.0
Subject: ...
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="kYQKZKJbJhnV1UVWPlqOaIMjRpvWDl17u"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--kYQKZKJbJhnV1UVWPlqOaIMjRpvWDl17u
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--kYQKZKJbJhnV1UVWPlqOaIMjRpvWDl17u
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----

[..]
-----END PGP MESSAGE-----

--kYQKZKJbJhnV1UVWPlqOaIMjRpvWDl17u--

**Comment by d-g** [comment]
einalex wrote:
> ### Expected behavior
> k-9 should look for recepient's key and try to decrypt mail using that.

No, that’s not an expected behaviour for a GPG-compatible software.  It should try to decrypt a piece of info by all possible means, including trying all available keys.

> ### Actual behavior
> k-9 looks for sender's key and fails decryption due to sender's private key not being present.

I did not study it, yet I was under impression, that no, K-9 does the sane thing by just passing ciphertext to OpenKeychain without any superfluous advices on how to decrypt it.

> ### Steps to reproduce
> 1. Setup enigmail as per the screenshots ![tb1](https://user-images.githubusercontent.com/5766095/55407877-cad4c180-5556-11e9-8b19-65f8ca85aeb3.png) ![tb2](https://user-images.githubusercontent.com/5766095/55407878-cad4c180-5556-11e9-8652-597812083de3.png) ![tb3](https://user-images.githubusercontent.com/5766095/55407879-cad4c180-5556-11e9-9244-fbb9b2a851d8.png)

What’s so specific in this setup?  It looks pretty default.

> 2. send mail
> 3. suffer
>
> ### Environment
> K-9 Mail version: 5.600

In any case, I could not reproduce it.

> Raw mail (redacted keys and addresses):

Nice oxymoron.

Now the real mail produced by Thunderbird 60.6.1 + Enigmail 2.0.8 + GnuPG 2.1.18 and successfully read by K-9 5.600 + OpenKeychain 5.2:

--8<---------------cut here---------------start------------->8---
To: Ivan Ivanov <ivan@ivanov.example>
From: Dmitry Alexandrov <321942@gmail.com>
Openpgp: preference=signencrypt
Autocrypt: addr=321942@gmail.com; keydata=
 mQENBFfx9+UBCADFWn9mcF6TKbvjlskFIdOFDZ6+NWR0BwZFV9gRsM1BXjjARO2NVBZ/7LW6
 +TyKwdlHyenWYOJkGqopBm2dhTccYEwdPHzyAHkE1DvALk5E0vzNbSed12dAR3vYoAiTIBzs
 DR24uZI3iteKF6QlIfTpbA/uCnKy9DoJj50UKJsVeW3SuYf6KdwNo/caRtpNZ+DfjUfuX80c
 PwpbUSjR0mK5xDYkeBqYmORGllvZGhsc6Qt4i4Kc5oyZWN4DdbIkU6npxcpLNUS8sU0YlBDG
 kSTVVsNI30gcJWyNbadPkqjyPypM64gnBG0XYDLWI/I1QIXBD2dWOQtlsiCWF/1hlkb1ABEB
 AAG0JERtaXRyeSBBbGV4YW5kcm92IDwzMjE5NDJAZ21haWwuY29tPokBVAQTAQgAPhYhBNcq
 E8fXzjWq4sYDSMnaCd4ZwbIwBQJX8fflAhsDBQkJZgGABQsJCAcCBhUICQoLAgQWAgMBAh4B
 AheAAAoJEMnaCd4ZwbIwAZwH/3DCZon68SCcSrfWhNfQXYEQJ1kAG4lOqJ+ZMorD+RgD1wfT
 HF3pPmfQO2PuOGaeh/SIVa8RlXhiH8YQyFGlYukfPMyqGsrkgHFzUn+Ho5RZUiX1jGl8QlPk
 NcIpu4sPgjOTB8Nf+bSsIiB/yq4rtUcafPclebJxanSa2yaBrdA2KCNkcyWr3i9KaQCJTepW
 QYihKrSIq6wJQHr+vz512cB61eMHiU5IEyAr+lZBShZ99VhDFosTvLTiwLlDvH6Lx46wvab6
 5kkhdSs6l/2Ox4XwDUFRekmGzyIJdel3diZBBsIIIefTDuaEwpot/2EL3uGNUzivzvCY9AYk
 s1VhYvq5AQ0EV/H35QEIAJ88wJXvqeHo6OgzZWvaaHVlSyV13J5o5bBQiCY3n1isR81xhrK8
 M7uLA3v/ALuqQplhzsMwXe7Dnzn99jHAeQFVgFrxmejoOLSugg2skyuJ0Tq01hLiZbPWz6rC
 G64kAP9jVuj/PCe5jO1EmVs+YaRbYM0458BfTEpRF38y/tiiuickrvfZ5Gsjxk/iTg3BJEIU
 ab8cYH8QEY3A8GohmUv57xAsC+pQnCTHZdm1oVts5poUpoYklxlqtHI1ou5hOyo0jW98bNWH
 4ZeOf2AIYwy/WY8OoBWYl3XC7pg40aJdIZH9ILVbYjvj4/l49BrMlm4ewxZ4w2eFYhxaA5Yf
 xwEAEQEAAYkBPAQYAQgAJhYhBNcqE8fXzjWq4sYDSMnaCd4ZwbIwBQJX8fflAhsMBQkJZgGA
 AAoJEMnaCd4ZwbIwWhQH/Rk6uCfY3m6j9T8/oVhEmbrpJNPzejv4TnpQ7fbvTGGLZNuNxS9+
 QnwnGeKFhICxfQ0tBsISvyADEVrHZEelaUxzqdhVKnXycis1+02CDpcXRWSBR1Dx91QkJDar
 /P4rv/OND7GxXVp73dKs7CgRonpiIvgOdnh/sIrybABD4z0pP8r6zNUCnHMCo1v5wXu61RWj
 L2L4dHR9Mq60x+50KBJh5KqP3/v5+Q0B3TYBJFaFBYQLPJ8rq1TN8eZCKGWeXjrQzxftk/m/
 N2F03J+vkNRQwE2+1o/gIRIQxZWMHjq/ZMP0W6xwmFOa21CQR6jppPQ/18ak9IDFyzbwOGAr EH0=
Message-ID: <d6477c16-f72c-10b2-9ca3-95473cee1a19@gmail.com>
Date: Tue, 2 Apr 2019 22:42:58 +0300
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101
 Thunderbird/60.6.1
MIME-Version: 1.0
Subject: Encrypted Message
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="iftn7v6pO5ThXhaVvTUn01PWdhPKyGPK5"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--iftn7v6pO5ThXhaVvTUn01PWdhPKyGPK5
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--iftn7v6pO5ThXhaVvTUn01PWdhPKyGPK5
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----

hQGMA4Zs9HSUL/9XAQv/f072J11LQCV07CkFuS21L4GJOe5HQZ9CX4edR8y/abZp
ZsQ96jLZQtD5ZaWyWFDcIm6EMwq1HlptI1g9Wd2S7YBwpcr2s0B4W2nOYmndS2ym
fy55K414E8AgU9c/ueTGP9RjDD7wS/v2ZcpfOBcLHC4TUzoNqnsxJ9jbrX8wkubT
SlZF2yeJ0HHm5TV5vO6MLl90hntXCmOQJhOb4Y/IVb8OqJoNcydktocLOzjaSFbK
sBHh7OhfZ88mb6tMJFqzo3Wd7tTMyqeK3F01zLCBJhCEgp6cFOtoej+BQ+OdqQWL
S5DOx96omVQxyCIM0VS/+YA5Xh0z0K1R9faJOctJ3o3Um7wiKnMMq8t79Z0oUErC
50Hpnr6S9519r73QgavnKviWkJHGGMCL2AXRhW5xjx0Igc546JUbkyxqygdDKy6m
KYSkedlkDwAP2NALMIB/L3SiSP2bP5zYAD3C0yjK+M1aG45wIH6kxxOi3RkBOffw
bchm3ROqNY1fYVUatJ+9hQEMA1EZLBSRCuCRAQf/b1j2ukzj3hoE+r5bDDxq4eG8
lr2frcuYSfsckbYcdh53dFkMMbbGbUkSXdNpzvAp3abr2+bp/kRTbsx9c1FBqU/h
UpzOCEn+x670emFEUCXzRG2ZLejH9fdtWqqqjs8YsmUvB6XPs67fppkraU7wNaLt
DXmfANTdopwvXOHGUywM3D72MfLcOycmE4gg1rBD0GPc1VkpSbOek5Ll8bZ7kbLm
P+/D9lH9ZrEKTOFtF4bWP6GqexBrmukTR/k3Czb/dNqmikxNNCWmPsMP3PLhcnYQ
v+8sua/1ePtJ1uOzCGpEY3N1gfWMP/th1hdBsotaqZifnLNbJfl4PBLc/40jDtLA
7AFVp5orgTHKJSlzfN1Rt/j5co9C7V1hhG42MX1s8JYakL+G2R9zsUE5k4RDmogq
FbqWcgVt7CynC2iNRDMKLvEyGN0xaBkgaXxxyqAHx2wEZHCJw+5CeOgMn7xW+Ols
aTq2hPQPjZsjtNtycPApd0QsDBLGkc+NDJmkk+a8yoKZMbt9GphbgzMvo3sYeWSL
ISigqGROLIczL5ebk7wW+tgyTdSw14BPWlVDK/ndCzTzwgvtB6sdBar//tpJHbJj
aXgE8Vr7MQwZUtbyCHuVqfBzm+7OoAJUdjjMP1O2XxFEDwk17L3FqZTo26MKT75S
0dYkAW25+WE1+fvHVPKlTiv9NfFIilWvLRKjT+ROssjktQ69KOaw57ttTH5aBGKQ
bfBsRyDyyKN1WmYZcFJ1vq+11EBlVsNJPKIpYzX2eaeOyKhb5NCGpBD7wG3ibaS1
pl+edDWqVvwiQfUoHewsSwQrBxX+xFVrwE3Wxf79133h0NAwba2oKZWeuB4w29q/
xsL287uhE4lBmpHGom70rMy5W8NK+iRypTA/dH5KrcAYgCJJ/BKcoR6Nd+xY
=5rdr
-----END PGP MESSAGE-----

--iftn7v6pO5ThXhaVvTUn01PWdhPKyGPK5--
--8<---------------cut here---------------end--------------->8---

And recipient’s key to decrypt it (no passphrase):

--8<---------------cut here---------------start------------->8---

REDACTED 
--8<---------------cut here---------------end--------------->8---

**Comment by Lythenas** [comment]
I had the same issue when switching phones. Turns out I didn't import the correct key in OpenKeychain.

**Comment by cketti** [comment]
Bugs regarding encryption/decryption should be reported to OpenKeychain. They are much more qualified to deal with them. If you do, please provide more information about what private keys are available in OpenKeychain, which ones are connected to an K-9 Mail account, the exact error message displayed etc.
