### ISSUE TITLE
scrolling with numeric keypad

### ISSUE THREAD

**Issue by hallyn** [k9mail/k-9#4003]
I'd like to use k9mail on a sonim xp5, which has no touch screen and only numeric keypad.  Works ok, but there is no way to scroll in emails.

It would be nice if there were either an option to have volume key scroll up/down inside an email, or (and) use the number keys for some actions.  Maybe 1 page up, 3 page down, 7 delete, ...

Is there any existing feature that I've overlooked?  Would a patch to implement something like this be acceptable?

**Comment by jmawhorter** [comment]
Please see my enhancement request #3999, which is exactly the same request. I already have the functionality implemented. I just need to get feedback on whether this would be accepted and it if will, how to implement the option in the settings from a UI perspective since there is already an option to use the volume keys for nagivation in message view.

**Comment by hallyn** [comment]
what.  so it is.  i swear i searched.  sorry about that.

closing as a dup, thanks.
