### ISSUE TITLE
Default notification settings should be global

### ISSUE THREAD

**Issue by balnaborju** [k9mail/k-9#4006]
### Expected behavior
There should be a default notification setting in the global settings menu (ringtone, led, etc..), to simplify usage. It would be effective on all accounts which are not otherwise configured.

### Actual behavior
Notificiations can only customized on a per-account base, which is inconvenient.

### Steps to reproduce
1. 
2.
3.

### Environment
K-9 Mail version:
5.600

Android version:
8.1

Account type (IMAP, POP3, WebDAV/Exchange):
n/a

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
That would lead to a more complex user interface. Because every notification setting would have an added "use global default" value. Notification settings aren't changed that frequently. So I don't think the added complexity would safe users a lot of time.
With newer Android versions we can only influence the notification settings at creation time of the notification channel anyway. To modify the settings users have to configure the channel using Android's notification user interface.
