### ISSUE TITLE
Can't see senders email address

### ISSUE THREAD

**Issue by rmamail** [k9mail/k-9#4009]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
It should be possible to see the senders email address when clicking on the senders name in the incoming message, as in previous versions of K9, now you can't.

### Actual behavior
When clicking on the senders name in a incoming message, you can't see the email address. You can only choose, update contacts etc.
You should be able to see the senders email by clicking the senders name.

### Steps to reproduce
1.Clic on incoming messages sender name
2.
3.

### Environment
K-9 Mail version: Latest

Android version:
Android 9
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP
Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by rmamail** [comment]
Hi!

It should be possible to see the senders email, as in previous versions of K9, now you can't. 

When clicking on the senders name in a incoming message, you can't see  the email address. You can only choose, update contacts etc. 
You should be able to see the senders email by clicking the senders name. 

Now when you click on the name, you only get options to update or save the senders email to contacts. 

Latest Android version of K9
Android 9
Imap

**Comment by justf0rfun** [comment]
I think the sender's email address should be shown by default in the head of the view. I mean above the message and not the view of the technical headers. Maybe it would be best to even show the sender's name, too, by default. Both. This is important because it helps to identify phishing attempts and spam.

There is an option in global settings to show either the sender's name or the sender's email address. Unfortunately I did not find a way to show both. Which one is the current default? 
On my installation I found that I had to change the settings to show the sender's email address, but maybe I changed the default setting in the past.

K9 Version: 5.600
Adnroid 6.0

**Comment by cketti** [comment]
The dialog displayed when clicking the sender name is provided by the system. K-9 Mail provides the name and email address of the contact so it could be displayed in the dialog. On older Android versions this worked as expected. It looks like this functionality is broken or has been removed in newer Android versions.

For showing name and email address see #1119.
