### ISSUE TITLE
local drafts

### ISSUE THREAD

**Issue by anpic** [k9mail/k-9#4024]
please add option in account settings to completely disable automatic saving of local drafts

**Comment by basilgello** [comment]
Go to Account Settings - Folders and set Drafts folder to None. This will skip creation of both local and remote drafts.

**Comment by anpic** [comment]
> This will skip creation of both local and remote drafts.

how to disable this only locally?

**Comment by basilgello** [comment]
I think there is no way to disable it locally, because first the message is copied to Drafts using IMAP APPEND command and it resides in the folder locally and remotely. The only thing to add here is to enforce local removal of draft message, leaving it on server.

As for me, storing local-only draft wpuld be a more security-wise idea.

**Comment by cketti** [comment]
Why are you asking for this feature? It reads like you still want to save drafts to the server. 

We never write directly to the server. Everything goes through the local database first.

**Comment by anpic** [comment]
> It reads like you still want to save drafts to the server.

no
please add option to disable drafts fully and easy

**Comment by basilgello** [comment]
This is easy: https://fastpic.ru/session/2019/0512/N0F7nCkXLj.html

**Comment by anpic** [comment]
> This is easy

but how save drafts only locally and manually?
