### ISSUE TITLE
Option to specifically select identity

### ISSUE THREAD

**Issue by kxcooper** [k9mail/k-9#4036]
I would like an option to force me to explicitly select the desired identity every time I send (compose/reply/forward) an email.

Too often I send an email from the wrong address!

Thank you.

**Comment by cketti** [comment]
I don't think this feature is worth the implementation and maintenance effort. I doubt it would be used by many people. It's not something that is typically found in mail clients.

**Comment by simontb** [comment]
To be honest this is something I'd be interested in as well, but in my case only for composing or when the reply can't find an identity in the "to" fields of the original email.

But even for me as someone who'd like to have this feature, I think it is low-prio, because a sensible default is sufficient for those times I forget to change the sender.

**Comment by cketti** [comment]
@simontb: If you're willing to implement it, I might reconsider. You'll have to come up with a convincing UI/UX concept though. Open questions I can think of right now:
- How do users configure K-9 Mail to not use a default identity?
- How does the compose screen look like when there's no identity selected?
- What happens when the user hits send and no identity was selected?

I'm guessing a lot of code currently assumes there's an active identity, e.g. the crypto code. You'd have to make all of that work without a selected identity.
