### ISSUE TITLE
Allow underscores in DNS names

### ISSUE THREAD

**Issue by n-a-b-s-t-e-r** [k9mail/k-9#4052]
DNS names may contain underscores. See https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_hostnames

### Expected behavior
Underscores in DNS names for incoming and outgoing servers should be allowed.

### Actual behavior
The 'Next' button becomes greyed-out.

### Steps to reproduce
1. Go to settings -> Account settings -> Fetching mail or Sending mail -> Outgoing or incoming server settings
2. Put an underscore in the DNS name (not hostname)
3. 'Next' becomes greyed-out.

### Environment
K-9 Mail version: 5.600
Android version: 9 PKQ1.180729.001
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Still no (see #4049). Not everything you can put into DNS (i.e. DNS names) is a valid name for a host (e.g. your mail server). I don't see a compelling argument to violate that standard. If you want more readable names use a hyphen to separate words in you hostname, e.g. `imap-server.domain.example`.

**Comment by njeyaakili** [comment]
@n-a-b-s-t-e-r  -- On the wikipedia page you reference, look at the third paragraph under "restrictions" -- "While a hostname may not contain other characters, such as the underscore character (_), other DNS names may contain the underscore"

The underscore is allowed in DNS entries for things like DMARC and DKIM and service records so that these records aren't confused with hostnames. Hosts are not addressable via these names. Underscores have never been allowable in hostnames.
