### ISSUE TITLE
Mailto body html get sanitized

### ISSUE THREAD

**Issue by nicolaspernoud** [k9mail/k-9#4151]
### Expected behavior
When opening a mailto link with an html body (useful for sharing links for example), the html should be usable.

### Actual behavior
When opening a mailto link with an html body (useful for sharing links for example), the html get sanitized, and the link is not usable.

### Steps to reproduce
1. Open in a web browser a link with the format `mailto:somebody?&subject=Some subject&body=<h2>Some title</h2><a href="https://someurl.com">Some caption</a>`
2. The mail body get in the message as text, not as usable html...

### Environment
K-9 Mail version: 5.6
Android version: 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
This is by design.

Excerpt from [RFC 6068](https://tools.ietf.org/html/rfc6068), section 2:
> The special &lt;hfname> "body" indicates that the associated &lt;hfvalue> is the body of the message.  The "body" field value is intended to contain the content for the first text/plain body part of the message.  The "body" pseudo header field is primarily intended for the generation of short text messages for automatic processing (such as "subscribe" messages for mailing lists), not for general MIME bodies.

Even if HTML was allowed in a `mailto` URI, K-9 Mail currently doesn't support rich text editing. See #1745.

Side note: The parameter values in `mailto` URIs need to be properly encoded. If you want to create `mailto` URIs on Android, check out the [`EmailIntentBuilder`](https://github.com/cketti/EmailIntentBuilder) library that does all that work for you.

**Comment by nicolaspernoud** [comment]
Ok, thanks a lot for the insights.
