### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by rspencer01** [k9mail/k-9#4195]
I'd like to point out that the last release, 5.600 is now over a year old.  A lot has happened since then, not least of which is that the app now looks like a 21st century product.  Recent changes to the message list #4110 has left it looking absolutely stunning, and it would be wonderful to share this with the world.

Considering that prior to 5.600 there was a minor release every few months, it might be worth putting this on the radar.

**Comment by ByteHamster** [comment]
There are still a few things left that need to be implemented before releasing the redesign: https://github.com/k9mail/k-9/milestone/24

**Comment by cketti** [comment]
I think everyone is painfully aware that we need to release a K-9 Mail update. Unfortunately, we can't just release what we have now. As @ByteHamster mentioned, there are a couple of things that need to be done first.

The need for a release is definitely on the radar. Due to limited free time (and sometimes motivation) it will probably still take some time. But I'm sure we'll get there.
