### ISSUE TITLE
APK filename

### ISSUE THREAD

**Issue by stevenleeS0ht** [k9mail/k-9#4210]
It would be awesome to add some version information in output packge of both signed and unsigned; debug and release.

like `k9mail-5.600-release`. Instead of `k9mail-release`.

**Comment by stevenleeS0ht** [comment]
@cketti, @obra, What are your opinions?

**Comment by cketti** [comment]
It seems like this would only be relevant for people building K-9 Mail from source. APKs published under https://github.com/k9mail/k-9/releases already contain the version number in the file name.

I've never missed this "feature". But if you find a way to do this without impacting build performance and the Android Studio integration, I'm happy to check out a pull request.
But if this requires additional I/O operations e.g. because the file that was generated is renamed later, I don't want to pay this price. In that case I'll ask you to modify your local build script to add this feature.
