### ISSUE TITLE
Missing Permissions on Android 9/Samsung

### ISSUE THREAD

**Issue by h1ght** [k9mail/k-9#4246]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
When installing of Playstore, dialog to select which allowance the app gets.

### Actual behavior
Some Dialogs/Permissions missing, just Contacts and Fotos/Media/Data are shown.
In App-Manager its not possible to add missing Permisions
### Steps to reproduce
1.Install k9mail of playstore
2. check the info screen before installing
3.check permissions manager in app-permissions-manager

### Environment
K-9 Mail version:
latest of playstore 5.600
Android version:
Android 9 one UI core 1.5 (samsung m30s)

Account type (IMAP, POP3, WebDAV/Exchange):
imap aswell pop3, major/higher problem 
Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
will add logs after it and screenshots, getting familiar with m30s. 

regards
[Screenshot_20191110-152515_Google Play Store](https://user-images.githubusercontent.com/23379974/68545610-f2361b80-03ce-11ea-810e-d1067bb0cd29.jpg)
[Screenshot_20191110-152611_Package installer](https://user-images.githubusercontent.com/23379974/68545611-f2361b80-03ce-11ea-84a5-b218fdf30786.jpg)

**Comment by cketti** [comment]
With previous Android versions apps declared which permissions they need and the user only had the option to either install the app, or not install the app. The ability to grant only some permissions was added later. K-9 Mail 5.600 does not support the new permission model.

Nowadays apps are required to support the new permission model in order to publish updates on Google Play. So the next version of K-9 Mail will support this.

**Comment by h1ght** [comment]
some eta on new update? guessable or not? maybe i can live with that some time. 👍
