### ISSUE TITLE
Use of external SD doesn’t work

### ISSUE THREAD

**Issue by fondness4thek9species** [k9mail/k-9#4276]
### Expected behavior
Storage on external SD

### Actual behavior
All data remains on internal

### Steps to reproduce
1. Account settings
2. Storage
3. External SD

### Environment
K-9 Mail version:
5.600

Android version:
6.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP 

My K9 app has 13 GB and is blocking all of my internal memory. When adjusting settings to Storage-> External SD nothing happens, even when "rebuild account" is started (called "Daten neu erstellen" in my german version).
SD is working, has enough free space and is used by many other apps. No "com.fsck.k9" folder or similar is to be found in SD card though. 

Thanks in advance!

**Comment by cketti** [comment]
13 GB sounds like way too much. It's weird that "recreate account" doesn't help to reduce the amount of storage used. What should help is uninstalling the app, then reinstalling. Make sure you export your settings before uninstalling. Otherwise you'll have to manually add all accounts again.

The next version of K-9 Mail won't support changing the storage location (since what we had was useless anyway). Storing data on external storage will only be possible if you configure Android to use [adoptable storage](https://developer.android.com/about/versions/marshmallow/android-6.0.html#adoptable-storage).

See #1187, #863
