### ISSUE TITLE
Pop3 remove messages from server + notification issues

### ISSUE THREAD

**Issue by HFnp** [k9mail/k-9#4315]
1) k-9 mail version 5.700
2) android ver. 8.1.0
3) account pop3

Poll frequency is set to 15 minutes, once the email is received, is also deleted on server. In the previous k-9 version there was an option to leave a copy on server... i can't find it now.

Other issue on notification. Even if "show a notification for message I sent" is checked... no any notification is shown. (This happens for both imap & pop3)

Thank you!

**Comment by cketti** [comment]
K-9 Mail doesn't delete messages from the server after retrieving them. It's much more likely your email provider is doing some behind-the-scenes magic, see e.g. https://support.google.com/a/answer/6089246?hl=en

If you can avoid it, you shouldn't use POP3 with K-9 Mail. It's not a great fit for how K-9 Mail handles messages. You probably shouldn't use POP3 at all in 2019.

We know that there are lots of issues regarding notifications. Fixing them will be a focus after the next stable version has been released.

Closing this issue because there was no actionable information provided and it's likely these are bugs we already have an issue for. 
If you need help figuring out how to configure K-9 Mail to use POP3 with a specific provider please use the [mailing list](http://groups.google.com/group/k-9-mail).
