### ISSUE TITLE
Next sync before 51 minutes (Back to the future)

### ISSUE THREAD

**Issue by yafp** [k9mail/k-9#4329]
### Expected behavior
k-9 tells a user when the next sync will happen

### Actual behavior
It tells me

> Next sync before 51 minutes

![Screenshot_20191202-185035-01](https://user-images.githubusercontent.com/67605/70038258-3d9bae00-15b8-11ea-86ef-65fcf8d25faa.jpeg)

Usually it looks like that

![Screenshot_20191202-185107-01](https://user-images.githubusercontent.com/67605/70038283-48eed980-15b8-11ea-8ad8-9ca712061f7d.jpeg)

### Steps to reproduce
1. I can't reproduce this behaviour so far - just realized it once yesterday

### Environment
K-9 Mail version: 5.600

Android version: 9.1

Account type (IMAP,):

**Comment by cketti** [comment]
Due to the energy saving measures in modern Android versions the app can't reliably tell when the next sync will actually be. So the next version of the app will remove this text. 
You can check out an early beta version by downloading the APK on our [Releases](https://github.com/k9mail/k-9/releases) page or by becoming a beta tester on Google Play.
