### ISSUE TITLE
Fetching mail with POP3 does not delete them from the server

### ISSUE THREAD

**Issue by 0x6273** [k9mail/k-9#4348]
When fetching mail with POP3, K-9 never deletes the mail from the server.

### Expected behavior
The mail should be deleted from the server after retrieving, since that is how POP3 normally works. See [RFC1939](https://tools.ietf.org/html/rfc1939#section-1).

### Actual behavior
K-9 never sends the POP3 `DELE` command after fetching the mail. They are still stored on the mail server, and other MUAs can retrieve them, which is the behavior you would expect from IMAP, not POP3.

### Steps to reproduce
1. Configure POP3 as the protocol when setting up an account.
2. Try to retrieve mail from the same same account using another POP3 MUA.

### Environment
K-9 Mail version: 5.700

Android version: 28

Account type (IMAP, POP3, WebDAV/Exchange): POP3

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
K-9 Mail has always worked like this. But you're right that it's not the way POP3 is intended to be used. 

However, instead of adding support for the "download and delete" model it's more likely we'll remove POP3 support. In my opinion it's a relic of the past that shouldn't have a place in a modern email client.

**Comment by 0x6273** [comment]
Can this be reconsidered now that this is being rebranded to Thunderbird? This is needed for parity with the desktop version of Thunderbird.

Please reopen.
