### ISSUE TITLE
Selecting account should not close sidebar

### ISSUE THREAD

**Issue by madduck** [k9mail/k-9#4368]
With 5.701, if I open the sidebar to switch accounts, the sidebar then closes right away. Please keep it open, maybe just for a second or two, as not always does one want to go directly to the Inbox, and now I have to reopen the sidebar to switch folders.

**Comment by cketti** [comment]
I can understand wanting to switch accounts, then selecting a folder. I don't think the proposed solution leads to a decent user experience. Alternative suggestions on how to enable the use case are welcome.

**Comment by madduck** [comment]
How about keeping the sidebar open, and opening inbox in the background?

**Comment by flxbt** [comment]
Hello, I just came by to suggest this enhancement, too: As I use server side mail filtering, my K-9 experience has "not improved" with the new UI. While I'll be happy with either of madducks suggestions, as the 10/10 solution I see a (per account?!) setting like this:

	on selecting account:
		[ ] go directly to [choose folder] of selected account and close menu
		[ ] stay within menu to choose target folder manually

Thanks for your great work!

**Comment by simontb** [comment]
My proposal regarding UX is to add a flag to "General setting - Interaction" to leave navigation drawer open after selecting accounts.

If you'd ask me, I'd enable this by default, since I can imagine most users switch from Unified Inbox to an account to see another folder than Inbox. But I'm also open to disable it by default.

I also like @flxbt's suggestion, but since k-9 doesn't have interaction settings on account level, I'd refrain from introducing this for this feature.

I'd like to work on this feature.

**Comment by cketti** [comment]
I'd like to avoid adding new settings if possible at all. See here for some reasons why that is: http://neugierig.org/software/blog/2018/07/options.html

Since version 5.714 selecting an account no longer closes the drawer. Is there any other functionality that was requested here? Otherwise I think we can close this issue.

**Comment by simontb** [comment]
Thanks, tested with 5.716 and works as expected for me: 
- Navigation drawer remains open when switching account
- Navigation drawer closes when selecting unified inbox

Can be closed from my point of view.

**Comment by mpas97** [comment]
@cketti 

> Since version 5.714 selecting an account no longer closes the drawer.

With the current version (5.805) an account change closes the drawer directly. Had this feature been reverted?

**Comment by cketti** [comment]
> Had this feature been reverted?

See https://github.com/k9mail/k-9/pull/5477

**Comment by flxbt** [comment]
On August 23, 2021 3:49:10 PM GMT+02:00, cketti ***@***.***> wrote:
> > Had this feature been reverted?
> 
> See https://github.com/k9mail/k-9/pull/5477
> 

Very nice!


-- 

[message sent otg]
