### ISSUE TITLE
Please keep controls in bottom area

### ISSUE THREAD

**Issue by okias** [k9mail/k-9#4377]
New design is really eye pleasing, but please, buttons to bottom 👍 

### Expected behavior
Controls placed in bottom area.

### Actual behavior
Email buttons like delete or back/forward are on top of screen, hardly reachable with one hand.

### Environment
K-9 Mail version: 5.7

Android version: 8.1

**Comment by cketti** [comment]
It's unlikely that we'll switch back to a bottom bar. While it is helpful in portrait orientation it's not in landscape. 5.600 shows the bottom bar only in portrait mode and moves the action to the top in landscape mode. This was a popular source of confusion for users because they couldn't find the actions. We have no intention to go back to this.

We're trying to come up with a way to make actions more easily accessible without adding a bottom bar. But such a mechanism might not be ready for the next stable version.

**Comment by ccpp** [comment]
I want it too. From a usability perspective it makes more sense having the most important controls close to your finger tips, I.e. at the bottom for smartphones
