### ISSUE TITLE
Unread Message Count 

### ISSUE THREAD

**Issue by ITGeekMonkeys** [k9mail/k-9#4410]
Unread message count is unreliable when using Tesla Unread notifications badges. 
Previous to this beta release, the unread count was accurate. 
Now the unread count won't change after reading new mail. 
![12-27_09:28:54](https://user-images.githubusercontent.com/4103343/71522700-677c8380-288b-11ea-86d7-238a22f4d051.png)

**Comment by cketti** [comment]
Please report this as a bug to the author of the app that shows the unread count.

**Comment by OlyAndy** [comment]
This was working in 5.6, now doesn't. Teslaunread is not the issue.

**Comment by cketti** [comment]
Yes, it is. We removed some legacy code that could be used by third party apps to update the unread count. Now it doesn't work anymore and those apps have to update to use the proper mechanism.

**Comment by OlyAndy** [comment]
The problem is that nova launcher, a very popular launcher, only can use Teslaunread for its numerical counts. Unfortunately teslaunread is no longer supported or developed (which I agree, is crazy) . I am not going to change launcher. Would it be possible to have the legacy method returned to the code, perhaps with a switch to turn it on or off?
