### ISSUE TITLE
starting folder is set to none but inbox will be selected automatically on account change

### ISSUE THREAD

**Issue by iriman** [k9mail/k-9#4471]
### Steps to reproduce
1. Add some accounts
2. Change starting folder for some of them to none
3. Switch between accounts of step 2. Side menu will be closed and Inbox will be selected automatically.

### Environment
K-9 Mail version: 5.704

Android version: 7.1.1

**Comment by cketti** [comment]
Due to the change in how the app is structured now, not opening a folder is not really a useful option anymore. The value "none" for the 'auto-expand folder' setting is now effectively treated as "automatic" (and will almost always mean the Inbox is opened). We'll change the name of the value accordingly.

**Comment by iriman** [comment]
When there are some folders other than default mail folders and I receive some emails in them I think it could be useful (of course if possible to implement easily). So after selecting an account with no starting folder, side menu would wait till I select a folder manually. A few times this happened to me that after inbox auto-expanded, I swiped side menu again to select another folder.

**Comment by stoecker** [comment]
> Due to the change in how the app is structured now, not opening a folder is not really a useful option anymore.

That's not true. This option is a useful as before.

I'm using a setup with server side filtering, so that each of the folders acts as an inbox and can have new mail. For me the logical starting point is still the folder overview and not only one of the folders.

Together with the fact that I disabled automatic sync the current layout means that I have to click each folder and refresh it, whereas before a refresh in the folder overview refreshed all the main folders.

The current UI is fine and I like it, but in a setup with server side filtering the menu alone presenting the folders is unusable without the folder overview.

**Comment by poldi171254** [comment]
Happy to have a look at this, but just want to get clarification on the expectations.
Currently, if the "**Auto-expand folder**" for the default account is set to "**None**", the Inbox folder is displayed
![Inbox](https://user-images.githubusercontent.com/43848359/121993621-28c3eb80-cde7-11eb-96dd-9cc101aec1ea.png)

Do you expect in the above situation to see this instead?
![Inbox2](https://user-images.githubusercontent.com/43848359/121993816-80faed80-cde7-11eb-870c-821c750934c9.png)

**Comment by stoecker** [comment]
For me it's as already described: I have server side filters, so that mail does not go into ONE inbox, but into multiple folders. In previous versions the "none" display showed the folders and you could call manual refresh for all of them. That's not possible anymore, you have to open and refresh each folder individually.

A "refresh all" in the menu would also solve this for me.

**Comment by cketti** [comment]
> That's not possible anymore, you have to open and refresh each folder individually.
> 
> A "refresh all" in the menu would also solve this for me.

You can swipe down on the folder list in the drawer to refresh all folders. You can also swipe down on the account list in the drawer to refresh all accounts.

**Comment by stoecker** [comment]
Doesn't work. Did as you said, swiping in the overview menu with the folders. Folder inbox (first) was refreshed, but the others like "dmarc" not. My version is 5.734.

**Comment by cketti** [comment]
@stoecker: The folder class system still applies, i.e. either appropriately set the poll class for the folders you wish to poll or set `Settings > [Account] > Fetching mail > Poll folders` to `All`. This behavior isn't different from 5.600. It has also nothing to do with the auto-expand folder setting.

If you have further questions please use the [support forum](https://forum.k9mail.app/).

**Comment by cketti** [comment]
@iriman: Changing the account now always leaves the drawer open showing the folder list of that account (the default folder is loaded behind the drawer). Is that behavior sufficient for your use case or do you want the drawer to be opened on "first launch", too, showing the folder list?

**Comment by iriman** [comment]
> 
> 
> @iriman: Changing the account now always leaves the drawer open showing the folder list of that account (the default folder is loaded behind the drawer). Is that behavior sufficient for your use case or do you want the drawer to be opened on "first launch", too, showing the folder list?

Thanks. Yes, current behavior is sufficient for me, when I want to browse other folders.
