### ISSUE TITLE
Can I set poll frequency every 1 min in 5.705?

### ISSUE THREAD

**Issue by Bethinkz** [k9mail/k-9#4486]
Can I set poll frequency every 1 min setting the same as the old version?.

![28-01-2020 11-21-22](https://user-images.githubusercontent.com/39416421/73235311-78891f00-41c0-11ea-8fa3-c2afe3beb44a.jpg)

### Actual behavior
Fetching email setting page.

### Environment
K-9 Mail version: 5.705

Android version: 9

**Comment by cketti** [comment]
No, you can't. This is due to the energy saving measures of modern Android versions.

There is a compatibility mode in modern Android versions that kind of makes it work for old apps (like K-9 Mail 5.600). But Google requires apps to target modern Android versions to be able to release updates on Google Play.

If you want almost instantaneous notifications when new messages arrive, you want Push anyway. We track re-enabling Push for IMAP under #4258.
