### ISSUE TITLE
Add unread count to account list in drawer

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#4515]
Some users seem to miss the account list screen that displayed the number of starred and unread messages. I don't think bringing back such a screen would fit into the current UI concept. However, we could add the unread count to the account list items, similar to how we do it for folders in the drawer.

**Comment by ITGeekMonkeys** [comment]
That would be a good alternative and somewhat set the K-9 UI and functionality apart from Gmail.
Thank you.

**Comment by marcus905** [comment]
I think that the global account list could be optionally made available (maybe through a settings checkbox) for those who want it still (maybe above the unified inbox entry in the drawer or as a sort of homepage).

I agree that this is a good thing to add too -- but still a global view as an optional homepage would be nice to have, having 10 mail accounts and 10 different account colors it's bad having this list and unread count available only tucked out of the way in the dropdown inside the left drawer.

Thanks anyway.

**Comment by chrkuhlmann** [comment]
I absolutely aggree that this overview page was one of the strong points of k-9. Yes, different from most other mail apps, but superior for advanced users with more than one account.

A number in the drop down is a good idea but still much inferior: 
- No direct access to unread / marked messages or the folder list with a single tap.
- No access to this information using the hardware 'back' button

Please bring this page back as an option. This overview page is why I prefer K9 over FairEmail (even the paid version). Removing it will make me stay at the old version or switch.

Don't get me wrong: I understand and appreciate that you want to update the UI to appeal to new users. But please don't forget the UX for your existing users. This overview page has solid advantages that don't vanish just because it may not look as modern.

I'm also open to a new approach, but the current menu on the side just doesn't cut it for me. Please consider the two points I mentioned above. The new UI has to be able to address these points or the overview page will be missed.
Keep up the great work, I really like k-9.

**Comment by VilleW** [comment]
I installed latest beta to my secondary phone and I must say that I also miss the global account list. That is number 1 reason I use K-9 mail. I think I'll use version 5.600 on my main phone and never install version 5.7xx

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) to voice your opinions. We use this issue tracker to organize work that needs to be done. None of the comments in this issue add any useful information to the task it was created for.
