### ISSUE TITLE
Always show delete action in notifications

### ISSUE THREAD

**Issue by muety** [k9mail/k-9#4661]
First of all, thanks a lot for K-9 mail! I just switched to it from BlueMail and really like it 🙂.
The only thing I am missing is the ability to – besides replying to a message and marking it as read – also delete it right from the notification.

**Comment by cketti** [comment]
The functionality is already available. You can enable it under `Global settings > Notifications > Show 'Delete' button`. If you're using the current beta version please note that "global settings" has been renamed to "general settings".

I believe this functionality isn't enabled by default due to historical reasons. At some point we deleted messages without asking for confirmation and didn't support an easy way to undo the deletion. Nowadays we still don't support undo (see #624), but we do ask for confirmation (can be disabled in settings). That removes the main reason for it being an option feature: accidentally deleting a message.

Since this feature request comes up regularly, I'll use this issue as a reminder to change the default to always show the delete action in notifications.

**Comment by muety** [comment]
Very cool, thank you :+1:

**Comment by cketti** [comment]
I'd like to keep the issue open to track the work we still have to do. You should be able to unsubscribe from updates to this issue in the web interface.
