### ISSUE TITLE
UI : with modern (tall) phones, the top bar is not the best place to put important elements

### ISSUE THREAD

**Issue by spfmoby** [k9mail/k-9#4725]
### Expected behavior
When navigating between emails, taking actions on them (archive, delete...) on a mobile app, these actions should be easy to make one handed.

### Actual behavior
The fact that in the new UI the bar has been moved to the top of the screen makes one handed operations very difficult to achieve.
The easy to access "zones" are at the lower third and middle of the phone, not on the top.
example : https://www.smashingmagazine.com/2018/02/comprehensive-guide-to-mobile-app-design/ taken from https://www.smashingmagazine.com/2018/02/comprehensive-guide-to-mobile-app-design/
I personally think that the bottom bar was a better implementation, but there are probably some other possible solutions, maybe a floating button (that we can put wherever we want) that expands with all the needed buttons (delete, archive...) when we click on it could be more usable. It means 2 "clicks" instead of one, but they are easier to do).

### Steps to reproduce
1. open K-mail with a >5" screen smartphone in one hand
2. open an email
3. try to click on the delete or archive button -> you can't

### Environment
K-9 Mail version:
5.710

Android version:
8.0.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by jjakob** [comment]
Personally I don't mind or have a problem with the buttons being at the top - I find they often get in the way of scrolling the message list or the message itself when at the bottom (I used FairMail for a while which has those buttons at the bottom, and I prefer K-9's layout). I rarely ever delete or archive messages though, but it's not hard to reach the top of the screen if you want to. It would be nice that if this were implemented, it was a selectable option.

**Comment by spfmoby** [comment]
I agree that it depends on the use we have. If you are an "inbox zero" type of guy as I am, you are constantly using the buttons.
An option to switch between a top or bottom buttons bars could indeed be a nice addition.

**Comment by bio12** [comment]
Please put at least an option to set the top bar to bottom. Like the new Firefox.

**Comment by cketti** [comment]
Right now we don't have plans to move the actions to the bottom.

**Comment by jikamens** [comment]
:+1:

The app is _much_ less usable on large phones with the buttons and menu at the top instead of the bottom. It's also inconsistent with the UI of other apps on my phone. Apps with buttons at the bottom include: Bitwarden, 1Password, MyFitnessPal, Garmin Connect, Health Mate, Player FM, Ultimate To-Do List, Clock (stock Android), iHeartRadio, Photos (stock Android), Slack, Camera (stock Android)

At the top: LastPass Authenticator, Duo Mobile, Synology Drive, Calendar

Both: Authy, Google Pay, Rocket Player, Keep, Gmail

With few exceptions, the apps with more modern UX designs are putting their frequently used controls at the bottom. K-9 Mail is moving in the wrong direction here.
