### ISSUE TITLE
photos sent via "Send Reduced" do not get attached (this used to work)

### ISSUE THREAD

**Issue by frief** [k9mail/k-9#4727]
### Expected behavior
a new mail with the size-reduced pictures attached should open. This used to work with previous (5.6x) k9-mail versions (and still works f.e. with FairEmail).

### Actual behavior
New mail opens, but there are no attachments.

### Steps to reproduce
1. select photo(s) from the gallery,
2. send to the app "Send Reduced",
3. send to K9-mail (or to FairEmail)

### Environment
K-9 Mail version: 5.709 (F-Droid)

Android version: 5.1.1 (inofficial patch level March 2020)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
[tmp.log](https://github.com/k9mail/k-9/files/4576187/tmp.log)

**Comment by cketti** [comment]
The log looks incomplete. Can you please try to record an unfiltered log.

**Comment by cketti** [comment]
Make sure to configure Send Reduced to "Use content provider".

**Comment by frief** [comment]
Hi cketti,

thank you for the quick response! The instructions at https://github.com/k9mail/k-9/wiki/LoggingErrors point 3.3 did not work for me (the --pid=xxxxx parameter was not accepted (xxxxx was 6885 in my case)). 
So attaching the log passed through grep 6885, hope that this is ok:
[tmp2.log](https://github.com/k9mail/k-9/files/4576439/tmp2.log)

Actually I was using "Send Reduced Free" (I was not aware I had been using the "Free" Version). This version does not seem to have a "Use content provider" option.

**Comment by cketti** [comment]
I was testing the free version as well. But it looks like the option is only visible on Android 6+. That's unfortunate, because the "content provider" method should work fine on older versions, too. 

K-9 Mail 5.7xx no longer supports file:// URIs. So I'm afraid you won't be able to use Send Reduced with it on the Android version you're currently using. 
K-9 Mail should show an error message to the user instead of failing silently. See issue #4399 for that.
