### ISSUE TITLE
critical: longclicking not working

### ISSUE THREAD

**Issue by ilyapashuk** [k9mail/k-9#4793]
longclicking is handled as shortclicking in all items except messages in wich calls multiselect mode. also can't find manual refresh button.

**Comment by ilyapashuk** [comment]
android 9, samsung galaxy a 3 0, talkback

**Comment by cketti** [comment]
Since you didn't provide most of the information we ask for in the issue description I have to guess. 

I'm assuming you're using a beta version (5.7xx). The long-press popup menus haven't been recommended for quite a while now. We've removed them. Long-pressing a message in the message list (de)selects it. This works as intended.

You can refresh a folder by swiping down on the message list. Starting with 5.715 the same swipe to refresh mechanism is supported in the side drawer.

None of the reported behavior sounds like a bug to me. In the future please use the [support forum](https://forum.k9mail.app/) if you have questions about the app. We use this issue tracker to coordinate development of the app.

**Comment by cketti** [comment]
Related: #4794
