### ISSUE TITLE
Functionality - Saving attachments 

### ISSUE THREAD

**Issue by Donkey-Doug** [k9mail/k-9#4809]
Requested functionality:
- Give user possibility to select/change download location for attachements
- Keep original filename after downloading an attachement

I myself am experiencing two things related to attachments that I dislike. The first one is that attachments that are downloaded do not have the same file name as the attached file in the email. The second one is that the user can not manually select in which location the attachments are being saved. The combination of these two is specifically annoying, since I simply cannot find the location where my downloaded attachments are stored. Neither by navigating to the correct folder using a file explorer nor by using the search field of my file explorer to locate the files.

**Comment by ByteHamster** [comment]
Hi! This feature is already available in the app redesign that is currently in beta. You can read about how to join the beta in the K9 Forum: https://forum.k9mail.app/t/how-do-i-become-a-beta-tester/68

**Comment by Donkey-Doug** [comment]
I am in the beta and am using version 5.715. I cannot find the settings to change the location where attachments are saved.

**Comment by condemnedmeat** [comment]
@ByteHamster 

> the user can not manually select in which location the attachments are being saved

I'm using the beta in Android 11. Long-pressing an embedded image gives me the option to download it, if I tap the Download Manager notification it gives me the option to open the image in my choice of viewer. K9 is saving it to `com.fsck.k9.tempfileprovider/temp` isn't it? All other file types attempt to open in a viewer, no option to save.

How can I save to storage or move a file from it's k9 saved location to wherever I want?

I searched `https://github.com/k9mail/k-9/issues?q=is%3Aissue+attachment` and the forum so if it's an obvious answer, sorry I didn't see it.

**Comment by cketti** [comment]
@condemnedmeat: Support issues like this should be asked in the [forum](https://forum.k9mail.app/), not the bug tracker.

We don't set a location to which Download Manager should save the file. But I don't know of any cases where the file is stored to anything but the Download folder. I just tried on Android 11 and it seems the downloaded file is not part of the "Download collection" (what you see when you open "Downloads" in the Files app). However, it can be found under `Internal Storage > Download`.

**Comment by condemnedmeat** [comment]
Thank you for that cketti. The Discourse forums are very good but I was really wondering if this is an issue rather than a request for support. See what you think.

> I simply cannot find the location where my downloaded attachments are stored. Neither by navigating to the correct folder using a file explorer nor by using the search field of my file explorer to locate the files

This is outstanding from the original post and I share this experience on my plain vanilla Pixel 2 XL.

For me the Download Manager is not storing saved files from K9 in the Download folder. `Settings > Storage > Files > Download`. This is the Files app not Files by Google app. If I download an embedded image and view it - as described previously - in Photos the app gives the path as...

![pic](https://user-images.githubusercontent.com/42522540/95471041-0254d300-0971-11eb-877e-57a87b164c6f.jpeg)

_The path for saved files referred to in the previous post was incorrect. It's simply what I thought at the time._

...the path pictured doesn't exist where I can access it and I have no ability to move it. I have Documents not /document, I don't have a folder called 1483. I have searched for file and folder names that I've managed to glean and so far as I can tell, they are not anywhere to be found.

Attachments or embedded media that aren't saved but instead opened in a viewer _are_ stored in the path mentioned in the previous post I believe. A .zip opened in KeePassDroid which listed the path.

Is there an issue or is this expected behaviour? Would a log help?

**Comment by cketti** [comment]
@condemnedmeat: Posting to the support forum gives more people a chance to help. If it turns out to be a bug you can always open an issue then. Right now you're posting to an unrelated closed issue.

Viewing inline images and saving inline images are fundamentally different operations. I'm happy to elaborate if you post your problem to the support forum. Please include enough information so people can get a good understanding of what steps you're taking and what you hope to accomplish.

**Comment by 5shot** [comment]
I'm having a somewhat related issue.  I can't select where I want to save an attachment, and the default location is somehow set to the SD Card.  Problem is I don't have one on my Samsung S20 Note.  This means that the file won't save.
