### ISSUE TITLE
Misleading number at icon when it looks 

### ISSUE THREAD

**Issue by muessjoeh** [k9mail/k-9#4924]
I am using K9mail 5.718 (the new issue is completely empty, by the way)
When there is an entry in the status line, then there is normally a number displayed at the K9mail icon. This number could mean "There is a new mail!", or "I am just looking, be patient".
It would be great if this could only be option (1).

**Comment by cketti** [comment]
A number badge on the app icon is not a feature of K-9 Mail or vanilla Android. It's most likely a feature of your Android version. The number is probably taken from a notification created by K-9 Mail. But since K-9 Mail supports multiple accounts (and hence multiple unread counts) it's not clear what your OS does in this case. I'm not surprised they get it wrong in some cases.

I don't know how K-9 Mail could fix this. Maybe the creator of your Android version can shed some light into this.
