### ISSUE TITLE
Re-move e-mail from trash folder before syncing

### ISSUE THREAD

**Issue by ruayrod** [k9mail/k-9#4933]
In POP, when you mistakenly move an email to the trash, before syncing, you should be able to move it to the inbox.  To be able to get it back.

Sorry my bad english, Google translator..

En POP, cuando, por error, mueves un email a la papelera, antes de sincronizar, deberías poder mover a la bandeja de entrada. Para poder recuperarlo.

**Comment by cketti** [comment]
Obsolete due to #4974

**Comment by wilfriedh** [comment]
The issue exists for me **also with IMAP account**, which I configured not to delete messages from the K9 inbox when deleted from server, and not delete from server when deleted from inbox, and synchronization only manually.
Reason is that on PC (Thunderbird, IMAP) I transfer messages to local storage when the issue is settled, so these messages get deleted on the server. But on my smartphone I want to keep some of them for longer. If accidentally I move one of these messages to trash, K9 refuses to undo this action "because messages cannot be moved when not synchronized". 
It would be enough to be able to undo the last action under the condition that this action was not yet synchronized with the server.
