### ISSUE TITLE
Please consider adding hacktoberfest topic to project.

### ISSUE THREAD

**Issue by jd-boyd** [k9mail/k-9#4975]
**Is your feature request related to a problem? Please describe.**
Contributing to this project is ineligible for participation in DigitalOcean and GitHub's Hacktoberfest unless it has the "hacktoberfest" topic.  This is a new change to that program for this year.

**Describe the solution you'd like**
Simply add "hacktoberfest" to the projects list of topics on github.
 
**Describe alternatives you've considered**
The alternative is to not add that topic, and people who were motivated to contribute by the program probably won't.  There could be spam issues for participation, but hopefully the raised bar for hunting down a project with this topic will discourage most of that bad behavior. 

**Additional context**
The official document about this is here: https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by cketti** [comment]
I'd rather not. Currently we don't have a lot of issues that are suitable for newcomers. Also, right now I'm the only one reviewing pull requests and I'd rather spend more time writing code. 
Based on past experience it's unlikely Hacktoberfest participants will stick around and become regular contributors to this project. So time investment on our side would be more of a service to the larger open source community rather than to benefit this project. That's not a bad thing. But currently there are no volunteers for this.
