### ISSUE TITLE
Support Android 4.4.4 (Kit-Kat)

### ISSUE THREAD

**Issue by KOLANICH** [k9mail/k-9#5074]
**Describe the bug**
Support for Kit-Kat has been dropped.

**To Reproduce**
https://github.com/k9mail/k-9/blob/340bc720c80c9ba73035ab0e18562aa8482466da/build.gradle#L6

**Expected behavior**
It should be supported.

**Screenshots**

**Environment (please complete the following information):**
 - K-9 Mail version: latest
 - Android version: 4.4.4
 - Device: any obsolete
 - Account type: IMAP

**Additional context**
Not all tevices can get new Qndroid versionx because of obstacles created by Google and devices vendors.

**Comment by cketti** [comment]
Support for older Android versions was dropped because it's a maintenance burden, not because there are no more users using those Android versions. Unless someone volunteers to make the app compatible with Android 4.4 and commits to maintaining this compatibility going forward there's little chance of this happening.

**Comment by KOLANICH** [comment]
>Unless someone volunteers to make the app compatible with Android 4.4 and commits to maintaining this compatibility going forward there's little chance of this happening.

Thanks for the info.

**Comment by justinacolmena** [comment]
K9 Mail version 5.600 on Android “Go” version 8.1.0 here...
