### ISSUE TITLE
Do not allow to show user password in mailer error settings

### ISSUE THREAD

**Issue by alxchk** [k9mail/k-9#5221]
As there is no app lock, in case the phone is unlocked, it's trivial to see user's password. In case of mail password, this can be also SSO password or any other sensitive information, which is not okay.

**Comment by cketti** [comment]
K-9 Mail's security model assumes that the device is protected against unauthorized access. So being able to see the incoming/outgoing server password is a convenience feature, not a security issue.

Due to the authentication methods commonly used with SMTP, IMAP or POP3 the app has to save the password. This is especially undesirable when using SSO. Which is why many large providers support (or lately require) using app-specific passwords. Ideally they limit access to just the email service and can easily be revoked without changing the SSO password. If your provider doesn't support this already you should encourage them to do so.
