### ISSUE TITLE
Create a single sync notification instead of one per each account

### ISSUE THREAD

**Issue by AnXh3L0** [k9mail/k-9#5678]
**Is your feature request related to a problem? Please describe.**
Having multiple sync notifications for each account adds some clutter to the top bar and also causes the bar to close when this sync notification is the only notification present, causing frustration.

**Describe the solution you'd like**
I would like to suggest having a single sync notification whose content is replaced every time X account and Y folder are being synced. This way, there is no random top bar closing when this notification is dismissed/killed and you can clearly see at which point the sync is.

**Describe alternatives you've considered**
I considered disabling the sync notification but I want to have it visible so I know when the sync is happening and if I am to be expecting new emails.

**Comment by cketti** [comment]
After our chat I thought some more about this. It wouldn't be too much effort to support this for manually checking all accounts at once. But automatic polling is scheduled individually for each account. If the poll intervals are the same chances are the system will schedule them back to back. But for the app it's still individual "check mail" operations and I don't see an easy way to only use one sync notification when there are e.g. three accounts checked back to back.

I don't think the sync notification is that useful at all. Automatic polling is something that should work, not something the user should feel the need to babysit. So in the long term I'd like to get rid of this notification rather than spending much time making it "better".
