### ISSUE TITLE
Add support for PGP/MIME encrypted messages with inner PGP/MIME signed part

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#576]

**Comment by Diagoras** [comment]
Can you clarify what is meant by this issue? Is this PGP/MIME messages where the signature is inside the encrypted message, or multipart MIME messages where the signed part is inside another multipart?

**Comment by dschuermann** [comment]
@Diagoras What we meant was: http://tools.ietf.org/html/rfc3156#section-6.1

**Comment by Diagoras** [comment]
I see, so "sign then encrypt" instead of the OpenPGP "sign and encrypt". Thanks for the clarification.

**Comment by dschuermann** [comment]
@Diagoras exactly.

**Comment by denim2x** [comment]
Related: #572

**Comment by lvella** [comment]
There is a bounty on this: https://www.bountysource.com/issues/815255-pgp-mime

**Comment by andrixnet** [comment]
Enigmail-1.9 extension for Mozilla Thunderbird has forcefully enabled by default PGP/MIME. 
AFAIK the next version (2.0) will drop inline PGP. 
This will create serious interoperability problems with K9 + OpenKeyChain since K9 does not yet support PGP/MIME.

**Comment by dschuermann** [comment]
@andrixnet This bug is not about general PGP/MIME support, which is being worked on. But thanks for the information about Enigmail, do you have a link that backs up the claim?

**Comment by ar-** [comment]
I hope I'm posting in the correct location here. I'm desperately trying to find out what the current status of PGP/MIME is. I can't find any information. @dschuermann "This bug is not about general PGP/MIME support, which is being worked on" .... So what is the actual issue for that? Who works on that.

I would like to send PGP/MIME emails with K9. So I'm wondering:

1. Does that already work? If so, what branch do I have to download?
2. If it doesn't work: Where can I continue the development? What is that status? How is it supposed to look on the UI?
3. There is the PGP/MIME milestone, but is also doen't have any open or closed issue that suggest the status of the implementation.

Can anyone help me to find that out?

Additionally there is also at least one PR claiming to fix this issue (#576), PR and issue are closed, but it is apparently not done. So why are they closed? I'm confused.

**Comment by haxti** [comment]
Hi,

I have subscribed to the Beta which is rolled out  through Google PlayStore and PGP/MIME is working for me. You need a PGP Provider though. I'm using OpenKeychain.

I hope this helps.

Am 7. November 2016 09:34:09 MEZ schrieb Andreas <notifications@github.com>:

**Comment by dschuermann** [comment]
@ar- Work on PGP/MIME is done by @Valodim . See our blog post at https://www.openkeychain.org/k-9

AFAIK the milestone does not contain any issues because they have been resolved and the next K-9 Mail stable is on the horizon including better PGP/MIME support. Stay tuned.

**Comment by philipwhiuk** [comment]
It does contain issues - there's 6 open and 17 closed. Regardless, I think we are fairly close to a K-9 release. I know @Valodim wants to make more changes but personally I'd like us to do a release and then subsequently future releases if necessary to improve UX. If we have to do 5.201 or even 5.220 I'd rather than that these huge slow releases which block everything else.

**Comment by Valodim** [comment]
I've actually been finished with my changes and pushing for a release for weeks, months even at this point. It's just that regressions like the attachment one *keep coming up*. I sure hope we can get to a tighter release cycle after this!
