### ISSUE TITLE
Option for marking messages as read before deleting

### ISSUE THREAD

**Issue by mbunkus** [k9mail/k-9#591]
I often delete messages. Each and every time I don't want to see them, don't want to have to be reminded of them anymore. Be it spam, mailing list posts I don't care about etc.

Often enough I delete a message without even looking at it. A Polish subject? Great, I don't speak Polish, just delete it. Wine marketing? I don't drink wine; delete it. Etc.

So my options are, especially from the notification area, to mark it as read or to delete it. If I just delete it it stays unread and my trash folder suddenly has one unread message in it. But I don't want to read that message. Ever! I also don't want the hassle of having to go to my trash folder and marking all messages read there regularly. I'm busy enough as it is, and such repeating tasks is what a computer should take care of for me.

So please, please provide an option that lets K-9 mark a message as read before it is moved to the trash folder. Pretty much all desktop email clients have such an option.

Thanks for considering it.

**Comment by cketti** [comment]
See PR #579

**Comment by philipwhiuk** [comment]
Few things

1. Your PR contains all the changes from a merge you've done. This is partially because GitHub is stupid at working out what a PR should contain and what commit the PR is based off. but it makes it impossible to review. If it wasn't for point 2, you'd need to resubmit it as a new PR anyway. Generally, don't bother merging in later changes, unless they'll conflict - in which case do a new PR.
2. See #1203 for an alternative PR on this fix.

**Comment by rugk** [comment]
I would also like this feature very much.

**Comment by rugk** [comment]
Just saw I opened an issue for that a long time ago, too (https://github.com/k9mail/k-9/issues/1840). This is really needed. I suggest anyone who wants this to upvote it…

**Comment by radicarl** [comment]
Miss this Feature too
+1
