### ISSUE TITLE
Starting Material Design

### ISSUE THREAD

**Issue by AMDG2** [k9mail/k-9#599]
Hello !

I just started a Material design for K9Mail, you can see my work here https://github.com/AMDG2/k-9
Let me know what you think about that, so when ready the pull request can be done very quickly !

**Comment by ocdtrekkie** [comment]
Please don't. :(

**Comment by obra** [comment]
fantastic. as the person most responsible for the old UI, I'm thrilled to see someone giving it love

**Comment by cketti** [comment]
:+1: for material design. However, I'd like the next UI overhaul to be more than just changing the design a little bit.

A couple of things I want in such a new version:
- Unite the settings screens so there are not 3 different places for settings.
- I want to move away from the concept of having one screen for each of account list, folder list, message list (and message view). A navigation drawer for accounts and folders seems like the way to go. This needs to be tuned a bit for tablets.
- The bottom action bar that is only present on phones in portrait orientation has proved to be too confusing for users. So we should get rid of it.
- Swiping left or right to get to the next or previous message
- Swiping items in the message list to trigger an action (e.g. archive) is something we definitely want
- We should aim to get rid of sub menus or add an indicator so sub menus are easily discoverable
- No more popup menus on long-press. The platform moved away from this a long time ago.
- A better concept to display error messages to the user

Please feel free to add your own thoughts and observations about what's not working very well in the current version.

**Comment by ocdtrekkie** [comment]
Bottom action bar is the best thing about K-9. One of the primary reasons I use it.

**Comment by cketti** [comment]
@ocdtrekkie Old versions of K-9 Mail won't go away. But the platform has largely moved away from the bottom action bar for a reason.

**Comment by ocdtrekkie** [comment]
Reason being "Google branding". Usability studies of finger reach from any of a number of common ways to hold a phone support that putting buttons on the top of the screen ranges from an uncomfortable stretch to a painful endeavor. The move to larger phones exacerbates the issue even further. 

I've used this app as an example of ideal comfort and productivity for years. The fact that it isn't just another Google Apps clone is the biggest reason why. 

Obviously I'll make myself a fork for personal comfort purposes if this happens, but I'm not an Android developer, so I won't be able to backport much (especially given how drastic code changes are to support Material). It'll be a huge loss to me, and the platform.

**Comment by clawoflight** [comment]
I wholeheartedly agree with most of the propositions, especially lateral swipes to change message and a navigation drawer.
However, I also think that the bottom action bar shouln't move.

**Comment by maniac103** [comment]
@ocdtrekkie Are you going to suggest to app developers they should fight against the platform (and not e.g. use the appcompat code) one project at a time now? It's _impossible_ to use the split action bar with appcompat when targeting API 20 and higher.

**Comment by ocdtrekkie** [comment]
@maniac103 I am pretty iffy on using AppCompat now that I've dug into it. It seems to be Google's way of forcing people into crud. 

Apps should be built for users, not Google. If I wanted Google's bad UI, I'd still be using the Gmail app. But I'm here using K-9 because it's better. So yeah, I intend to ask the devs to not screw up what makes their app worthwhile.

**Comment by maniac103** [comment]
@ocdtrekkie Holo is as much Google's design as is Material. Just because you happen to not like it, it isn't 'bad' per se.
What most users actually want is consistency in the UI of their apps. They want them to look and behave somewhat consistently, so they don't need to learn new UI paradigms each time they use a new app. That's actually what design guidelines are used for. If the platform design guideline evolves (in whatever direction), it's a good idea for app developers to follow that, or their apps will feel dated and lose users sooner or later. Try one of the (still plentifully available) pre-API 10 apps and you'll see what I mean. It's just pointless to fight against platform evolvement as a single app developer if the vast majority follows said evolvement.
(NB: considering material design to be 'bad' and 'for Google, not users' [I can't follow what specific advantage Google has from Material vs. Holo] seems to be a niche opinion and certainly not reflect the majority of opinions voiced so far)

**Comment by ocdtrekkie** [comment]
@maniac103 There's actually a huge branding difference between Holo and Material. Namely, that Holo is an Android brand, and Material is a Google brand. But it's largely irrelevant point here, I'm not as concerned with how it looks as how it works.

Does @cketti know what does and doesn't make users choose K-9 for mail? I mean, the new Email app from Google now much more feature-complete, Gmail now takes third party email accounts directly. I would argue one of K-9's biggest key differentiating features is it's UI. Changing it to match Google's new stuff isn't actually a user-friendly choice. The reason I disabled the Google apps and installed K-9 is because of the superior UI, which is now proposed to be overwritten. The continued development of apps without these awful UIs is one of the reasons I haven't fully abandoned the Android platform yet. K-9 as it currently is, is without a doubt, the only reason I still own an Android phone at all.

If you want to shift the app that radically, you're really making a new app at that point. Cutting off users from updates to the app they actually chose to use (and potentially updating them via the Play Store without them realizing it was going to happen) is a pretty terrible thing. The smartest people I've seen at this are Mobint, who realized their Holo Launcher was selected by people _because_ it is Holo. So instead they created a separate app for each new UI, so people can have the UI they want, not the UI the developer is forcing on them.

**Comment by ocdtrekkie** [comment]
Also, I agree, users want consistency. Which is why I'm mystified you'd advocate a change which would cause many users to open up their email one day and not know where the buttons are because you moved them. And be unable to revert it since the Play Store doesn't allow you to install old versions. 

The Play Store auto updates apps for most users, so if you want to move buttons that drastically, you should be building a separate app. And maybe give users of the original app a one time pop-up telling them the new app exists and they can switch to it if they want.

**Comment by dodgex** [comment]
Split actionbar is still possible  https://gist.github.com/dodgex/7bc81fd2cbb70a8d5117

**Comment by cooperpellaton** [comment]
@ocdtrekkie I think that much of what drives users to K-9 is the fine grain control it offers over accounts. Although GMail now encompasses IMAP support, one can still not select which folders to sync, at which intervals they sync and on which to receive notifications. This, in my opinion, is what drives users away from the default mail application. All that being said, I believe that the biggest detractor currently plaguing K-9 mail is the UI. I feel that the major reason CloudMagic got any traction was the beauty of the UX and the control it offered. K-9 is great, and can be even better if it hits the proper market by attracting users rather than looking like something which people who "care about this type of thing" would use.

**Comment by ocdtrekkie** [comment]
@cooperpellaton I think if it's absolutely necessary to create a new UI to attract new users, it should be a different application.

**Comment by cooperpellaton** [comment]
@ocdtrekkie Do you not want the entirety of the applications on your phone to adhere to a standard design specification? Why are we grasping at straws trying to hold on to a design spec that was thrown to the wayside more than a year ago. Software was meant to evolve, and this seems like the natural evolution of the application.

**Comment by cketti** [comment]
I created the branch [material_design](https://github.com/k9mail/k-9/tree/material_design) that includes @AMDG2's initial work. If you want to help with the material design overhaul please create pull requests against that branch.

**Comment by ocdtrekkie** [comment]
@cooperpellaton Every app on my phone is currently Holo compliant. I do want all of the applications to adhere to a standard design specification. It's not the steaming pile of poo that material is. It's really freaking awful.

And only 5.4% of Android phones use Material: http://developer.android.com/about/dashboards/index.html while 90% of Android phones are on some version of Holo. If you want a standard design specification on phones, you should be using Holo.

**Comment by cketti** [comment]
In my opinion K-9 Mail's user interface is far from ideal. And that's why it **will** change at some point in the future, hopefully for the better :)
Given the number of users K-9 Mail has, not everyone will be happy about the change. But that's okay. Maybe this is the time to part ways.
The nice thing about open source software is that you can take the code and make your own version. Or, if you like K-9 Mail the way it is now, all you have to do is not update.

Please try to keep comments in this issue on topic. If you feel the need to argue further about whether or not change is necessary please use the mailing list: http://groups.google.com/group/k-9-mail

**Comment by obra** [comment]
This is the wrong place to complain about or debate work that other folks are trying to do to make K-9 better.

If you'd like to see a future version of K-9 that sticks with Holo, it's worth discussing on the k-9 users mailing list. If the folks volunteering their time to improve K-9 make changes you dislike, you're always welcome to use the older version or to fork the application.

**Comment by jancborchardt** [comment]
@AMDG2 @cketti @obra looking forward to this very much! I’m trying out the default CyanogenMod email app and it’s a bit too buggy for my taste.

I’d be very interested in helping on the UX design of K9-Mail. Can you post screenshots of this change, or are there any pre-built .apks? (Alternatively I can also build the whole thing if it’s reasonably straightforward for a half-designer/developer. ;)

**Comment by mohlerm** [comment]
@ocdtrekkie @cooperpellaton The reasons why I personally (and a few friends) use K-9 is because it's free, open-source and supports pretty much everything you could expect from a mail client (many settings, folders, pgp etc).
I'm pretty confident that a new design would even attract more users since the current one looks dated.

**Comment by andrewachen** [comment]
Nice start @AMDG2! Do you happen to have the source files for the Material icons? I've been trying to keep tabs on the original svg files for new assets so that we can migrate to vector icons in 5.0+. Thanks.

**Comment by gnuanu** [comment]
I would love to see K9 in Material Design. As @cketti mentioned in a previous comment, Settings should be segregated in to a single screen and sub categorizing it in to "App Level" and "Account Level" settings.

I use CyanogenMod (obviously with F-Droid only) and I love the design on default EMail application in CM.

**Comment by AMDG2** [comment]
@andrewachen Glad to see someone working on this :)
You have the Google Repository: https://github.com/google/material-design-icons
Or a community one: (i think there are more icons on that one) : https://github.com/Templarian/MaterialDesign

I am very very busy right now, I can't work on the Materiel re-design. I started this thread so other can work on it, I am happy to see that you work on it, thanks !

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, as a supplement, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi

**Comment by CFPrulez** [comment]
There is a fork called "SMile" where the UI of K-9 has been re-designed, so it should look like Material Design.

Maybe it is possible to include some of these elements in K-9.

Screenshots of UI in Playstore: https://play.google.com/store/apps/details?id=de.fau.cs.mad.smile.android
Sourcecode: https://github.com/FAU-Inf2/SMile/

**Comment by mruwek** [comment]
@CFPrulez 
Regarding SMile (after about 10 minutes of playing with it).

a) Nice:
- floating button for new e-mail
- swipe to delete
- sidebar with "default folders" (Inbox, Sent, Trash, Drafts)
- avatars as circles
- big search button on top

b) Not very nice:
- no convenient way for selecting multiple messages
- some original settings from k9 are absent (I can't find notification sound setting for instance)
- messages with openPGP error doesn't display at all (for example when someone replies to inline PGP message and didn't remove PGP data from reply) - k9 displays whole message and error message on top of it.

It definetely needs polishing, but as a starting point it's more than good.

**Comment by jancborchardt** [comment]
So maybe these can be incorporated step by step into K-9 as pull requests? K-9 is a very popular and established app, so it would be good to collaborate here. @cketti @CFPrulez

**Comment by mokkun** [comment]
@cketti I'd love to help with the Material Design as well as with other features of the app. Do we have any wireframes for the redesign? If not, it would be nice to start some sort of prototyping and discuss on the top of that, until there's something concrete and only then move on implementing it.

**Comment by cketti** [comment]
@mokkun I think a first good step would be to collect a list of user-visible features that are currently available on each screen. Ideally all of them should still be available in one form or another after the redesign.

**Comment by PanderMusubi** [comment]
Top bar is ineed to much of a stretch for your fingers on large scren smartphones. Looking forward to the Material Design, especially a new or at least alternative laincher icon.

**Comment by mokkun** [comment]
@cketti Okay, will do some work on that, where'd be the best place to put such documents (list of features, wireframes images, screenshots, etc)? Maybe a place like Dropbox Paper or the GitHub Wiki?

**Comment by JasperWeiss** [comment]
I'd love to see a Material design overhaul. The design is what keeps me from using k-9 mail at the moment.

**Comment by cketti** [comment]
@mokkun Github wiki would be best.

**Comment by ouafnico** [comment]
Nice!
How can we install the material design version to test it?

**Comment by JasperWeiss** [comment]
Could you give us a debug apk?

**Comment by ouafnico** [comment]
The material design seems to works well. I've compiled it from the github sources with android studio.

Is going to be a alpha release dedicated to this material design version?

**Comment by JasperWeiss** [comment]
Some binaries would be nice indeed :)

**Comment by cketti** [comment]
Please use the mailing list for talk that is not directly related to development.

**Comment by qooob** [comment]
+1 for material!

Is this hard to maintain two versions maybe? Androind 6 is there, K9 doesn't blend well because of absence of material design.

**Comment by ocdtrekkie** [comment]
@qooob It's not "hard" if an app is developed well. But there is an amount of work involved. Work that @cketti has made quite clear he has no intention of doing.

**Comment by qooob** [comment]
That would be nice to release version K-9 Mail Material - it will only make it more popular.

...or make material default and release another version with old design.

**Comment by JasperWeiss** [comment]
If I remember correctly k-9 mail is moving to material design and will be abandoning holo all together which I think is great. But oh well I'm just going to wait for protonmail to release their app since I'm using protonmail as my primary email now anyway.

**Comment by Orbixx** [comment]
The UI, and more importantly the UX in K9 Mail is really the only thing that stops me from using it. It is not pleasant to look at and the amount of taps I have to do for certain actions is far more than necessary. I'm a bit surprised this hasn't been addressed sooner.

Which is unfortunate, because the functionality of it is fantastic. I'd love to recommend it to my friends, but in its current state I cannot simply due to it being far too confusing and difficult to use by them.

**Comment by PanderMusubi** [comment]
+1 for material **with** bottom action bar

**Comment by cketti** [comment]
FYI: I am and will be deleting random "+1" comments (not only in this issue) that only add noise. We already know that users have different preferences when it comes to the UI. There's no way to use Github to vote on an issue and be sure the result is representative. Not that I want to open a vote on something like this anyway.

If you feel the need to discuss this policy, please use the [user mailing list](http://groups.google.com/group/k-9-mail) or the [developer mailing list](https://groups.google.com/forum/#!forum/k-9-dev).

**Comment by Abscissa** [comment]
PLEASE make any metro *cough* I mean "Material" UI changes optional. Many people don't like it.

**Comment by qooob** [comment]
I noticed an opposite - that many people love it. Who exactly doesn't like it? Not having `Material UI` (when Android 6 is around quite a lot) for such an amazing app, is the way to loose users. 

However, I don't mind keeping old design. I'm just guessing that it's gonna be difficult for developers to maintain two versions.

In the end, it's Android app and developers have to follow parent's trends.

**Comment by Abscissa** [comment]
Ilia Rostovtsev <notifications@github.com> wrote:
>I noticed an opposite - that many people love it. Who exactly doesn't
>like it? Not having `Material UI` (when Android 6 is around quite a
>lot) for such an amazing app, is the way to loose users. 
>
>However, I don't mind keeping old design. I'm just guessing that it's
>gonna be difficult for developers to maintain two versions.
>
>In the end, it's Android app and developers have to follow parent's
>trends.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/599#issuecomment-170104194

Two different versions shouldn't be necessary. I haven't looked at the code, so I don't know how tightly coupled it may or may not be currently, but if the visual style, layout, etc aren't already cleanly abstracted away from everything else then they really should be anyway. Which means there really wouldn't be much duplication. It's essentially comparable to a skinning issue, really just a collection of a handful of options.

**Comment by qooob** [comment]
Then devs should definitely release two versions. :)

**Comment by cketti** [comment]
Locked this issue. Please take non-technical discussions to the [mailing list](http://groups.google.com/group/k-9-mail).

**Comment by cketti** [comment]
The `master` branch has already switched to using Material Design themes. K-9 Mail version 5.800 will contain these changes. 
Closing this issue since we don't need a general reminder and it's locked anyway.
