### ISSUE TITLE
Resend/redirect/bounce mail

### ISSUE THREAD

**Issue by darkdragon-001** [k9mail/k-9#622]
Without changing header. 
So that PGP signature is still valid.

Needed to 
- train spam filter
- transfer to another person
- send to other mail address of same person (e.g. calendar invites)
- send to distribution list

Also see this old issue: https://code.google.com/p/k9mail/issues/detail?id=1848#makechanges

Where should I get started to implement this?

**Comment by cketti** [comment]
I want us to add resent-* headers when resending a message.
See https://tools.ietf.org/html/rfc5322#section-3.6.6

As for where to start: 
`MessageCompose` is the Activity that contains most of the code to build a message to be sent. But it's in desperate need of a refactoring before new functionality should be added.

We're still working on the PGP/MIME integration and 'master' is in a bit of a fragile state. So sending messages might be broken right now.

**Comment by neufeind** [comment]
Adding resent-headers is a must. Also displaying them would be great since it allows to see if a message reached you directly or which colleague bounced a mail to you.
When I bounce something in Thunderbird (with a plugin) I also get an indication that the message was bounced (like "has been replied to") in my own mailbox. But I'm not sure if that flag is stored in IMAP or maybe just local. Would be great to be able to work cross-device of course (and see what you bounced or did not yet bounce), if there is a standard for it maybe.

**Comment by the0ne** [comment]
see #1739 for an implementation of rfc5322

**Comment by cketti** [comment]
See comments in #1739 for why we won't include this feature.
