### ISSUE TITLE
Add simple blacklist spam filter

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#679]
See PR #148

This feature requires…
- a simple way to add addresses to the blacklist
- a user interface to remove items from the blacklist
- a new database or a new table in an existing database

**Comment by uudruid74** [comment]
Just my two cents, but an implementation should be mindful of possible Sieve support in the future. See RFC 3028, 5228, and 5429.  Best place to do any sort of filters and blacklists is on the server since we're on mobile so we don't want to maintain lists in multiple places (mobile, desktop, work desktop, etc) nor do we want to download mail over expensive mobile connections just to drop the message.  Even when these RFC are not supported directly by the server, there are often hacks, such as using google's gmail web interface and filling out the form to get the server to filter for us.  Spam/Trash folders should only be synced manually, not in background, etc, etc.

**Comment by BloodyRain2k** [comment]
Adding my 2 cent: I'd really like a localized filter because my mail service provider doesn't even allow filtering of any kind in the free version.
Mainly because the first thing everyone would add would be their ad mails.

On my PC so don't care at all because Thunderbird knows that spam since years and on my phone the mail gets already downloaded anyways because it isn't classified as spam in the first place obviously.

So I'd really like the ability to define some, or in this case 1, filter for blacklisting mails so I don't get a notification for that crap <.<

I get the point about not wanting to maintain multiple lists, but in the end should this be a choice of the user, in my opinion atleast.

**Comment by uudruid74** [comment]
Agreed.  Blacklist for now, but it's development and implementation should be mindful of future improvements.  However, I've had to dump K9 and K@ since I was never getting my mail.  Switched to Edison mail

**Comment by cketti** [comment]
See #1508
