### ISSUE TITLE
Reply button disappears from toolbar when turning phone sideways

### ISSUE THREAD

**Issue by djkucera** [k9mail/k-9#727]
Is this a bug or a support request?

Bug

Have you looked for another ticket that might already be about your bug? 

Yes, and others have opened tickets in the past about this issue, however, all have been marked Invalid, closed in some other way, or New, yet still no resolution.

What steps will reproduce the problem?
1. Open any e-mail
2. Turn phone sideways
3. Toolbar buttons jump to title bar, but reply button is missing

What do you expect to have happen?

Buttons should include reply button.

What do you see instead?

Reply button simply missing.

What version of K-9 are you using?

5.006

What is your device and what version of Android are you using?

Motorola Photon Q, CyanogenMod 12.1 (Lollipop 5.1.1)

Is your email account a POP account, Exchange Account or an IMAP account?

IMAP

In order for us to have a chance at helping you with a complex issue, we're
going to need a debug log from your phone. 

Sure, I'm attaching the tail part of the log where I opened a new e-mail and the reply button was not on the landscape toolbar.  I doubt it will be very helpful, but here it is in any case.

What else should we know?

Also attaching a screenshot.  I'm willing to help in any way to gather further info, just let me know.

![screenshot_2015-08-01-12-46-10 1](https://cloud.githubusercontent.com/assets/13606160/9024310/c7536042-387d-11e5-9590-053b1168d3d2.png)

![k9_logcat_photon_q](https://cloud.githubusercontent.com/assets/13606160/9024345/3de92f1a-387f-11e5-8e11-0c3989506579.jpg)

**Comment by patricktokeeffe** [comment]
I've noticed this too. If you play around (en|dis)abling options under "Settings > Global > Display  >Visible message actions", you'll see that only the left-most action icon is displayed. 

Workaround: disable all message actions

**Comment by djkucera** [comment]
Thanks Patrick.  Your workaround works well.  I never delete e-mails from K-9 so that works out just fine for me to remove the default garbage can that was there before.

As far as I'm concerned this is still a bug, so I'm going to leave it open for a project team member to arbitrate.

**Comment by cketti** [comment]
This works as expected. The number of actions that are displayed as icons depends on the location of the action bar and screen size. When the icon is not visible the "Reply" action is inside the "Send…" submenu.

**Comment by lord-aerion** [comment]
This is still an issue in version 5.600

I use a Planet Computers Gemini, which is designed to be used in landscape mode due to its integrated keyboard.

I have to rotate the device into portrait mode In order to display the reply button before I can reply to or forward messages, then put the device back in its default landscape position.

The workaround mentioned does indeed result in the reply button being displayed, but at the cost of losing the delete button, so not really a workable workaround. When the reply button is not visible, for example when leaving the delete action enabled, the reply function does _not_ appear in the overflow menu.

Contrary to the reason given for closing this bug, I'd argue that this is not working as intended. There is more space in landscape mode, yet fewer actions are displayed than in portrait mode. Furthermore, the missing action do not move to the overflow menu, and enabling additional message actions results in only the left most icon being displayed (as mentioned in a previous comment).

This bug makes using K-9 Mail on pure landscape devices such as the Gemini cumbersome. I don't expect to have to pick up a laptop style device off my desk, turn it to portrait mode, hit reply, then put it back on my desk, before I can reply to a message. This is frustrrating enough to have to do for just one email, let alone having to do this repeatedly when working through a string of messages.
