### ISSUE TITLE
MIME type set incorrectly for attachment intent

### ISSUE THREAD

**Issue by micwallace** [k9mail/k-9#787]
Hi,

When a .gz attachment is opened in k9, the MIME type gets set to text/plain.
The mime type should be set based on the file extension.

Thanks for all you great work building this app. It's my primary client on Android and I have even worked on the source to help create a visual voicemail client with another developer.
The only thing that I find a bit buggy is remote search.

If you point me to the right files I'm happy to work on these issues.

**Comment by cketti** [comment]
We already use a fairly complex algorithm to determine which MIME type to use with the VIEW intent. If "text/plain" is used then that's probably because it was specified like this in the email.

Next time please use the [issue template](https://raw.githubusercontent.com/k9mail/k-9/master/issue_template.md) to report bugs. For questions about development use the [developer mailing list](https://groups.google.com/forum/#!forum/k-9-dev).

**Comment by micwallace** [comment]
Thanks for the quick clarification.

Cheers,
Michael

**Comment by micwallace** [comment]
I just had a look at the email source and I still think there's an issue here.

**Comment by micwallace** [comment]
....woops pressed enter

The attachment mime type is set as text/plain but the name is clearly .gz:
Content-Transfer-Encoding: base64
Content-Type: text/plain;
 name="device-logs.log.gz"
Content-Disposition: attachment;
 filename="device-logs.log.gz";
 size=26286

Shouldn't k9 be checking the file extension in the case of text/plain?

**Comment by cketti** [comment]
K-9 Mail has no way of knowing for sure that `text/plain` is the "wrong" MIME type. It's the responsibility of the sending application to provide the correct MIME type for the attachment.
