### ISSUE TITLE
disappearing notifications

### ISSUE THREAD

**Issue by mis2417** [k9mail/k-9#834]
I have a weird issue. Frequently, notifications for received mails (gmail account) keep disappearing. Screen is off, mail comes, sound is played (often only a part), LED blinks once and thats it. after turning the screen on there is no notification bar entry, BUT account widget (envelope) shows correct count. it is slso inconsistent, happens sometimes, other times notification shows up and stays. 
KDE Connect and Skins have access to notifications, but it is only this app suffering from this. also disabling those improved nothing. 
Did not happen in CM 11 or pre 5.00x versions, 
Is there anything I can do to help resolve this? logs, etc? 

Cyanogenmod 12.1, K9 5.006 from play store.

**Comment by cketti** [comment]
Notifications are canceled when the message list or folder list is displayed. Depending on the Android version this may also be true if the screen is active behind the lock screen.
The widget displays the number of unread messages. So that's mostly unrelated to notifications.

Without more information there is nothing we can do about this. Unfortunately, I don't believe a debug log will contain relevant information to find out what's going on.

**Comment by mis2417** [comment]
normally notifications would stay until manually  dismissed, but not in this case, even the notification drawer is empty. I understand this: "if the screen is active behind the lock screen" but isn't this the case only when the app is displayed behind the lockescreen? I never leave it open, and I'm using stock CM12.1 lockescreen. This also happens when the device is not locked, just screen is off. 

so there is nothing i can do about it? I tried creating account from scratch, clearing data, uninstalling application, nothing helped. Also, I'm not 100% sure but I think other accounts are not affected by this. (4 accounts, all gmail, everything except ringtone and synchronization is identical).

**Comment by SJD** [comment]
I suddenly stopped getting notifications for incoming mail too. It may have been when I updated to Android 6; this on a Nexus 5. I haven't noticed a notification sound/ vibration for incoming mail so I don't know if they turned up and disappeared again, or if the notification was never generated in the first place. The widget showing new unread mail still works.

**Comment by RolandSpencer** [comment]
I've also stopped getting notification sounds most of the time.  I still get the notifications in the bar and the widget's unread count updates correctly, but most of the time the new mail notification sounds do not play.

**Comment by mis2417** [comment]
i noticed something odd. i have 3 accounts set up (2 gmails) but only notifications from my main/default account dissapear. other stay, even if notification that disappeared came later.

**Comment by mis2417** [comment]
accidental closing. my bad, sorry.

**Comment by mis2417** [comment]
changing phones from Samsung Galaxy S4 (cyanogenmod 12.1) to LG G4 stock Marshmallow. clean install of k9mail, problem still persists. this is becoming unbearable.

**Comment by mis2417** [comment]
since there is apparently no way to fix this... 

@RolandSpencer here's a workaround that worked for me:
force close the application, clear all data and (instead of importing accounts from backup file) recreate all accounts from scratch, by hand (be careful around notifications settings). 
belive me, I know how painful that can be (30 minutes for 3 accounts) - general settings, account settings, folder settings. in the end however - l think it's worth it, no more missedit app and whatever unread plugins. 

sadly, I don't have the faulty (I think) backup file anymore, but I did notice some new things in the application after that - funny thing...

**Comment by mis2417** [comment]
well, happiness didn't last long. 
after changing "privacy" setting "hide subject in notifications" to always  - this issue came back.

**Comment by zeorin** [comment]
+1 I've also got the issue... I don't get any K9 notifications.

**Comment by mis2417** [comment]
http://imgur.com/ZJAWPc3

that's not it, but thanks for looking. still an issue.

**Comment by mis2417** [comment]
I have installed tasker and created a profile that intercepts k9 notifications and creates it's own notification with sound (mp3 file). notification is 3 second long, but I noticed that if k9 notification dissappears, that new one also gets cut (almost instantly). this also applies only to k9 notifications, no other app has that problem.

**Comment by mis2417** [comment]
problem does not exist in nougat (7.1)

**Comment by mis2417** [comment]
well, actually it does exist, but after all this time I rather suspect it's something like tasker/autonotification plugin/some other app. that said, it ONLY affects default account new mail notifications (and only k9mail).

**Comment by lobstaj** [comment]
I'm also experiencing this issue on Android 7.1. Could this issue be re-opened?

On those times when this happened to me, the screen of the phone is woken up, and sometimes the start of the notification sound is played. But then the screen goes off, notification led is inactive, and when I wake the screen, I don't have any notification. I'm only experiencing this quite rarely (or at least I've noticed it only rarely), but since it leads to the situation that I don't notice new mail at all (potentially in days), I think it is quite serious.

If the behaviour is that the notification is cancelled when the message list is displayed, is there maybe another event (which depicts the "displayed"), which could be reacted to? Is it so that Android 7.1 renders the app view also sometimes when it's in the background?

Or could there be a setting which would let the user choose to cancel the notification only when the mail is opened (and/or marked as read)?

I've tried to reproduce the issue by leaving k9 in the foreground (with the correct inbox message list open) and let the screen go off. I was hoping that this would lead to the app view being rendered in the background and that this would get the notification cancelled. But I've not been able reproduce the behaviour willingly.

Thanks already for looking into this.

J

**Comment by benjmarshall** [comment]
I have this same issue. Android 8.1 fresh install of K9 and only one account configured. I have had the same problem with both notifications set to show and obfuscate. Has there been any progress on a fix, or any know workarounds?

**Comment by Dagefoerde** [comment]
Please reopen @valodim. Same issue here. Only happens with the (android main) Gmail account, but not with my other account. Thanks in advance for your investigation.

**Comment by Mrfiregem** [comment]
I have the same issue with Android 7.0 on the lg k20. Notifications show up while the sync notification appears, but disappear shortly after the sync notification is completed and leaves

**Comment by Chris78** [comment]
I have used LineageOS 16 with an earlier version of K-9Mail (probably 5.403) and without MindTheGApps _without_ problems.
Now I have the same issue as described here _after flashing MindTheGapps_ to my phone and installing K-9Mail from the play store.
So I downloaded the older version (5.403) today from apkmirror, but it shows the same problems now too. Sometimes no notification at all, in most cases the LED blinks for a few seconds only and then stops while the notification also auto-disappears, along with the envelope in the status bar. Even worse: Now it happened that I didn't see new mails even after opening k-9mail, until I manually pulled down to load new mails.

So it looks to me like the Google Apps are at least part of the problem.
