### ISSUE TITLE
Add signature to setup wizard

### ISSUE THREAD

**Issue by sirtet** [k9mail/k-9#842]
The signature is auto-populated, what makes a nice advertizing for K9, and yes, i think other apps (ios?) do  that too.

But it would be nice to inform the user about that step by showing a pre-populated form in the wizard, so ppl are aware of it more and can easily change it.

**Comment by cketti** [comment]
I don't want the setup process to be longer than necessary. Ideally, we remove options from the existing flow instead of adding more.
The signature is displayed in the compose window, so users shouldn't be surprised of the fact there is a (default) signature.

But making it easier to change the default signature is certainly something we should do. Maybe instead of an input field at the bottom of the compose screen we could make it a drop-down (spinner) to select one of the user's signatures, the option to specify a different one just for this message (show the input field), or go to a screen to edit/add to the user's signatures.

@jancborchardt Any thoughts on this?

**Comment by jancborchardt** [comment]
Yeah, I wouldn’t add the signature to the setup process either.

And making it easier to change involves simplifying the options vastly, as discussed elsewhere. Rather than adding more and more things. ;)
