### ISSUE TITLE
Add ability to configure which notification actions are displayed

### ISSUE THREAD

**Issue by sebastiannielsen** [k9mail/k-9#943]
The notification button gets too large, so even tough I in settings have selected to show the "Delete" button, the buttons will be:

(icon) Reply (icon) Mark as R...

(with three dots, like theres not enough space to show the whole button "Mark as Read" and the "Delete" button)

Proposed suggestion to fix this:
1: Allow in Settings\Notifications, to select the size of the notification text.
2: Add options in Settings\Notifications, to show/hide the Reply button, and also show/hide the "Mark as read" button.

Phone: SM-G980A (Samsung Galaxy S6 32GB Camo Blue AT&T) running Android 5.1.1

Image:
![Too large notification](http://i.stack.imgur.com/tbbFY.png)

**Comment by cketti** [comment]
"Vanilla Android" displays all actions and ellipsized text as necessary. So this problem seems to be specific to the Android version provided by your OEM.
You could provide a shorter text for the translation of the 'mark as read' action by going to [our Transifex project site](https://www.transifex.com/k-9/k9mail/). The key for this particular string is `notification_action_mark_as_read`

Adding the ability to configure which actions are displayed in notifications is certainly an option. But for me this is a very low priority item.

**Comment by carbsk** [comment]
Hi,

Well, opposite to response from notifications, for me have access to "Delete" button is important, because I constantly getting spam, so I can delete it really quickly from there, but I can't do it for now, I have to get into the e-mail, delete and get out again, or I can do it from notifications if I have sideways my cell.

As you said, maybe selecting icons to show or maybe just decide if I want to see the button's title, or not decide, just remove it (lol), in this time everybody knows that "arrow" are for response, "open envelop" for mark as read, "trash can" for delete, easy. :)

Any way, what you guys are doing with this app it's great, hope fix this soon.

Thanks.
Greetings.

**Comment by carbsk** [comment]
Hi, 

To solve this quickly isn't able just leaving button icons and removing it's tittles?, with some white spaces between them, everybody knows what icon is for.

Regards.

**Comment by marmistrz** [comment]
If vanilla Android desperately wants text, maybe one could work it around by setting the text to `String foo = " "`?

**Comment by cketti** [comment]
I created #3530 to outline what I have in mind for configurable notification actions.
