### ISSUE TITLE
Individually encrypt attachments when using inline PGP

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#948]
Only encrypting the body when using inline PGP seems like a bad idea. We should also encrypt the attachments instead of displaying a warning that attachments won't be encrypted.

**Comment by gdt** [comment]
Is there actually a way defined in the standards to encrypt attachements?  The in-line PGP encoding pre-dates MIME and is basically an ascii/ascii transformation (perhaps ok with UTF-8 now).   Are any other MUAs able to process any sort of inline encoding e.g. for application/octet stream with a tgz?
I agree that sending unencrypted attachments seems wrong.   So perhaps sending the message should fail with an error instead.

Another question is why do people want to use inline rather than MIME, and why support it at all?   I certainly did it that way long ago, but it seems all MUAs that are even sort of maintained can do RFC3156.

**Comment by clawoflight** [comment]
@gdt well... K9 doesn't support PGP/MIME properly yet.
At least not in the release version, not sure exactly how well the git version works right now.

Sooo, yeah. K9 users are still stuck on inline for now.

**Comment by Valodim** [comment]
there is no widely supported and reliable way to encode attachments in PGP/INLINE, other than to have attachments in individually encrypted files (i.e. attachment.pdf.gpg)

**Comment by alanthehat** [comment]
Is there a reasonable way of offering to encrypt (or sign) attachments? 
The current workflow requires attachments to be already encrypted(/signed) before the message is composed, which is clunky & error-prone though not particularly difficult.

**Comment by alanthehat** [comment]
It seems to me that inline attachments are part of the message (as delivered) so should be sent for encryption in that position. 
Pre-MIME messages (which these are) only have 2 parts - header & body with any attachments within the body

**Comment by SecTec** [comment]
Do you plan to implement PGP/MIME or sign/enc attachments or do you say that it is less important?
I asking because I am using K-9 mail only because of its GPG integration.

**Comment by Valodim** [comment]
OpenPGP integration is a feature which is important to us, and we are working hard on it. There has been a lot of progress since the last release, however none of that is in the current stable release. We hope to release a new stable with pgp/mime support and in a couple of months.

(closing this issue, since encrypted attachments for pgp/inline will not be implemented)
