### ISSUE TITLE
Cannot send mail when connected to ipv6 LTE AP

### ISSUE THREAD

**Issue by kengoldsholl** [k9mail/k-9#955]
When my phone is connected to the internet over wi-fi, I have no trouble sending mail through a mail server hosted by Rackspace. When wi-fi is switched off, and the phone uses an LTE connection over an ipv4 AP, it can still send mail. When the phone connects to an ipv6 AP, it is not able to send mail. K-9 is able to retrieve mail from the same server under all conditions, but cannot send it under that one condition, even though no server settings are changed. Are some send mail server settings affected by ip version?

Saying the configuration must be wrong is not an engineering response. If that is the case, then there must be a reason why K-9 can send mail when connected via wi-fi or ipv4 LTE, with no other changes to server settings.

It's possible this is a Rackspace issue, but since I can only replicate it (every time) with K-9, it's not easy to convince them it's their issue. I have not tried this with the default Android mail client.

**Comment by cketti** [comment]
Simply opening another issue without providing more information won't get you a different response (see #953). I told you to write to the mailing list because there's a broader audience that may be able to help you track down the cause of the problem. Once that's identified developers can get to work. Using very sparse developer resources to investigate "it doesn't work" situations is not a very good use of our time.

A couple of notes:
* Our [guidelines for contributing](https://github.com/k9mail/k-9/blob/master/CONTRIBUTING.md) contain instructions on what information a bug report should contain.
* Downloading and sending mails use two different services. So it's easily possible for only one of them to be reachable when using IPv6.

**Comment by kengoldsholl** [comment]
Judging by your response, I am guessing you are not an engineer, as you 
ignore what I said. I did research the issue, else how do you think I 
discovered the problem was related to ipv6? Did you not even read what I 
wrote?  I didn't say "it doesn't work", I gave you the conditions and 
tests I performed.

If you don't have the resources to investigate further, I can appreciate 
that, as this bug probably affects just a few per cent of K-9 users.  
However, your arrogance and condescension is uncalled for.

I'm not the only person with this issue:

https://community.rackspace.com/products/f/28/t/4071?pi1830=2

**Comment by gdt** [comment]
cketti's point was that bugs are not a helpdesk mechanism, and you were pointed to the list.   There isn't enough information in your report to know that there is actually a bug in k-9 (vs someplace else, vs configuration).   We don't know, for example, if when connected to this 'ipv6 AP' you do or don't have a v4 address, and what kind of NAT is going on, if your mailserver has AAAA records, or have traces of packets, or even logs from adb logcat.

**Comment by kengoldsholl** [comment]
I'm not looking for help, I already worked around it (by forcing my 
phone to only use ipv4 APNs).  There's a bug, whether it's in Rackspace 
servers, T-Mobile gateways, or k-9,  I don't know (I think it's in k-9 
or the network driver in android).

I only posted it because at some point, when more LTE networks use ipv6, 
this will become a bigger issue. Ignore it for now and don't call it a 
bug, that's your call, but I really don't care for the attitude.
