### ISSUE TITLE
Progress indicator with throughput while fetching a message / attachment

### ISSUE THREAD

**Issue by frittentheke** [k9mail/k-9#999]
Currently only a simple popup with no metric of remaining time or download speed is shown when a message is partially on the phone but the rest is fetched from the IMAP server. Especially with big messages and a slow connection some indication of how long this might take would be great. This somewhat relates to  issue #574

**Comment by lbdroid** [comment]
I'd like to add a bit to this report; especially when you are dealing with flakey networks, I often find that events freeze up altogether. Along with a progress indicator, ability to cancel an event, and ability to *reset the connection* would be highly useful.

**Comment by harjot-oberai** [comment]
I have been working on this [idea](https://github.com/k9mail/k-9/wiki/Google-Summer-of-Code-2017#progress-indicator-while-fetching-attachment).
It demands percentage progress of download of an attachment, and I have figured out a way to calculate the number of bytes downloaded in realtime. As we already know the size of the attachment beforehand, so basically, now the task reduces to creating a new ProgressDialogFragment with an actual percentage progress bar and just updating it as the number of downloaded bytes increase.

My approach basically includes incrementing the number of bytes downloaded each time `inputstream.read()` is called, as it just reads a single byte. 
The accuracy of this method is about **98% - 99%** . The small difference between actual size and calculated one is due to the fact that I have not been able to intercept all `read()` calls. Still the method would work perfectly for displaying the **percentage of attachment downloaded**.

I have tested my approach and it works perfectly. I will make a PR as soon as I refactor the the code and implement the new Dialog Fragment.

**Comment by harjot-oberai** [comment]
The above mentioned approach did not work . 
But I figured out another way to get the download progress. It was much simpler to implement as well. 

Here is the PR : [https://github.com/k9mail/k-9/pull/2307](https://github.com/k9mail/k-9/pull/2307)

The new approach includes using the temporary file created to store the attachment data. Basically a variable `filledBytes` is update every 50 ms with the size of temp file. Since we already know that the total size of temp file must be equal to attachment size, we can easily use this data update the progress dialog.
